### PR TITLE
Overcome path with trailing spaces 2

### LINKED ISSUE #1861: Aborting InvalidPathException when processing mounted folders with invalid file names
Reported by an user:
Screenshot_20230901-195840_WhatsApp

We should log and skip the file at least, if not possible to access its contents using an alternative way.

### PR DESCRIPTION
**Pull request by lfcnassif**
Fix #1861 using a simple approach to skip problematic files and folders, warning users on the Console.

### CODE REVIEW

**Comment by lfcnassif** [comment]
@patrickdalla since you are busy with other unrelated things, I'll merge this. If processing aborts with your test data, we can reopen #1861.

**Comment by patrickdalla** [comment]
It had finished: none of the files inside folders with leading spaces were processed.
I will check the log if any report about these non processed files were included.
image

**Comment by patrickdalla** [comment]
It didn't report any "Directory ignored" entry in processing log.

**Comment by lfcnassif** [comment]
Could you please double check? This is printed in the Console (and also in the log) here:
```
2023-10-26 16:31:43     [ERROR] [engine.datasource.FolderTreeReader$FolderVisitor]                      File/Folder ignored: f:\teste-files\spaces\dir\b.txt : java.nio.file.NoSuchFileException: f:\teste-files\spaces\dir\b.txt
2023-10-26 16:31:43     [ERROR] [engine.datasource.FolderTreeReader$FolderVisitor]                      File/Folder ignored: f:\teste-files\spaces\dir\s.txt    : java.nio.file.NoSuchFileException: f:\teste-files\spaces\dir\s.txt
2023-10-26 16:31:43     [ERROR] [engine.datasource.FolderTreeReader$FolderVisitor]                      File/Folder ignored: f:\teste-files\spaces\dir\b.txt : java.nio.file.NoSuchFileException: f:\teste-files\spaces\dir\b.txt
2023-10-26 16:31:43     [ERROR] [engine.datasource.FolderTreeReader$FolderVisitor]                      File/Folder ignored: f:\teste-files\spaces\dir\s.txt    : java.nio.file.NoSuchFileException: f:\teste-files\spaces\dir\s.txt
2023-10-26 16:31:43     [ERROR] [engine.datasource.FolderTreeReader$FolderVisitor]                      File/Folder ignored: f:\teste-files\spaces\dir2 : java.nio.file.NoSuchFileException: f:\teste-files\spaces\dir2
2023-10-26 16:31:43     [ERROR] [engine.datasource.FolderTreeReader$FolderVisitor]                      File/Folder ignored: f:\teste-files\spaces\dir3 : java.nio.file.NoSuchFileException: f:\teste-files\spaces\dir3
2023-10-26 16:31:43     [ERROR] [engine.datasource.FolderTreeReader$FolderVisitor]                      File/Folder ignored: f:\teste-files\spaces\mydirectory : java.nio.file.NoSuchFileException: f:\teste-files\spaces\mydirectory
2023-10-26 16:31:43     [ERROR] [engine.datasource.FolderTreeReader$FolderVisitor]                      File/Folder ignored: f:\teste-files\spaces\dir2 : java.nio.file.NoSuchFileException: f:\teste-files\spaces\dir2
2023-10-26 16:31:43     [ERROR] [engine.datasource.FolderTreeReader$FolderVisitor]                      File/Folder ignored: f:\teste-files\spaces\dir3 : java.nio.file.NoSuchFileException: f:\teste-files\spaces\dir3
2023-10-26 16:31:43     [ERROR] [engine.datasource.FolderTreeReader$FolderVisitor]                      File/Folder ignored: f:\teste-files\spaces\mydirectory : java.nio.file.NoSuchFileException: f:\teste-files\spaces\mydirectory
```

**Comment by patrickdalla** [comment]
Right. "Folder ignored" log appeared for the toppermost folder with trailing spaces. 


2023-10-26 15:58:01	[ERROR]	[engine.datasource.FolderTreeReader$FolderVisitor]			File/Folder ignored: c:\Users\Adminwks\Documents\CasosPatrick\trailingspaces\dir : java.nio.file.NoSuchFileException: trailingspaces\dir 
2023-10-26 15:58:01	[ERROR]	[engine.datasource.FolderTreeReader$FolderVisitor]			File/Folder ignored: c:\Users\Adminwks\Documents\CasosPatrick\trailingspaces\dir : java.nio.file.NoSuchFileException: trailingspaces\dir

**Pull request merged**
