### PR TITLE
Minor GUI Improvements #823

### PR DESCRIPTION
**Pull request by tc-wleite**
Implement very minor GUI changes described in #823.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @tc-wleite!

**Review by lfcnassif — COMMENTED** [review]
@tc-wleite commit df07df2 assumes just the top Window has no parent, right? Maybe this could change in the future acidentally. What do you think about creating a public HexViewerPlus.setParent(x) method?

**Comment by tc-wleite** [comment]
> @tc-wleite commit [df07df2](https://github.com/sepinf-inc/IPED/commit/df07df267fbcbe51431f61459487908db5f26634) assumes just the top Window has no parent, right? Maybe this could change in the future acidentally. What do you think about creating a public HexViewerPlus.setParent(x) method?

Yes, that would be a better approach.
Maybe when creating a viewer, the parent window could (or should) be passed.
Let me take a look here...

**Comment by tc-wleite** [comment]
I changed for an alternative approach, allowing setting explicitly the owner window of a viewer.

**Review by lfcnassif — APPROVED** [review]

**Pull request merged**
