### PR TITLE
Changes related to Issue #65 - Store all email headers as metadata

### PR DESCRIPTION
**Pull request by thalespr**
* RFC822 and OutlookPST Parsers now including all email headers as metadata;

### CODE REVIEW

**Comment by thalespr** [comment]
Considerations:
* Values in the 'headersBlackList' from Outlook PST Parser needs to be reevaluated;
* Headers with multiple values (like **Received**) are agreggate in one row in the metadata view with the values being separated by comma. It may be difficult to read them;
* Tested with a bunch of PST and EML files and it is working fine so far...
* Searching headers fields that present a diversity of values may not be useful...
* In the PST Parser, we can optimize the insertion of the headers as metadata. Some headers (From, To, Bcc, CC...) are included apart... They are treated separately, I'll see if we can add them together with the other headers at once. 

Feel free to make suggestions on this PR.

Best Regards,

**Comment by lfcnassif** [comment]
Thanks @thalespr! Could you give an example about your 4th consideration?
I took a quick look at the changes, I think headers could span multiple lines, maybe the split("\n") should be changed.
Do you plan to update the OST parser too?
Thanks

**Comment by thalespr** [comment]
> Thanks @thalespr! Could you give an example about your 4th consideration?
> I took a quick look at the changes, I think headers could span multiple lines, maybe the split("\n") should be changed.
> Do you plan to update the OST parser too?
> Thanks
**Could you give an example about your 4th consideration?**
Hello @lfcnassif, An example could be the Received header, it can be anything and mostly will differ from email to email... it doesn't have a pattern, so the searching engine will hardly aggregate same entries for this field like it would do with other fields such as From, To, etc... You will have basically one entry for every email you have... In most cases, you dont know _a priori_ which SMTP servers the email message went through, so what will you search for? Although I agree that this field (Received) particularly needs to be added as metadata for further analysis.

**> I took a quick look at the changes, I think headers could span multiple lines, maybe the split("\n") should be changed.**
Agreed, actually, I noticed that some headers values aren't being printed out entirely because of that split call. I need to reevaluate that regex. 

**> Do you plan to update the OST parser too?**
Actually, the OST files are already parsed by OutlookPSTParser. But, yes, I plan doing more enhancements to PST Parser, it's not ready in my opinion to go for production even though it's storing the e-mail headers as metadata as requested in the issue. I marked this PR as draft, so people can take a look at the changes and give me feedback as it is growing.

**Comment by lfcnassif** [comment]
> Actually, the OST files are already parsed by OutlookPSTParser. But, yes, I plan doing more enhancements to PST Parser, it's not ready in my opinion to go for production even though it's storing the e-mail headers as metadata as requested in the issue. I marked this PR as draft, so people can take a look at the changes and give me feedback as it is growing.

For sure, don't worry and take your time. Actually, most OST files are parsed by LibpffPSTParser, because OutlookPSTParser (that uses java-libpst behind) fails with > 2013 OST files and falls back to LibpffPSTParser. java-libpst added support for "new" OST format some years ago, but it is very broken (https://github.com/rjohnsondev/java-libpst/issues/60) and the project seems kind dead...

**Comment by thalespr** [comment]
> > Actually, the OST files are already parsed by OutlookPSTParser. But, yes, I plan doing more enhancements to PST Parser, it's not ready in my opinion to go for production even though it's storing the e-mail headers as metadata as requested in the issue. I marked this PR as draft, so people can take a look at the changes and give me feedback as it is growing.
> 
> For sure, don't worry and take your time. Actually, most OST files are parsed by LibpffPSTParser, because OutlookPSTParser (that uses java-libpst behind) fails with > 2013 OST files and falls back to LibpffPSTParser. java-libpst added support for "new" OST format some years ago, but it is very broken ([rjohnsondev/java-libpst#60](https://github.com/rjohnsondev/java-libpst/issues/60)) and the project has no release since 2017...

Nice to know that background. You saved me a lot of research time. I'll take a look at LibpffPSTParser. Thanks.

**Comment by thalespr** [comment]
Just updated LibpffPSTParser. I think now every e-mail parser is storing email headers as metadata. If anyone could test, I would really appreciate that. Thanks in advance.

**Comment by lfcnassif** [comment]
Thanks @thalespr, will review and test soon.

**Comment by lfcnassif** [comment]
@thalespr sorry for not reviewing this yet, I'm prioritizing PRs ready for review and some important changes for 4.0.0.

**Comment by thalespr** [comment]
> @thalespr sorry for not reviewing this yet, I'm prioritizing PRs ready for review and some structural changes for 4.0.0.

Don't worry, @lfcnassif. This is a minor enhancement (not in priority queue since the beginning...). Take your time and let me know if I can help you in something. Cheers.

**Comment by thalespr** [comment]
> Edit: I did some adjustments in the writeInternetHeaders() from LibpffPSTParser but I was not able to see if it is ok. So I decided to not push those changes.

Decided to commit the changes in the writeInternetHeaders() method from LibpffPSTParser. Need beta testers to evaluate those changes.

Planning to mark this PR as ready for review next weekend.

**Comment by lfcnassif** [comment]
> Need beta testers to evaluate those changes.

This would be very nice, unfortunately we don't have these kind of resources...

**Comment by thalespr** [comment]
> > Need beta testers to evaluate those changes.
> 
> This would be very nice, unfortunately we don't have these kind of resources...
> 
> edit: so we have to do peer review and testing...

Sorry, just saw your edit note right now. Yes, I absolutely agree to do peer review. Maybe other colleagues/contributors/users have email messages and could help testing it too. If so, I would like to ask them to please give it a go :-) It will be welcome.

**Comment by thalespr** [comment]
Good news: Talked to @visgueira and he's willing to contribute to IPED's project testing new features enhancements like this one.

**Comment by lfcnassif** [comment]
Just fixed fields spanning multiple lines:
image

**Comment by lfcnassif** [comment]
After testing this with ~1M emails, including corrupted and carved, I noticed a lot of corrupted headers were being added. So I created a white list of common headers collected from that dataset + headers starting with X-. This list can be improved further in the future, but I think this is ok to be merged now.

**Comment by thalespr** [comment]
Thanks for reviewing, fixing and accepting this PR @lfcnassif.

**Comment by lfcnassif** [comment]
You're welcome!

**Pull request merged**
