### PR TITLE
#847 identify QRCodes

### PR DESCRIPTION
**Pull request by hauck-jvsh**
Actually this also identify barcodes in images.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh! I will try to take a look next week.

**Comment by hauck-jvsh** [comment]
I did some tests and I found that this task takes a time similar to the thumb task:
QRCodeTask:	Processing Time:	55s (6%)
ImageThumbTask:	Processing Time:	59s (7%)

**Comment by hauck-jvsh** [comment]
I also found that there are some false positives on barcode detector. I don't known if this should enabled what do you think?

**Comment by lfcnassif** [comment]
> what do you think?

I think barcodes are less priority to us. But maybe this could be configurable, I you think this is worthy to implement.

If an image has multiple qrcodes, does the lib detect all of them? We could save the results for all of them in a List<?> before saving the results in extra attributes.

**Comment by hauck-jvsh** [comment]
> > what do you think?
> 
> I think barcodes are less priority to us. But maybe this could be configurable, I you think this is worthy to implement.
> 
> If an image has multiple qrcodes, does the lib detect all of them? We could save the results for all of them in a List<?> before saving the results in extra attributes.
I didn't test with an image with more than one qrcode, I will create an image with a lot of qrcodes and test.

**Comment by hauck-jvsh** [comment]
@lfcnassif  I think this is ready for merging. It is decoding only QRCodes, as this is allows decoding multiple QRcodes in a single image. If the barcode dector is used only one QRCode or barcode per image is deteced. 
This closes #847

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh. I'll review this after finishing #908, that is causing me some trouble...

**Review by lfcnassif — APPROVED** [review]

**Pull request merged**
