### PR TITLE
Load and process map data only when it is visible

### LINKED ISSUE #1710: Load and process map data structures just when it is shown.
Postpone loading of map to the moment it is really necessary, when it becomes visible.

### PR DESCRIPTION
**Pull request by patrickdalla**
Temporarily saves unprocessed tableModelEvent when map is hidden to be processed when it is shown

Closes #1710.

### CODE REVIEW

**Review by lfcnassif — APPROVED** [review]
Thanks @patrickdalla!

**Review by lfcnassif — CHANGES_REQUESTED** [review]
This needs a fix. After more tests, this change caused an issue that, if a subset of georeferenced items were in result set when the map is rendered the first time, the other geo-referenced items outside the first subset are never plotted after clearing all filters or after applying another filter to list them.

**Comment by patrickdalla** [comment]
Right. I will correct.

**Comment by patrickdalla** [comment]
> This needs a fix. After more tests, this change caused an issue that, if a subset of georeferenced items were in result set when the map is rendered the first time, the other geo-referenced items outside the first subset are never plotted after clearing all filters or after applying another filter to list them.

@lfcnassif , I could not reproduce it. Could you detail better when does it occurs? Any exception was thrown on app log?

**Comment by patrickdalla** [comment]
I found the cause. That is an unrelated bug. I will register an specific issue an put the commit in this same PR.

**Comment by patrickdalla** [comment]
Try with the last commit. [dba8360](https://github.com/sepinf-inc/IPED/pull/1711/commits/dba8360b58773d0907008e54d7c73f3d8c28b7be)

**Comment by lfcnassif** [comment]
It worked, thank you!

**Review by lfcnassif — APPROVED** [review]

**Pull request merged**
