### PR TITLE
Usn reason timestamp

### LINKED ISSUE #1503: Expand timestamp events from UsnJrnlParser and enable it in forensic and pedo profiles
Currently the NTFS USN journal parser `extractEntries` parameter is disabled. This can be very useful for e.g. CSAM or malware cases. Usually it extracts about 300k events from each NTFS partition.

Should we enable it in `pedo` profile by default? And perhaps on `forensic` profile?

### PR DESCRIPTION
**Pull request by patrickdalla**
Closes #1503 .

### CODE REVIEW

**Comment by lfcnassif** [comment]
Hi @patrickdalla, thanks for the Unit test fixes.

Could you implement the ParserConfig.xml config files merging idea? So we would be able to turn records extraction on in forensic and pedo profiles without duplicating ParserConfig.xml into them.

**Comment by patrickdalla** [comment]
Yes. I will.

Em seg., 27 de mai. de 2024, 08:09, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
There is already the ParsersConfig class in iped.engine.config package, it may be used for that.

**Comment by patrickdalla** [comment]
Hi @lfcnassif . I have created the merging code for ParserConfig.xml from profile. It replaces completely all the parser tag with the same class attribute from default config with the configured in profile. As it was implemented, only changed and additions can be done (no removal).

It works in master and can be merged, but maybe I have to make some changes to avoid conflict in UI config, in which branch i will start working now. There, as the the user can use the UI to select which Parsers to use (including removing some), I replace completely the ParserConfig. So, I will make some distinctions to inform if the config is to be merged ou replaced completely. Maybe a simple attribute in parsers tag. But I will change it in UI config branch, right?

**Comment by lfcnassif** [comment]
Thanks @patrickdalla! Parser removal while merging multiple ParserConfig.xml files is not needed for this feature, it is fine. When it is needed, I think a new `enabled` attribute in xml parser element would be enough to flag the merging code it should be removed.

**Comment by lfcnassif** [comment]
@patrickdalla, I think you enabled a wrong parser in forensic and pedo profiles. It should be `UsnJrnlParser` with an enabled `extractEntries` param right?

**Comment by patrickdalla** [comment]
Sorry. It is correct now.

**Review by lfcnassif — APPROVED** [review]
Thanks @patrickdalla! I did minor changes and updated the properties prefix to a shorter one.

**Pull request merged**
