### PR TITLE
#1631: feature to select items and (subItems / parent / references / referencedBy)

### PR DESCRIPTION
**Pull request by aberenguel**
…referencedBy)

### CODE REVIEW

**Comment by lfcnassif** [comment]
Hi @aberenguel, thank you very very much for all your issue reports and fixing or enhancing PRs!

About this feature, do you know the Ctrl+A then Space key could be used to check all items into those related items tabs? Do you think it is not straightforward and are proposing an easier way to achieve the same thing?

**Comment by aberenguel** [comment]
> Hi @aberenguel, thank you very very much for all your issue reports and fixing or enhancing PRs!
> 
> About this feature, do you know the Ctrl+A then Space key could be used to check all items into those related items tabs? Do you think it is not straightforward and are proposing an easier way to achieve the same thing?

I known. But I it is boring to do it several thousand times. In my case, I have 2K images. What I wanted was to select all chats with those images.

**Comment by wladimirleite** [comment]
> I known. But I it is boring to do it thousand times. In my case, I have 2K images. What I wanted was to select all chats with those images.

The key point is that @aberenguel proposal allows dealing with multiple items at once, while the current procedure (described by @lfcnassif) must be repeated for each item, right?!

**Comment by lfcnassif** [comment]
Oh I got it now, it checks all related items to all highlighted items in the main table, right? Sorry I didn't see the code changes yet and there is no issue describing the proposal in detail.

**Comment by aberenguel** [comment]
> h I got it now, it checks all related items to all highlighted items in the main table, r

That is it! The check is done for all highlighted items. 
I used some shortcuts due to the previous use CTRL+R / ALT+R. But now the check functions are not bound to shortcuts anymore. I think the shortcuts (CTRL+R / ALT+R) except  could be removed.

**Comment by wladimirleite** [comment]
@lfcnassif, do you think this PR should be included in the 4.2 release?
If that is the case, I can review it.

**Comment by lfcnassif** [comment]
> @lfcnassif, do you think this PR should be included in the 4.2 release?
> If that is the case, I can review it.

Sure, we can include it! Thank you @wladimirleite and @aberenguel!

**Comment by lfcnassif** [comment]
Hi @wladimirleite! I know you are very busy, but do you still plan and have a time schedule to review this? I will be on vacation again starting on November 30th, and I plan to release IPED-4.2 just with the merged PRs until that time. It would be very nice if we could include this.

**Comment by wladimirleite** [comment]
> Hi @wladimirleite! I know you are very busy, but do you still plan and have a time schedule to review this? I will be on vacation again starting on November 30th, and I plan to release IPED-4.2 just with the merged PRs before that time. It would be very nice if we could include this.

Hi @lfcnassif! 
I am sorry about the delay!
Unfortunately, the last few weeks have been very busy here.
I will finish this review by the end of the week.

**Review by wladimirleite — APPROVED** [review]
There were a lot of code changes (which I think improved the overall organization), so it is not easy to check everything, but as far as I can tell, looking at  the code changes and doing some tests, this is ready to be merged.

I tested in a real case I am working on, and these new options were very useful.
Thanks @aberenguel!

Sorry again for the delay to finish the review.

**Comment by lfcnassif** [comment]
Thank you @aberenguel for this feature and thank you @wladimirleite for your review!

**Pull request merged**
