### PR TITLE
Minor features related to metadata (#519 #520 #522)

### PR DESCRIPTION
**Pull request by tc-wleite**
This includes #519 #520 and #522

### CODE REVIEW

**Comment by tc-wleite** [comment]
@lfcnassif, about #520, I tried to add the property name filter without reducing the space available for the list of values.
Of course, there are other possible layouts...
Feel free to make any adjustments or let me know if you want me to implement another solution.

**Comment by lfcnassif** [comment]
I couldn't wait to test it :)
image

image

That's a simple solution, seems good to me! I tested on a screen with 1360x768, maybe just shortening the portuguese background help text?

**Comment by lfcnassif** [comment]
Maybe change the left label to "Filtrar:" and the text areas to "Propriedades" and "Valores"...

**Comment by tc-wleite** [comment]
Made the suggested changes. 
It looks clearer this way and should fit better in lower resolutions.

**Comment by tc-wleite** [comment]
Made a minor adjustment in the copy icon, using a lower resolution one.
image

**Comment by lfcnassif** [comment]
Thank you!

**Pull request merged**
