### PR TITLE
Support iLBC audios (#1798)

### LINKED ISSUE #1798: Support iLBC (Internet Low Bitrate Codec) audios
As discussed in #1797.

### PR DESCRIPTION
**Pull request by tc-wleite**
Closes #1798.

### CODE REVIEW

**Comment by tc-wleite** [comment]
One sample audio in LBC format:
[sample.zip](https://github.com/sepinf-inc/IPED/files/12267093/sample.zip)

**Comment by tc-wleite** [comment]
@lfcnassif / @hauck-jvsh, I found a possible issue in our internal remote transcription service.
After the changes I made, LBC audios were processed fine by local transcription (both Vosk and Wav2Vec2).
MPlayer conversion seems fine (it was used in the local transcription and I ran it manually successfully, using the command line defined in "convertCommand").
However, when using the remote service, no LBC audio was transcribed (I have ~1000 files here).
They all caused the following error:

`2023-08-05 08:57:47	[WARN]	[task.transcript.RemoteWav2Vec2TranscriptTask]			Fail to transcribe on server: XX.XX.XX.XX:NNNN audio: LBC/XXXXX.lbc error: Exception while transcribing: java.io.IOException: Failed to convert audio to wav.
`

Does anything need to be set on the server side to handle other extensions/mime-types?

**Comment by lfcnassif** [comment]
Thank you @tc-wleite this PR!

I think the allowed mimeType control is just checked on client side. A possible cause could be an older mplayer version used in our Linux cluster not supporting iLBC format yet. We would need to log into one worker node and run mplayer on one of your samples to test, thanks for them!

**Comment by tc-wleite** [comment]
> A possible cause could be an older mplayer version used in our Linux cluster not supporting iLBC format yet.

That makes sense. As far as I know, the support to iLBC is very old, but I guess it depends on how MPlayer was compiled. Internally MPlayer relies on FFMpeg to decode several format, including this one.

**Comment by tc-wleite** [comment]
Just as additional information, the output of `mplayer -ac help` from the MPlayer version we used in Windows, including a line mentioning the support to iLBC through FFmpeg/libilbc:

```text
MPlayer Redxii-SVN-r38109-6.2.0 (i686) (C) 2000-2018 MPlayer Team
Using FFmpeg N-91255-g7b80df677a (2018-06-09 12:36:24 +0530)
Compiled on 2018-06-10 04:01:36 EDT (rev. 1)
Available audio codecs:
ac:     afm:      status:   info:  [lib/dll]
wma9dmo     dmo       working   Windows Media Audio 9 DMO  [wma9dmod.dll]
wmadmo      dmo       working   Windows Media Audio DMO  [wmadmod.dll]
wma9spdmo   dmo       working   Windows Media Audio 9 Speech DMO  [wmspdmod.dll]
wma9spdshow dshow     working   Windows Media Audio 9 Speech DShow  [wmavds32.ax]
ffqdm2      ffmpeg    working   FFmpeg QDM2 audio  [qdm2]
ffqdmc      ffmpeg    working   FFmpeg QDMC audio  [qdmc]
qdmc        qtaudio   working   QuickTime QDMC/QDM2 audio  [QuickTime.qts]
ffqclp      ffmpeg    working   FFmpeg QCLP audio  [qcelp]
qclp        qtaudio   working   QuickTime QCLP audio  [QuickTime.qts]
qtmace3     qtaudio   working   QuickTime MACE3 audio  [QuickTime.qts]
qtmace6     qtaudio   working   QuickTime MACE6 audio  [QuickTime.qts]
zygoaudio   qtaudio   working   Zygo audio  [ZyGoAudioS.qtx]
ffra144     ffmpeg    working   FFmpeg RealAudio 1.0  [real_144]
ffra288     ffmpeg    working   FFmpeg RealAudio 2.0  [real_288]
ffralf      ffmpeg    untested  FFmpeg Real Audio Lossless  [ralf]
ffcook      ffmpeg    working   FFmpeg COOK audio  [cook]
ffatrc1     ffmpeg    working   FFmpeg Atrac 1 audio  [atrac1]
ffatrc      ffmpeg    working   FFmpeg Atrac 3 audio  [atrac3]
ffatrc3p    ffmpeg    working   FFmpeg Atrac 3+ audio  [atrac3plus]
ffsipr      ffmpeg    working   FFmpeg Sipr/Acelp.net audio  [sipr]
ra144       realaud   working   RealAudio 1.0  [14_4.so.6.0]
ra144win    realaud   working   Win32 RealAudio 1.0  [14_43260.dll]
ra144mac    realaud   working   Mac OS X RealAudio 1.0  [14_4.shlb]
ra288       realaud   working   RealAudio 2.0  [28_8.so.6.0]
ra288win    realaud   working   Win32 RealAudio 2.0  [28_83260.dll]
ra288mac    realaud   working   Mac OS X RealAudio 2.0  [28_8.shlb]
ra10cook    realaud   working   RealPlayer 10 COOK audio  [cook.so]
racook      realaud   working   RealAudio COOK  [cook.so.6.0]
ra10cookwin realaud   working   Win32 RealAudio 10 COOK  [cook.dll]
racookwin   realaud   working   Win32 RealAudio COOK  [cook3260.dll]
racookmac   realaud   working   Mac OS X RealAudio COOK  [cook.bundle/Contents/MacOS/cook]
rasipr      realaud   working   RealAudio Sipro  [sipr.so.6.0]
ra10sipr    realaud   working   RealPlayer 10 RealAudio Sipro  [sipr.so]
ra10siprwin realaud   working   Win32 RealAudio 10 Sipro  [sipr.dll]
rasiprwin   realaud   working   Win32 RealAudio Sipro  [sipr3260.dll]
rasiprmac   realaud   working   Mac OS X RealAudio Sipro  [sipr.bundle/Contents/MacOS/sipr]
raatrc      realaud   working   RealAudio ATRAC3  [atrc.so.6.0]
ra10atrc    realaud   working   RealPlayer 10 RealAudio ATRAC3  [atrc.so]
ra10atrcwin realaud   working   Win32 RealAudio 10 ATRAC3  [atrc.dll]
raatrcwin   realaud   working   Win32 RealAudio ATRAC3  [atrc3260.dll]
raatrcmac   realaud   working   Mac OS X RealAudio ATRAC3  [atrc.bundle/Contents/MacOS/atrc]
ffevrc      ffmpeg    working   FFmpeg EVRC decoder  [evrc]
ffadpcmadx  ffmpeg    working   FFmpeg SEGA CRI adx codec  [adpcm_adx]
ffadpcmimaamv ffmpeg    working   FFmpeg AMV IMA ADPCM audio  [adpcm_ima_amv]
ffadpcmimaapc ffmpeg    working   FFmpeg APC IMA ADPCM audio  [adpcm_ima_apc]
ffadpcmimasmjpeg ffmpeg    working   FFmpeg SMJPEG IMA ADPCM audio  [adpcm_ima_smjpeg]
ffadpcmimaqt ffmpeg    working   FFmpeg QT IMA ADPCM audio  [adpcm_ima_qt]
ffadpcmimawav ffmpeg    working   FFmpeg WAV IMA ADPCM audio  [adpcm_ima_wav]
ffzorkpcm   ffmpeg    working   FFmpeg PCM Zork audio  [pcm_zork]
ffadpcmms   ffmpeg    working   FFmpeg MS ADPCM audio  [adpcm_ms]
ffadpcmoki  ffmpeg    working   FFmpeg ADPCM IMA Dialogic OKI  [adpcm_ima_oki]
ffadpcmafc  ffmpeg    working   FFmpeg ADPCM Nintendo Gamecube AFC  [adpcm_afc]
ffadpcmaica ffmpeg    working   FFmpeg ADPCM Yamaha AICA  [adpcm_aica]
ffadpcmdtk  ffmpeg    working   FFmpeg ADPCM Nintendo Gamecube DTK  [adpcm_dtk]
ffadpcmimarad ffmpeg    working   FFmpeg ADPCM IMA Radical  [adpcm_ima_rad]
ffadpcmimadk4 ffmpeg    working   FFmpeg DK4 IMA ADPCM audio  [adpcm_ima_dk4]
ffadpcmimadk3 ffmpeg    working   FFmpeg DK3 IMA ADPCM audio  [adpcm_ima_dk3]
ffadpcmimaiss ffmpeg    working   FFmpeg Funcom IMA ISS ADPCM  [adpcm_ima_iss]
ffadpcmimaeasead ffmpeg    working   FFmpeg ADPCM IMA Electronic Arts SEAD  [adpcm_ima_ea_sead]
ffadpcmimaeaeacs ffmpeg    working   FFmpeg ADPCM IMA Electronic Arts EACS  [adpcm_ima_ea_eacs]
ffroqaudio  ffmpeg    working   Id RoQ File Audio  [roq_dpcm]
ffsmkaud    ffmpeg    problems  FFmpeg Smacker Audio  [smackaud]
ffbinkdctaud ffmpeg    problems  FFmpeg Bink Audio (DCT)  [binkaudio_dct]
ffbinkrdftaud ffmpeg    working   FFmpeg Bink Audio (RDFT)  [binkaudio_rdft]
ffbmvaudio  ffmpeg    working   FFmpeg Discoworld II BMV Audio  [bmv_audio]
ffdsicinaudio ffmpeg    working   FFmpeg Delphine CIN audio  [dsicinaudio]
ff4xmadmpcm ffmpeg    working   FFmpeg 4XM ADPCM audio  [adpcm_4xm]
ffadpcmimaws ffmpeg    working   FFmpeg Westwood IMA ADPCM audio  [adpcm_ima_ws]
ffvima      ffmpeg    working   FFmpeg LucasArts VIMA audio  [adpcm_vima]
ffpafaudio  ffmpeg    working   FFmpeg Packed Animation File  [paf_audio]
ffwssnd1    ffmpeg    working   FFmpeg Westwood SND1  [ws_snd1]
ffinterplayacm ffmpeg    working   FFmpeg Interplay ACM audio  [interplay_acm]
ffinterplaydpcm ffmpeg    working   FFmpeg Interplay DPCM audio  [interplay_dpcm]
ffadpcmea   ffmpeg    working   FFmpeg EA ADPCM audio  [adpcm_ea]
ffadpcmear1 ffmpeg    working   FFmpeg EA ADPCM R1 audio  [adpcm_ea_r1]
ffadpcmear2 ffmpeg    working   FFmpeg EA ADPCM R2 audio  [adpcm_ea_r2]
ffadpcmear3 ffmpeg    working   FFmpeg EA ADPCM R3 audio  [adpcm_ea_r3]
ffadpcmeaxas ffmpeg    working   FFmpeg ADPCM Electronic Arts XAS  [adpcm_ea_xas]
ffadpcmeamaxis ffmpeg    working   FFmpeg EA MAXIS XA ADPCM audio  [adpcm_ea_maxis_xa]
ffadpcmpsx  ffmpeg    working   FFmpeg FFmpeg ADPCM Playstation  [adpcm_psx]
ffadpcmxa   ffmpeg    working   FFmpeg XA ADPCM audio  [adpcm_xa]
ffxandpcm   ffmpeg    working   FFmpeg XAN DPCM audio  [xan_dpcm]
ffyamahaadpcm ffmpeg    working   FFmpeg Yamaha ADPCM audio  [adpcm_yamaha]
ffadpcmthp  ffmpeg    working   FFmpeg THP ADPCM audio  [adpcm_thp]
ffadpcmthple ffmpeg    working   FFmpeg THP ADPCM little endian audio  [adpcm_thp_le]
libdv       libdv     working   raw DV audio (libdv)  [libdv.so.2]
ffdv        ffmpeg    working   FFmpeg DV audio  [dvaudio]
fflatm      ffmpeg    working   FFmpeg AAC in LATM  [aac_latm]
ffaac       ffmpeg    working   FFmpeg AAC (MPEG-2/MPEG-4 Audio)  [aac]
ffflac      ffmpeg    working   FFmpeg FLAC audio  [flac]
ffalac      ffmpeg    working   FFmpeg ALAC audio  [alac]
fftta       ffmpeg    working   FFmpeg True Audio (TTA)  [tta]
ffwavpack   ffmpeg    working   FFmpeg WavPack audio  [wavpack]
ffshorten   ffmpeg    working   FFmpeg Shorten audio  [shorten]
ffape       ffmpeg    working   FFmpeg Monkey's Audio  [ape]
ffals       ffmpeg    working   FFmpeg ALS  [als]
ffmlp       ffmpeg    working   FFmpeg MLP  [mlp]
fftruehd    ffmpeg    working   FFmpeg TrueHD  [truehd]
ffnellymoser ffmpeg    working   FFmpeg Nellymoser Audio  [nellymoser]
faad        faad      working   FAAD AAC (MPEG-2/MPEG-4 Audio)  [libfaad2]
pcm         pcm       working   Uncompressed PCM
divx        acm       working   DivX audio (WMA)  [divxa32.acm]
vdowaveacm  acm       working   vdowave ACM  [vdowave.acm]
msadpcmacm  acm       working   MS ADPCM  [msadp32.acm]
ffpcmdaud   ffmpeg    untested  D-Cinema audio (FFmpeg)  [pcm_s24daud]
ffpcms16leplanar ffmpeg    working   FFmpeg PCM 16-bit little-endian planar  [pcm_s16le_planar]
ffwmav1     ffmpeg    untested  DivX audio v1 (FFmpeg)  [wmav1]
ffwmav2     ffmpeg    untested  DivX audio v2 (FFmpeg)  [wmav2]
ffwmapro    ffmpeg    untested  WMA Pro audio (FFmpeg)  [wmapro]
ffwmall     ffmpeg    untested  WMA lossless audio (FFmpeg)  [wmalossless]
ffwmavoice  ffmpeg    untested  WMA Voice audio (FFmpeg)  [wmavoice]
ffxma1      ffmpeg    working   Xbox Media Audio 1 (FFmpeg)  [xma1]
ffxma2      ffmpeg    working   Xbox Media Audio 2 (FFmpeg)  [xma2]
ffmac3      ffmpeg    untested  Macintosh Audio Compression and Expansion 3:1  [mace3]
ffmac6      ffmpeg    untested  Macintosh Audio Compression and Expansion 6:1  [mace6]
ffsonic     ffmpeg    untested  FFmpeg Sonic  [sonic]
mpg123      mpg123    working   MPEG 1.0/2.0/2.5 layers I, II, III
ffmp3on4float ffmpeg    working   FFmpeg Multi-channel MPEG layer-3 on MP4 audio  [mp3on4float]
ffmp3on4    ffmpeg    working   FFmpeg Multi-channel MPEG layer-3 on MP4 audio  [mp3on4]
ffmp3float  ffmpeg    working   FFmpeg MPEG layer-3 audio  [mp3float]
ffmp3       ffmpeg    working   FFmpeg MPEG layer-3 audio  [mp3]
ffmp3adufloat ffmpeg    working   FFmpeg MPEG layer-3 adu audio  [mp3adufloat]
ffmp3adu    ffmpeg    working   FFmpeg MPEG layer-3 adu audio  [mp3adu]
ffmp2float  ffmpeg    working   FFmpeg MPEG layer-1 and layer-2 audio  [mp2float]
ffmp2       ffmpeg    working   FFmpeg MPEG layer-1 and layer-2 audio  [mp2]
mad         libmad    working   libMAD MPEG layer 1-2-3  [libmad]
mp3acm      acm       working   MPEG layer-3  [l3codeca.acm]
imaadpcmacm acm       working   IMA ADPCM  [imaadp32.acm]
ffgsm       ffmpeg    working   FFmpeg GSM 06.10  [gsm]
ffgsmms     ffmpeg    working   FFmpeg MS GSM  [gsm_ms]
libgsm      ffmpeg    working   libgsm GSM 06.10  [libgsm]
libgsmms    ffmpeg    working   libgsm MS GSM  [libgsm_ms]
msgsmacm    acm       working   MS GSM  [msgsm32.acm]
msnaudio    acm       working   MSN AUDIO  [msnaudio.acm]
alaw        alaw      working   aLaw
ulaw        alaw      working   uLaw
dvdpcm      dvdpcm    working   Uncompressed DVD/VOB LPCM
fflpcm      ffmpeg    working   Blu-ray LPCM  [pcm_bluray]
ffpcmlxf    ffmpeg    working   Leitch/Harris PCM  [pcm_lxf]
ffs302m     ffmpeg    working   SMPTE 302M  [s302m]
ffac3       ffmpeg    working   FFmpeg AC-3  [ac3]
ffeac3      ffmpeg    working   FFmpeg E-AC-3  [eac3]
a52         liba52    working   AC3-liba52  [liba52]
ffdca       ffmpeg    working   FFmpeg DTS  [dca]
dts         libdca    working   DTS-libdca
ffmusepack7 ffmpeg    working   Musepack sv7 audio codec  [mpc7]
ffmusepack8 ffmpeg    working   Musepack sv8 audio codec  [mpc8]
musepack    mpcdec    working   Musepack audio codec
ffdsdlsbf   ffmpeg    working   FFmpeg DSD (Direct Stream Digital), lsbit first  [dsd_lsbf]
ffdsdlsbfp  ffmpeg    working   FFmpeg DSD (Direct Stream Digital), lsbit first, planar  [dsd_lsbf_planar]
ffdsdmsbf   ffmpeg    working   FFmpeg DSD (Direct Stream Digital), msbit first  [dsd_msbf]
ffdsdmsbfp  ffmpeg    working   FFmpeg DSD (Direct Stream Digital), msbit first, planar  [dsd_lsbf_planar]
ffamrnb     ffmpeg    working   AMR Narrowband  [amrnb]
ffamrwb     ffmpeg    working   AMR Wideband  [amrwb]
libopencoreamrnb ffmpeg    working   AMR Narrowband  [libopencore_amrnb]
libopencoreamrwb ffmpeg    working   AMR Wideband  [libopencore_amrwb]
libilbc     ffmpeg    working   FFmpeg libilbc  [libilbc]
ffadcpmswf  ffmpeg    working   FFmpeg's ADPCM Flash-variant  [adpcm_swf]
voxvoice    dshow     working   VoxWare MetaVoice  [voxmvdec.ax]
ffmetasound ffmpeg    working   FFmpeg VoxWare Metasound  [metasound]
voxware     dshow     working   VoxWare  [voxmsdec.ax]
rhetorex    acm       working   Rhetorex ADPCM  [rhetorex.acm]
sanyo       acm       working   Sanyo ADPCM  [ldadp32.acm]
acelp       dshow     working   ACELP.net Sipro Lab Audio  [acelpdec.ax]
ffimc       ffmpeg    working   FFmpeg Intel Music Coder  [imc]
imc         acm       working   Intel Music Coder  [imc32.acm]
ffiac       ffmpeg    working   FFmpeg Intel Indeo Audio  [iac]
iac25       acm       working   Indeo audio  [iac25_32.ax]
ffadpcmsbpro2 ffmpeg    working   FFmpeg ADPCM Sound Blaster Pro 2-bit  [adpcm_sbpro_2]
ffadpcmsbpro3 ffmpeg    working   FFmpeg ADPCM Sound Blaster Pro 2.6-bit  [adpcm_sbpro_3]
ffadpcmsbpro4 ffmpeg    working   FFmpeg ADPCM Sound Blaster Pro 4-bit  [adpcm_sbpro_4]
ffctadp32   ffmpeg    working   FFmpeg Creative ADPCM codec  [adpcm_ct]
ctadp32     acm       working   Creative ADPCM codec  [ctadp32.acm]
ctfs32      acm       untested  Creative FastSpeech 8 and FastSpeech 10 CODEC  [ctfs32.acm]
ffdsssp     ffmpeg    working   FFmpeg Digital Speech Standars - Standard Play  mode (DSS_SP)  [dss_sp]
sc4         acm       working   SC4 : Micronas speech codec (ADPCM, MPman recording)  [mi-sc4.acm]
hwac3       hwac3     working   AC3 through S/PDIF
hwdts       hwac3     working   DTS through S/PDIF
ffvmdaudio  ffmpeg    working   FFmpeg Sierra VMD audio  [vmdaudio]
ffopus      ffmpeg    working   FFmpeg opus  [opus]
fflibopus   ffmpeg    working   FFmpeg libopus  [libopus]
ffvorbis    ffmpeg    working   FFmpeg Vorbis  [vorbis]
vorbis      libvorbis working   OggVorbis Audio  [libvorbis]
tremor      tremor    working   OggVorbis audio  [tremor]
vorbisacm   acm       working   OggVorbis ACM  [vorbis.acm]
speex       speex     working   Speex audio  [speex]
fflibspeex  ffmpeg    working   ffmpeg libSpeex audio  [libspeex]
vivoaudio   acm       working   Vivo G.723/Siren Audio Codec  [vivog723.acm]
g72x        g72x      crashing  G.711/G.721/G.723  [g72x.c]
ffg722      ffmpeg    working   G.722 Audio  [g722]
ffg7231     ffmpeg    working   G.723.1 Audio  [g723_1]
g7231ms     acm       working   G.723.1 MS  [msg723.acm]
ffg726      ffmpeg    working   FFmpeg G.726 Audio  [g726]
ffg726le    ffmpeg    working   FFmpeg G.726 little endian Audio  [g726le]
g726        acm       untested  Sharp G.726 Audio  [scg726.acm]
ffg729      ffmpeg    working   FFmpeg G.729  [g729]
g729dmo     dmo       working   verint g729  [G729DecoderDMO.dll]
atrac3      acm       problems  Sony ATRAC3  [atrac3.acm]
ALF2        acm       working   ALF2  [alf2cd.acm]
fftruespeech ffmpeg    working   FFmpeg TrueSpeech  [truespeech]
truespeech  acm       working   DSP Group TrueSpeech(TM)  [tssoft32.acm]
netspeakgsm acm       working   NetSpeak GSM  [nsgsm32.acm]
netspeakts  acm       working   NetSpeak TrueSpeech  [nstsp32.acm]
voxwarert24 acm       working   VoxWare RT24 speech codec  [nsrt2432.acm]
lhacm       acm       working   Lernout & Hauspie CELP and SBC codecs  [lhacm.acm]
lhacm2      acm       working   Voxware AC aka Lernout & Hauspie CELP and CBS codecs  [lhacm2.acm]
pscelp      acm       working   Philips Speech Processing CELP  [smcelp32.acm]
fftwinvq    ffmpeg    working   FFmpeg TwinVQ  [twinvq]
TwinVQ      vqf       working   VQF codec by NTTLabs  [tvqdec.dll]
ff8svxraw   ffmpeg    working   FFmpeg 8SVX raw  [8svx_raw]
ff8svxexp   ffmpeg    working   FFmpeg 8SVX exponential  [8svx_exp]
ff8svxfib   ffmpeg    working   FFmpeg 8SVX fibonacci  [8svx_fib]
ffon2avc    ffmpeg    working   FFmpeg On2 Audio for Video Codec  [on2avc]
hwmpa       hwmpa     working   MPEG audio pass-through for hardware MPEG decoders
msnsiren    acm       working   msn siren audio codec  [sirenacm.dll]
ffdvaudio   ffmpeg    working   FFmpeg Ulead DV  [dvaudio]
uleaddva    acm       working   Ulead DV ACM  [dvacm.acm]
spdifaac    spdif     working   libavformat/spdifenc AAC pass-through decoder  [aac]
spdifac3    spdif     working   libavformat/spdifenc AC-3 pass-through decoder  [ac3]
spdifeac3   spdif     working   libavformat/spdifenc E-AC-3 pass-through decoder  [eac3]
spdifdts    spdif     working   libavformat/spdifenc DTS pass-through decoder  [dca]
spdifmpa    spdif     working   libavformat/spdifenc MPEG AUDIO BC pass-through decoder  [mpa]
spdifthd    spdif     working   libavformat/spdifenc Dolby TrueHD pass-through decoder  [thd]
ffwavesynth ffmpeg    working   FFmpeg wave synthesizer  [wavesynth]
fftak       ffmpeg    working   FFmpeg TAK  [tak]
```

**Comment by lfcnassif** [comment]
Just run `mplayer -ac help | grep lbc` on a dev node:
`libilbc     ffmpeg    working   FFmpeg libilbc  [libilbc]`

But trying to convert to wav running `mplayer -benchmark -vo null -vc null -srate 16000 -af format=s16le,channels=1 -ao pcm:fast:file=sample.wav sample.lbc`:
```
MPlayer 1.4 (Debian), built with gcc-11 (C) 2000-2019 MPlayer Team
do_connect: could not connect to socket
connect: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing sample.lbc.
libavformat version 58.76.100 (external)
libavformat file format detected.
[ilbc @ 0x7fd779aaa8e0]Estimating duration from bitrate, this may be inaccurate
[lavf] stream 0: audio (ilbc), -aid 0
Load subtitles in ./
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
libavcodec version 58.134.100 (external)
Cannot find codec 'libilbc' in libavcodec...
ADecoder init failed :(
ADecoder init failed :(
Cannot find codec for audio format 0x63626C69.
Audio: no sound
Video: no video


BENCHMARKs: VC:   0.000s VO:   0.000s A:   0.000s Sys:-1779.122s = -1779.122s

Exiting... (End of file)
```

**Comment by tc-wleite** [comment]
I see. That is odd. So the issue is something a bit more complicated.

**Review by lfcnassif — APPROVED** [review]
Thanks @tc-wleite! This seems good to me. I'm going to merge it and open another issue to investigate the lbc->wav conversion in our transcription cluster, although it seems an environment issue not related to this project.

**Pull request merged**
