### PR TITLE
Italian localization files

### PR DESCRIPTION
**Pull request by flates**
This is related to discussion #1091

I have translated into Italian:
- localization files ( iped-app/resources/localization/ )
- Help htm file ( /iped-app/resources/root/help/ )
- html report htm files ( iped-app/resources/root/htmlreport/ )

In the Help file I made some small changes to the words used as examples to make them more relevant to the Italian language. Hope that's not a problem.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @flates! I'll review and merge next week.

> Hope that's not a problem.

Not at all!

**Comment by flates** [comment]
> Hi @flates, I just added missing 'nudityScore' & 'nudityClass' properties to default english properties file. What would be a good italian translation to them?

A possible translation could be:
- nudityScore -> Percentuale di nudità
- nudityClass -> Livello di nudità

In my opinion the most appropriate translation for 'Score' is 'Percentuale' (percentage) even if it is usually a term that is used with values from 1 to 100.
Luckily I don't use this function for my job, but is there a reason why the values are 1-1000 and not 1-100?

**Comment by lfcnassif** [comment]
> but is there a reason why the values are 1-1000 and not 1-100?

I'm not sure since the algorithm was originally designed by @tc-wleite, but I think it is just an approach to allow more granular values using an integer. Maybe a float could be used for that, but I don't remember if the tool would support that when the feature was integrated at first (it comes from another tool developed by @tc-wleite).

**Comment by tc-wleite** [comment]
> I'm not sure since the algorithm was originally designed by @tc-wleite, but I think it is just an approach to allow more granular values using an integer. Maybe a float could be used for that, but I don't remember if the tool would support that when the feature was integrated at first (it comes from another tool developed by @tc-wleite).

Correct, 1-1000 was used because of granularity. Float could be used, but I just want to use an integer for simplicity.
Of course the raw output of the detection algorithm can be converted to float, scaled to [1, 100], or even to [0, 1].

**Comment by lfcnassif** [comment]
> In my opinion the most appropriate translation for 'Score' is 'Percentuale' (percentage) even if it is usually a term that is used with values from 1 to 100.

I'm not sure if you wrote what you've thought, but, as you noticed, actually it is a term that usually has values from 1-1000, so, could you think of a better translation than 'Percentuale'?

> Should this left "Report" string be left as is?

I also have this doubt about one report string.

After we finish those terms translation, I think this will be ready and I'll merge this, thank you!

**Comment by flates** [comment]
> I'm not sure if you wrote what you've thought, but, as you noticed, actually it is a term that usually has values from 1-1000, so, could you think of a better translation than 'Percentuale'?

Is correct. As a rule, 'percentuale' is used with values of 1-100 but in the Italian language it can also be used with values of 1-1000 or even 1-10000. 'Percentuale di nudità' is OK.
The literal translation would be 'punteggio' but it doesn't fit the context and sounds strange.


> Should this left "Report" string be left as is?

Yes, 'Report' is an English word commonly used in the Italian language.

**Comment by flates** [comment]
> > I'm not sure since the algorithm was originally designed by @tc-wleite, but I think it is just an approach to allow more granular values using an integer. Maybe a float could be used for that, but I don't remember if the tool would support that when the feature was integrated at first (it comes from another tool developed by @tc-wleite).
> 
> Correct, 1-1000 was used because of granularity. Float could be used, but I just want to use an integer for simplicity. Of course the raw output of the detection algorithm can be converted to float, scaled to [1, 100], or even to [0, 1].

Don't worry, I was just curious :)

**Comment by lfcnassif** [comment]
> > I'm not sure if you wrote what you've thought, but, as you noticed, actually it is a term that usually has values from 1-1000, so, could you think of a better translation than 'Percentuale'?
> 
> Is correct. As a rule, 'percentuale' is used with values of 1-100 but in the Italian language it can also be used with values of 1-1000 or even 1-10000. 'Percentuale di nudità' is OK. The literal translation would be 'punteggio' but it doesn't fit the context and sounds strange.
> 
> > Should this left "Report" string be left as is?
> 
> Yes, 'Report' is an English word commonly used in the Italian language.

Great! Thank you @flates for the explanation and sorry for my complete lack of knowledge about the italian language.

**Pull request merged**
