### PR TITLE
Added option to enable metadata filtering and clipboard helper button

### PR DESCRIPTION
**Pull request by leosol**
Addition of a JTextField to help search results in Meta Data Panel.
Addition of a JButton to copy results to clipboard

### CODE REVIEW

**Comment by lfcnassif** [comment]
Will test this possibly on Thrusday, thanks.

**Comment by lfcnassif** [comment]
Did a test with a 2.3M items case, performance is good, takes < 2s to filter 1M URLs and 11s to copy. Possibly will remove the "copy to clipboard" button to save UI space. Ctrl+A was optimized a lot in #451. Ctrl+C takes almost the same time to copy.

**Comment by leosol** [comment]
Great!! Thanks!

**Comment by leosol** [comment]
I guess it's okay to remove the button anyway. Leaves space for the listing or for anything else more important!

**Comment by lfcnassif** [comment]
just pushed f6fa7e2 to timeline branch (will keep this PR as small as possible to decrease the conflicts that already exists between the two branches), to limit Regex and NER values collected for highlight, collecting them all for a ctrl+a + ctrl+c makes no sense to me and it is heavy.

**Comment by lfcnassif** [comment]
I rebased this on timeline branch and force pushed the changes, sorry if it causes trouble.

**Comment by leosol** [comment]
That's okay! We can survive this.

Em qui., 22 de abr. de 2021 às 14:57, Luis Nassif ***@***.***>
escreveu:

**Comment by lfcnassif** [comment]
I kept the copy button, but changed the components and layout to save some ui space:
image

**Comment by leosol** [comment]
How nice! very good! Thank you!!

Em sex., 23 de abr. de 2021 às 00:57, Luis Nassif ***@***.***>
escreveu:

**Comment by lfcnassif** [comment]
Did some fixes/improvements and merged, thanks.

**Pull request merged**
