### PR TITLE
Fix jump quoted edited messages on whatsapp, add new message types, fix quoted status, quoted private and quoted catalog messages

### PR DESCRIPTION
**Pull request by gfd2020**
This PR fix Issue #2245 on Android New Databases.

Fix quoted status, privaty quote, catalog quote messages on Android New and IPhone.

Adds 2 new action types for Android:

*63 - Security code notifications are no longer available for this chat.

*142 - This group has over 256 members so now only admins can edit the groups settings.

*76 - You contacted this from find businesses

*69 - adds a subtype from table message_system_business_state

*Message type 15 and status equals 13 are deleted messages.

I haven't tested it on iPhone databases.
@wladimirleite , could you please help see this specific case on the iPhone?

@lfcnassif , I believe it would be good to do that batch of regression tests...

### CODE REVIEW

**Comment by gfd2020** [comment]
I think the edit timestamp information is not parsed on the iPhone, right?
In the iPhone databases that I have, I can't find any quote with editing...

**Comment by wladimirleite** [comment]
> I think the edit timestamp information is not parsed on the iPhone, right?

Right. I couldn't find any edit message in the iPhones I was working on when implementing that feature, neither I have an iPhone that I can use to test.

**Comment by gfd2020** [comment]
@wladimirleite and @lfcnassif , I found 2 new action_types (android) that are not mapped, can I add them to this same PR?

**Comment by gfd2020** [comment]
I also implemented quoted status identification. I'm also seeing if I can implement quoted in particular in groups ...

I can´t find any quoted edited messagens on iphone to test 😥

**Comment by gfd2020** [comment]
Hi @lfcnassif and @wladimirleite .

I didn't know there were other types of citations (status and private). So these new types were implemented ( Android and Iphone):

"Quoted Status"
image

"Message quoted privately"
image

If user clicks on the quoted message:
image

"Message quoted privately not found"
image

**Comment by lfcnassif** [comment]
Thank you very much @gfd2020 for this PR!

**Comment by lfcnassif** [comment]
A small regression test with 12 databases passed fine, running a larger one with hundreds of DBs...

**Comment by gfd2020** [comment]
Hi @lfcnassif .
I made a small commit to add translations ( french, italian and deutch) and to optimize a search. I added more information that can be captured in the iPhone case. I believe that this modification does not affect the database connection.

**Comment by gfd2020** [comment]
Hi @lfcnassif .

I just finish it. I was able to do comparison tests with a real database and a smartphone in the case of Android. 
In the case of the iPhone, I only have the database, I don't have the device. It would be good if someone did a comparison test on the iPhone.

The logic behind implementing quotes can be quite confusing, so I left several comments in the code.

I don't know if the new messages in English have correct spelling. If anyone can review it too...

**Comment by wladimirleite** [comment]
I am starting to review this PR.

@lfcnassif and @gfd2020, I had this doubt in the past: as the branch used it not in `sepinf-inc` repository, how is the correct (and easy) way to review this (and make changes if necessary)?

The solution I used before (following a @lfcnassif's suggestion) was to use the "Fetch GitHub Pull Request..." option. 
It was pretty simple, and worked fine. However, I was not able to make changes, which can be quite inconvenient...

**Comment by gfd2020** [comment]
> The solution I used before (following a @lfcnassif's suggestion) was to use the "Fetch GitHub Pull Request..." option. It was pretty simple, and worked fine. However, I was not able to make changes, which can be quite inconvenient...

I don't know what you have to do to make changes. I thought the option marked below would be enough

image

**Comment by gfd2020** [comment]
@wladimirleite , I remember you had problems in another PR. I rescued the conversation here, if I can help...

image

**Comment by lfcnassif** [comment]
Hi @wladimirleite!

> The solution I used before (following a @lfcnassif's suggestion) was to use the "Fetch GitHub Pull Request..." option.
It was pretty simple, and worked fine.

Good!

> However, I was not able to make changes, which can be quite inconvenient...

From commit history, right click on last commit of your local branch fetched above -> "PushCommit..." -> New Remote:

image

image

Then push to @gfd2020's repo using the branch name there (got from the top of this PR page):

image

**Comment by wladimirleite** [comment]
Thanks @lfcnassif!
I will try to follow these steps tomorrow.

**Comment by lfcnassif** [comment]
PS: Source local branch is "master" in sample images above, but it should be your local fetched pr-2246 branch.

**Comment by wladimirleite** [comment]
I pushed a code formatting commit successfullly (thanks again @lfcnassif and @gfd2020 for helping me with this branch setup part).

About the PR review itself, I already finished checking the code changes.
I running now a large comparison test with hundreds of WhatsApp databases, to check for regressions and to find samples of the types of messages which support was added.

**Review by wladimirleite — APPROVED** [review]

**Comment by lfcnassif** [comment]
Thank you @gfd2020 for this great work and @wladimirleite for reviewing!

**Pull request merged**
