### PR TITLE
Timeline interaction fixes

### PR DESCRIPTION
**Pull request by patrickdalla**
Solves #1478 #1477 #1470 and #1471.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thanks @patrickdalla, all reported issues were fixed. But I found another one:
- if a filtering range is defined in the chart and being applied (tab title with red color), if you press shift and selects an overlapping region from right to left, the range is cleared in the char, but the filter remains active, but the user don't know what is the filter definition anymore because it was cleared. I think dragging the mouse from right to left with shift pressed shouldn't clear overlapping filters.

**Review by lfcnassif — CHANGES_REQUESTED** [review]
Thanks @patrickdalla, all reported issues were fixed. But I found another one:

- if a filtering range is defined in the chart and being applied (tab title with red color), if you press shift and selects an overlapping region from right to left, the range is cleared in the chart, but the filter remains active, but the user doesn't know what is the filter definition anymore because it was cleared. I think dragging the mouse from right to left with shift pressed shouldn't clear overlapping filters.

**Comment by lfcnassif** [comment]
Example:

https://user-images.githubusercontent.com/7276994/212911094-387ce80a-94ec-4e92-a713-304f7ac37b0a.mp4

**Comment by lfcnassif** [comment]
I'll try to take a look on the last issue I've reported, please let me know if you are already on it to avoid duplicate efforts.

**Comment by patrickdalla** [comment]
No, i am not. You can take a look.

Il giorno mar 17 gen 2023 alle ore 12:19 Luis Filipe Nassif <
***@***.***> ha scritto:

**Review by lfcnassif — APPROVED** [review]

**Pull request merged**
