### PR TITLE
Search for hardware wallets

### PR DESCRIPTION
**Pull request by mobab-th**
Possible Solution for Issue #1371 (Vendors and Products Identifiers for Hardware Wallets)

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @mobab-th! I'll try to review this next week.

**Comment by lfcnassif** [comment]
Sorry @mobab-th for the long delay, I'll start reviewing this...

**Comment by lfcnassif** [comment]
Hi @mobab-th, here are new results after my changes:
image

**Review by lfcnassif — APPROVED** [review]
Thanks for this PR!

**Comment by tc-wleite** [comment]
One minor detail that I noticed related to this PR: 
It seems that there isn't a simple way (a parameter in IPEDConfig.txt) to disable this task, right?
I am processing a lot of E01 images using the "fastmode" profile and I noticed that this task is enabled.
It is not critical, as it processes just a few files and the spent time is minimal.

Maybe it should be better to keep a similar behavior as most other tasks, allowing to be disabled in IPEDConfig.txt, and disable it in "fastmode" profile default configuration, unless the current behavior is intentional.

I know I can disable it by removing (or commenting it out) in TaskInstaller.xml, but that is not as straightforward as the standard way used by other tasks.

**Comment by lfcnassif** [comment]
Agreed.

**Pull request merged**
