### PR TITLE
#1282 Extract telegram deleted groups;

### LINKED ISSUE #1282: Extract telegram deleted groups
A colleague from SETEC-AP found some groups that are presented in the chat tables, but are not presented in the dialogs tables or in the messages table. This groups are not being listed, but its name can contain valuable information.

### PR DESCRIPTION
**Pull request by hauck-jvsh**
Extract telegram deleted groups and fix a null pointer when the searcher is null.
Closes #1282

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh!

**Comment by lfcnassif** [comment]
Hi @hauck-jvsh, is it possible to flag deleted groups as "deleted"?

**Comment by hauck-jvsh** [comment]
> Hi @hauck-jvsh, is it possible to flag deleted groups as "deleted"?

I think that it is easy. Is there a metadata for this?

**Comment by lfcnassif** [comment]
> I think that it is easy. Is there a metadata for this?

Yes: ExtraProperties.DELETED

**Comment by hauck-jvsh** [comment]
When I was implementing this I see that there is a property` ExtraProperties.CHAT_RECOVERED`. So I use it to mark the recovered chats, and I also print a message inside the recovered chats. I do not translate the terms to Spanish or Italian.

**Review by lfcnassif — APPROVED** [review]

**Pull request merged**
