### PR TITLE
VideoThumbOriginalDimension and ImageSimilarity on videoThumbs

### PR DESCRIPTION
**Pull request by arisjr**
Changed the VideoThumbOriginalDimension ability and ImageSimilarity on videoThumbs ability. They don't depend on each other to work.

### CODE REVIEW

**Comment by arisjr** [comment]
Something to look better is iped-engine/src/main/java/dpf/sp/gpinf/indexer/search/ImageSimilarityScorer.java OrganizeTopResults. I only put to group the first vector of the multiple vectors of the videothumbnail file. It's complicated to group several vectors that can be very different from each other, so it's something that remains open. Maybe let the videos being ordered by score?

**Comment by lfcnassif** [comment]
Thank you @arisjr for this PR.

> I only put to group the first vector of the multiple vectors of the videothumbnail file

Maybe it is better to group by the frames nearest vector to the reference image.

And if user chooses a video to search similar images/videos for, is first frame vector chosen? This is what is currently done for faces (first face is taken from a multiple faces image), but this is too naive. Maybe user could choose the frame of interest.

**Comment by lfcnassif** [comment]
> They don't depend on each other to work.

So, ideally they could be sent in separate PRs, so a buggy or incomplete one wouldn't delay the merge of the other feature.

**Comment by lfcnassif** [comment]
@tc-wleite, not sure how is your current backlog, but since this changes features originally implemented by you, do you would like and do you think you will have available time to review this in the near future?

**Comment by lfcnassif** [comment]
> Maybe let the videos being ordered by score?

What would happen if images and videos are returned?

**Comment by tc-wleite** [comment]
> @tc-wleite, not sure how is your current backlog, but since this changes features originally implemented by you, do you would like and do you think you will have available time to review this in the near future?

Hi @arisjr and @lfcnassif! Sorry for the slow response. I am returning from vacation today, and there were a lot of things that I had to deal with. 
@lfcnassif, I won't be able to review this PR this week. Hopefully in the next week I can do it. Feel free to review if you want to finish this sooner. I can always run additional tests later, if you decide to review it.

**Comment by lfcnassif** [comment]
> @lfcnassif, I won't be able to review this PR this week. Hopefully in the next week I can do it.

Don't worry and don't hurry! By "near future" I mean next weekS... This is not in my priority queue (sorry @arisjr), I already have other things scheduled for 4.0.0 much before, although this PR changes the way image similarity vectors are indexed and should be backwards imcompatible, so 4.0.0 may be a good fit...

Welcome back!

**Comment by lfcnassif** [comment]
Another totally different approach, I said to @arisjr privatelly, would be to extract video frames as video subitems, that would be backwards compatible, but I think I prefer this PR approach.

**Comment by lfcnassif** [comment]
> is first frame vector always chosen?

I just saw the answer to this is yes. Asking user to choose the reference video frame to be searched for may be easier, but other approach would be to search for all of them, shouldn't be too hard, but not sure how to present the results...

**Comment by arisjr** [comment]
One thing I didn't was to get only the best score for a video. I think it was missing this part of the code on the score part. 

On the score part, all the frames are checked. On the organizeTopResults only the first frame. 

I'll close this PR and add them as a separated PR. And will do a best score approach checking all frames on Score and Organize procedures.

I think it would be better.

**Pull request closed without merging**
