### PR TITLE
Issue 428 - Add WhatsApp sender/recipient info to chat preview and metadata

### PR DESCRIPTION
**Pull request by leosol**
Made a small change in method WhatsAppParser.getBestItem. Before, if there were only one account xml file (com.whatsapp_preferences.xml) this would be taken for every other chats. Suppose that for any reason, you can find the whole whatsapp structure but with different name (maybe a com.modwhatsapp_preferences.xml could be found). In this case, chats in this structure would be "sent" by an incorrect account.

Besides that, just had to pass on WAAccount from the parser to the ReportGenerator.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Great, thanks for the PR and the fix! Will review soon.

**Comment by lfcnassif** [comment]
Merged, thank you. Fixed a small regression in name + number formatting. Please use 4 spaces indentations in next PRs, thanks.

**Comment by leosol** [comment]
Nice! Is there any code formatter somewhere?

Em qua., 28 de abr. de 2021 às 19:54, Luis Nassif ***@***.***>
escreveu:

**Comment by lfcnassif** [comment]
> Nice! Is there any code formatter somewhere? Em qua., 28 de abr. de 2021 às 19:54, Luis Nassif ***@***.***> escreveu:

Yes, take a look here: https://github.com/sepinf-inc/IPED/wiki/Contributing

**Pull request merged**
