### PR TITLE
Whisperx Optimization

### LINKED ISSUE #1539: Try to optimize Wav2Vec2 transcription inference
General recommendations:
https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html

This one was found by @hauck-jvsh:
https://developer.nvidia.com/blog/accelerating-inference-up-to-6x-faster-in-pytorch-with-torch-tensorrt/

### PR DESCRIPTION
**Pull request by hauck-jvsh**
Closes  #1539

### CODE REVIEW

**Comment by hauck-jvsh** [comment]
This must be used with our fork of the whisperx, as I had to change the library to accept more than one file and to do not use ffmpeg, We already convert the to wav before sending it to be transcribed.

**Comment by lfcnassif** [comment]
Thank you very very much @hauck-jvsh! I'll run a basic accuracy test soon, to be sure it wasn't affected by the changes. Have you pushed the changes to WhisperX to some branch in our fork?

To let others know, with the batch inference approach suggested on #1539 (processing up to 16 audios at the same time) and avoiding a duplicated ffmpeg run into the library, @hauck-jvsh was able to speed up WhisperX inference on a batch of audios with different durations up to 5x-6x!

**Comment by hauck-jvsh** [comment]
Yes I have pushed the changes to a branch called multi-audio

**Comment by hauck-jvsh** [comment]
I forgot to run the tests with all the changes disabled to compare. I ran tests only against the wav2vec model and I manage to the get whisperX only 1.6 times slower than the wav2vec.

**Comment by lfcnassif** [comment]
> I forgot to run the tests with all the changes disabled to compare. I ran tests only against the wav2vec model and I manage to the get whisperX only 1.6 times slower than the wav2vec.

Default WhisperX is about 9x times slower than Wav2Vec2 large model on my test data sets, so 9 / 1.6 = 5.6x speed up :-)

I've just computed the WER numbers for 2 data sets:

WER | TedX (3.8h) | Real data set (1h)
-- | -- | --
WhisperX-LargeV3 | 0.134 | 0.193
ThisPR-LargeV3 | 0.134 | 0.187

So accuracy seems fine!

**Comment by hauck-jvsh** [comment]
The last commit solves a bug when a very huge audio, with 11 hours was sent to the cluster and it causes an out of memory in the node.

**Review by lfcnassif — APPROVED** [review]
Just did a basic local test with both whisperx and faster_whisper, both worked. Thank you @hauck-jvsh!

**Pull request merged**
