### PR TITLE
Custom MimeTypes - change name based detection rules

### LINKED ISSUE #457: Minor optimization - detectors executing twice
I found out that each detector in the CompositeDetector is running two times in a row for every item.

### PR DESCRIPTION
**Pull request by mbichara**
Hey! This is related to discussion #401.
Still a work in progress, just some starting idea (not intended for merging).

- Moves all the detectors declaration to ParserConfig.xml. By doing explicit detector declaration it fixes #457.
- Creates a custom MimeTypes detector, that uses most of the functionality from the original.

Name based detection is changed to only be used in three situations:
1. If the mime from name hint has no magic signature associated with it. 
2. If there was a signature match already(try to specialize it).
3. If the mime name hint is defined to always run name detection (TO DO).

I did just some minor testing with some corrupted files with JPEG and PDF extensions. Those are then not categorized as JPEG or PDF if the magic signature does't match. Still needs a lot of testing.

About adding a set of mimes to always use name based detection, I would like some opinion about the best way to do it.
Some ideas..
- Create a file with a list of mimes that should run name detection
- Add some mime parameter in tika-mimetypes.xml and CustomSignatures.xml (not sure if it is straightforward, maybe needs to modify MimeType class)
- Use the mime comment/description in tika-mimetypes.xml and CustomSignatures.xml to append some label (I think it could be easy, but it feels like a hack)

Feel free to make any changes.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thanks @mbichara! About the mimes to always use name detection rule, I think your second ideia is better, but not sure if it is possible without changing Tika. If not, first option is good to me.

**Comment by mbichara** [comment]
Alright! I will do that and let you know how it goes

**Comment by lfcnassif** [comment]
Just had an ideia, maybe declaring a new element/section in CustomMimeTypes.xml file to list the mimes to do name detection? Maybe Tika will not complain about an unknown element...

**Comment by mbichara** [comment]
Great idea, I think it should work. I'll try that.

**Comment by lfcnassif** [comment]
I just remembered an important thing: in fastmode profile, file type detection is done using just names for all mimetypes, it should keep working.

**Comment by mbichara** [comment]
> 
> 
> edit: Using a different ParserConfig.xml (with Tika MimeTypes detector) for fastmode profile should work.

Nice, I think that will do.

I was able to create the element list in CustomSignatures.xml and read it ok without breaking Tika.
For now I just added to the list the RFC822 mimes that you pointed out.

Then I think we need to run a lot of tests to make sure the additional rules are ok and it does't break anything else. 

I can update the other profiles after.

**Comment by lfcnassif** [comment]
@mbichara sorry for not reviewing this yet, I'm prioritizing PRs ready for review and some structural changes for 4.0.0.

**Comment by lfcnassif** [comment]
I'm closing this due to lack of activity for more than 1 year and lack of exhaustive tests. We must test this with hundreds of thousands/millions of files of several different file types to check for regressions/misdetections. Signature detection is a very sensitive module because running other modules depends on the detected signature.

After we make those exhaustive regression tests, we can reopen this or a similar PR.

Thanks @mbichara.

**Pull request closed without merging**
