### PR TITLE
#493 support new Media Classification properties from Cellebrite UFDR reports

### LINKED ISSUE #493: Support new Media Classification properties from Cellebrite UFDR reports
It would be useful if IPED could identify Media Classification properties from Cellebrite UFDR reports

### PR DESCRIPTION
**Pull request by aberenguel**
Closes #493.

### CODE REVIEW

**Comment by aberenguel** [comment]
I think the names of metadata fields should be changed. They are a little bit long. In a case with all types of classification, I got these:

```
ufed:mediaResult:category:BarcodesQRCodes
ufed:mediaResult:category:Beach
ufed:mediaResult:category:Camera
ufed:mediaResult:category:Cars
ufed:mediaResult:category:Cigarettes
ufed:mediaResult:category:Credit_Cards
ufed:mediaResult:category:Documents
ufed:mediaResult:category:Drugs
ufed:mediaResult:category:Face
ufed:mediaResult:category:Flags
ufed:mediaResult:category:Food
ufed:mediaResult:category:Gatherings
ufed:mediaResult:category:Hand_Holding_Objects
ufed:mediaResult:category:Handwritten
ufed:mediaResult:category:Hotel_Rooms
ufed:mediaResult:category:Invoices
ufed:mediaResult:category:Jewelry
ufed:mediaResult:category:Licenseplates
ufed:mediaResult:category:Maps
ufed:mediaResult:category:Money
ufed:mediaResult:category:Motorcycles
ufed:mediaResult:category:Nudity
ufed:mediaResult:category:Photo_Id
ufed:mediaResult:category:Pool
ufed:mediaResult:category:Restaurant
ufed:mediaResult:category:Screenshots
ufed:mediaResult:category:Smartphones
ufed:mediaResult:category:SuspectedCSA
ufed:mediaResult:category:Tattoos
ufed:mediaResult:category:Upskirt
ufed:mediaResult:category:Vehicle_Dashboards
ufed:mediaResult:category:Weapons
```

**Comment by lfcnassif** [comment]
Or maybe `ufed:mediaClass:XXX`?

**Comment by lfcnassif** [comment]
First, thanks @aberenguel for this PR! Does PA fill a score value for all categories for each image?

**Comment by aberenguel** [comment]
> First, thanks @aberenguel for this PR! Does PA fill a score value for all categories for each image?

Not for all categories, just only for the categories the user choose. The user also can choose "Images only", "Videos only" or "Images and Videos". I think the PA just don't add when the score is zero.

**Comment by aberenguel** [comment]
The json file has both terms: "classifications" and "categories"
Example:
```json
{"FileId":"ffaa0cd3-9478-47ce-9a97-f0fa6f599e93","Classifications":[],"Categories":[{"Value":"Upskirt","Score":84.829796}]}{"FileId":"ffcaeba2-6399-4d84-a756-b9833fe43f26","Classifications":[],"Categories":[{"Value":"Face","Score":99.979805}]}
```
The "Classifications" is always empty. I added some tags for images in PA, but nothing changed. I don't know what "Classifications" is intended for.

**Comment by lfcnassif** [comment]
> ```json
> ```json
> {"FileId":"ffaa0cd3-9478-47ce-9a97-f0fa6f599e93","Classifications":[],"Categories":[{"Value":"Upskirt","Score":84.829796}]}
> {"FileId":"ffcaeba2-6399-4d84-a756-b9833fe43f26","Classifications":[],"Categories":[{"Value":"Face","Score":99.979805}]}
> ```
So seems just a few categories per image receive a score value, right? Maybe the most likely ones? Are low score values also returned?

I was thinking about creating an additional string metadata like `ufed:mediaClasses` containing the categories names with the highest scores for each image, keeping current keys, so filtering will be easier for users not used to numeric range queries. Not sure if a score threshold X should be used or picking the top Y categories with highest scores...

**Comment by aberenguel** [comment]
> So seems just a few categories per image receive a score value, right? Maybe the most likely ones? Are low score values also returned?

I checked all categories in a example case and saw that the most categories have starting in ~50. Just a few categories had scores starting in ~40. The category "SuspectedCSA" was the odd one: its score has values between 0.9 and 99.9.

Some examples of files classified in many categories:
```json
{"FileId":"fe44f40d-ddb2-4d0c-a9ba-e13ffe2df928","Classifications":[],"Categories":[{"Value":"Documents","Score":89.23717},{"Value":"Upskirt","Score":80.498665},{"Value":"Hand_Holding_Objects","Score":77.77763},{"Value":"SuspectedCSA","Score":76.03493},{"Value":"Nudity","Score":74.03932},{"Value":"Screenshots","Score":52.330223},{"Value":"Smartphones","Score":52.019016}]}
{"FileId":"ad138cc5-027f-46eb-8824-8f7698289c9d","Classifications":[],"Categories":[{"Value":"Nudity","Score":76.209656},{"Value":"Smartphones","Score":67.06892},{"Value":"Jewelry","Score":64.700226},{"Value":"Hand_Holding_Objects","Score":63.480453},{"Value":"Face","Score":59.012554},{"Value":"Documents","Score":55.35909},{"Value":"SuspectedCSA","Score":37.326992}]}
{"FileId":"9e015b13-c498-4bd3-a8c3-49aab52cd0ce","Classifications":[],"Categories":[{"Value":"Upskirt","Score":94.55889},{"Value":"Nudity","Score":80.896126},{"Value":"Tattoos","Score":67.84504},{"Value":"Hand_Holding_Objects","Score":55.09293},{"Value":"Vehicle_Dashboards","Score":52.921158},{"Value":"SuspectedCSA","Score":51.122326}]}
{"FileId":"5d1be971-3ad4-4df2-b169-8438de9748f6","Classifications":[],"Categories":[{"Value":"Face","Score":99.04964},{"Value":"Nudity","Score":98.060234},{"Value":"Jewelry","Score":83.834526},{"Value":"Hand_Holding_Objects","Score":80.31617},{"Value":"Cigarettes","Score":57.893257},{"Value":"SuspectedCSA","Score":7.4421296}]}
```

> 
> I was thinking about creating an additional string metadata like `ufed:mediaClasses` containing the categories names with the highest scores for each image, keeping current keys, so filtering will be easier for users not used to numeric range queries. Not sure if a score threshold X should be used or picking the top Y categories with highest scores...

I think this string metadata it would be useful for filtering. It can also be filtering in metadata tab, selecting all lines.

image

**Comment by lfcnassif** [comment]
> Not sure if a score threshold X should be used or picking the top Y categories with highest scores...

What approach do you guys think fits better? This should need some experimentation with results...

> Or maybe `ufed:mediaClass:XXX`?

ufed:classScore:XXX is another option, since values are floats, may be more intuitive.

**Comment by hauck-jvsh** [comment]
I like the ufed:classScore:XXX, the user can filter using ufed:classScore:* to find all elements witch has a score for the class or filter using a range query.

**Comment by aberenguel** [comment]
Or `ufed:mediaClassScore:XXX`. I prefer to add terms similar to PA, but the string starts becoming long

**Comment by lfcnassif** [comment]
> I was thinking about creating an additional string metadata like `ufed:mediaClasses` containing the categories names with the highest scores for each image, keeping current keys, so filtering will be easier for users not used to numeric range queries. Not sure if a score threshold X should be used or picking the top Y categories with highest scores...

Since it is possible to do range queries easily using the metadata filter tab like @aberenguel has shown and since the definition of the threshold would need some experimentation (is 50.0 a good cut value?), I'll leave this suggestion as a future improvement. I'm waiting some ufdr sample to test this...

**Comment by lfcnassif** [comment]
> The "Classifications" is always empty. I added some tags for images in PA, but nothing changed. I don't know what "Classifications" is intended for.

The sample UFDR I got has this property filled up:
```
{"FileId":"fb7ceb84-3b7d-472e-8dbc-c818b5fa8c29","Classifications":[{"FrameOffsetMilliseconds":0,"Categories":[]},{"FrameOffsetMilliseconds":2000,"Categories":[{"Value":"Documents","Score":98.93832},{"Value":"Face","Score":99.8473}]},{"FrameOffsetMilliseconds":1000,"Categories":[{"Value":"Documents","Score":97.739044}]},{"FrameOffsetMilliseconds":3000,"Categories":[{"Value":"Documents","Score":99.55653},{"Value":"Face","Score":99.85789}]}],"Categories":[{"Value":"Face","Score":99.85789},{"Value":"Documents","Score":99.55653}]}
```
Seems it is related to Videos. @aberenguel have you checked this feature for videos in PA?

Should we store all those values in a multivalued metadata? Just the top score for each class? Or do a similar approach like @tc-wleite did for videos nudityScore, combining scores of multiple frames: https://github.com/sepinf-inc/IPED/blob/master/iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/DIETask.java#L283 ?

**Comment by aberenguel** [comment]
Changes in IPED
image
image

**Comment by aberenguel** [comment]
> > The "Classifications" is always empty. I added some tags for images in PA, but nothing changed. I don't know what "Classifications" is intended for.
> 
> The sample UFDR I got has this property filled up:
> 
> ```
> {"FileId":"fb7ceb84-3b7d-472e-8dbc-c818b5fa8c29","Classifications":[{"FrameOffsetMilliseconds":0,"Categories":[]},{"FrameOffsetMilliseconds":2000,"Categories":[{"Value":"Documents","Score":98.93832},{"Value":"Face","Score":99.8473}]},{"FrameOffsetMilliseconds":1000,"Categories":[{"Value":"Documents","Score":97.739044}]},{"FrameOffsetMilliseconds":3000,"Categories":[{"Value":"Documents","Score":99.55653},{"Value":"Face","Score":99.85789}]}],"Categories":[{"Value":"Face","Score":99.85789},{"Value":"Documents","Score":99.55653}]}
> ```
> 
> Seems it is related to Videos. @aberenguel have you checked this feature for videos in PA?
> 
> Should we store all those values in a multivalued metadata? Just the top score for each class? Or do a similar approach like @tc-wleite did for videos nudityScore, combining scores of multiple frames: https://github.com/sepinf-inc/IPED/blob/master/iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/DIETask.java#L283 ?

The sample case I used had few videos (none of them was caught by PA). 
Good to know how it works. It seems PA process equally spaced frames in videos (spaced by 1000ms). I don't think it is a good approach, but it is what we have.

**Comment by aberenguel** [comment]
> @aberenguel I was making changes to this PR, but just saw your [8439c41](https://github.com/sepinf-inc/IPED/commit/8439c411e20a3dd2eb8a7e92cb5bbe72b88d5d09) commit, thanks. I'll switch to another PR. When you finish making changes, please let me know.

Disconsidering the video frames classification (I think we need further discussions), I think I don't have anything else to commit.

> PS: Have you checked if the 50% score is a reasonable threshold for a representative amount of images?
The most of images are scored with values greater than 50.0. The only exception is the "SuspectedCSA" category which has reasonable images scored less than 50.0.

Examples:
image
image
image

**Comment by lfcnassif** [comment]
> Disconsidering the video frames classification (I think we need further discussions), I think I don't have anything else to commit.

Any opinion about this @tc-wleite?

> The most of images are scored with values greater than 50.0. The only exception is the "SuspectedCSA" category which has reasonable images scored less than 50.0.

Great, maybe this is the threshold used by PA, and as "SuspectedCSA" is a very sensible class, they possibly decided to keep any related score.

**Comment by tc-wleite** [comment]
> > Disconsidering the video frames classification (I think we need further discussions), I think I don't have anything else to commit.
> 
> Any opinion about this @tc-wleite?

Well, I think that taking the top score or combining the scores with a simple heuristic (could be similar to the one @lfcnassif  mentioned, implemented  for videos nudityScore) are better alternatives than storing all raw values.

The heuristic implementation is pretty straightforward, and basically combines frames' scores using a weighted average, using higher weights for higher scores. 
The final result is similar to taking the top score, but in general a bit better.

**Comment by lfcnassif** [comment]
> combining the scores with a simple heuristic

+1 for this. I think one video with many frames with high SuspectedCSA scores should have a higher overall score than other video with a single frame with high SuspectedCSA score. Since IPED, currently, won't show the exact frames evaluated by PA (and eventually highlighting high score frames), I think a single overall score makes sense, being consistent to what we already have for videos nudityScore.

**Comment by lfcnassif** [comment]
I was busy early. Just tested current code, it is already working for videos. I checked some samples and seems PA simply chooses the top scores for each category through all the frames (from the `Classifications `element) and put them at the end in the `Category `element. Should we leave this as is keeping PA decision for the final video scores or implement the combined frames scores?

**Comment by lfcnassif** [comment]
> PS: I can implement this if decided.

I decided to implement this. Just writing here to avoid duplicate efforts.

**Comment by lfcnassif** [comment]
After implementing the score combination, I just realized PA stores the category score for some frame just if it is >= 50. This is bad for the combination formula, since we don't have the scores for all frames for each category. I thought about setting the score zero, 49.999 or 25.0 for missing frames scores, but this is far from the ideal... Any ideas? I'll do some tests, but possibly I'll rollback my local implementation and leave it as is...

**Comment by lfcnassif** [comment]
> Any ideas?

I'll try adding 49.99 for missing frames scores, so the final score won't be penalized that much and won't be too far from the top score used by PA (this assumes missing frames scores are always < 50)

**Comment by tc-wleite** [comment]
> Any ideas?

Not sure. Your idea seems reasonable. Usually only tests would tell.

**Comment by lfcnassif** [comment]
Using 49.99 for missing frames scores gave good results in my opinion, specially when there is a single or a few frames with a high score and other frames totally unrelated. Maybe using 25 for missing frames scores would improve a bit, but video scores would start to be below 50. The threshold would need to be adjusted. But this would make the score range for images to be different from videos, so I'll keep the 49.99 value, resulting in a less aggressive score adjustment for videos for now.

**Comment by lfcnassif** [comment]
Thanks @aberenguel for this PR, @tc-wleite and @hauck-jvsh for your comments!

**Pull request merged**
