### PR TITLE
Usn jrnl parser

### PR DESCRIPTION
**Pull request by hauck-jvsh**
Implements a parse for the UsnJnrl File

### CODE REVIEW

**Review by lfcnassif — CHANGES_REQUESTED** [review]
First review, I didn't compile or tested yet:

`<mime-type type="USNJOURNAL/$J">`
Could you change all new mimes to application/x-usnjournal-?????? pattern?

The name of usn journal inside iped is $UsnJrnl:$J I think current definition will not work with forensic images.

A mimetype should not sub-class more than 1 parent.

In `readInt16() readInt32 etc` methods:
Seems bigEndian logic is inverted?

Not sure if readInt32 is expected to return signed or unsigned integers. If unsigned, change return and var i to long.

Util.readString() method:
check num bytes returned by in.read(b, 0, len) and continue reading until len.
This applies to all read() and skip() methods from other classes as well. You can use IOUtils.readFully() and IOUtils.skipFully() methods from already used commons io lib.

I think all methods of Util class shoud throw IOException instead of catching internally.

**Review by lfcnassif — CHANGES_REQUESTED** [review]
SimpleDateFormat is not thread safe, be careful, it cannot be static.

**Comment by hauck-jvsh** [comment]
The bigEndian logic was indeed inverted,
I changed the mime types names to match the suggested pattern.
The readInt methods should return positive values, but java does not have unsigned int, how can I return positive long values?

**Comment by lfcnassif** [comment]
Just readInt32(and internal var i) can be changed to return long to support unsigned int max value.

readInt64() is ok, there is no workaround, and very little chance to return huge long values greater than signed long max value.

**Comment by lfcnassif** [comment]
Semicolons could occur in NTFS file names, I suggest surrouding CSV column data with double quotes.

**Comment by lfcnassif** [comment]
Merged, thank you @hauck-jvsh !

**Pull request merged**
