### PR TITLE
'#1652 Replace of JFreeChart TimePeriod objects from timeline index

### PR DESCRIPTION
**Pull request by patrickdalla**
Creation of index with Date objects. Also parses the date string that is stored in date fields is done simultaneously with date normalization with respective time period being counted.

### CODE REVIEW

**Comment by patrickdalla** [comment]
In a test case with 3 million timestamped items, some timeperiod index creation times reduced to 1/3 of original time. Also some memory was saved (it was difficult to measure as garbage collection scheme hides precise info).

Logged times before PR:
2023-04-19 06:50:10	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Day]]: 11923ms
2023-04-19 06:50:31	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Year]]: 13887ms
2023-04-19 06:50:32	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Quarter]]: 14398ms
2023-04-19 06:50:32	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Month]]: 14573ms
2023-04-19 06:50:32	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Week]]: 14797ms
2023-04-19 06:50:42	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Hour]]: 24242ms
2023-04-19 06:50:48	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Second]]: 30933ms
2023-04-19 06:50:50	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class iped.jfextensions.model.Minute]]: 32340ms

Logged times after PR:
2023-04-19 06:52:45	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Day]]: 7600ms
2023-04-19 06:52:58	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Month]]: 8560ms
2023-04-19 06:52:58	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Quarter]]: 8573ms
2023-04-19 06:52:58	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Year]]: 8615ms
2023-04-19 06:52:59	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Hour]]: 9335ms
2023-04-19 06:52:59	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Week]]: 9719ms
2023-04-19 06:52:59	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class iped.jfextensions.model.Minute]]: 9830ms
2023-04-19 06:53:00	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Time to build time cache of [[class org.jfree.data.time.Second]]: 10120ms

**Comment by lfcnassif** [comment]
Thank you @patrickdalla!

**Comment by patrickdalla** [comment]
Maybe this pull request can be done together with other commits made in TimelineFlushedIndexCreation, when it is finished. It is almost finished. I just asked in #1598 for opinions about the best rule when to pause index and flush intermediary results.

**Comment by patrickdalla** [comment]
I am closing it as #1666 contains it.

**Pull request closed without merging**
