### PR TITLE
'#1942 send error 2 client if caused by startServer(), shutdown server process

### LINKED ISSUE #1942: Audios not retried and skipped if specific errors happen in remote transcription service
An user reported the transcription service was not working last week and sent a processing log with following errors:
```
2023-10-17 09:00:45	[WARN]	[task.transcript.RemoteWav2Vec2TranscriptTask]			Fail to transcribe on server: XXX  audio: XXX.opus error: Exception while transcribing: java.lang.RuntimeException: iped.exception.IPEDException: 'huggingsound' python lib not loaded correctly. Have you installed it?.
2023-10-17 09:01:13	[WARN]	[task.transcript.RemoteWav2Vec2TranscriptTask]			Fail to transcribe on server: XXX  audio: XXX.opus error: Exception while transcribing: java.lang.RuntimeException: iped.exception.IPEDException: 'huggingsound' python lib not loaded correctly. Have you installed it?.
2023-10-17 09:01:13	[WARN]	[task.transcript.RemoteWav2Vec2TranscriptTask]			Fail to transcribe on server: XXX  audio: XXX.opus error: Exception while transcribing: java.lang.RuntimeException: iped.exception.IPEDException: Error loading '/home/transcript/.cache/huggingface/hub/models--jonatasgrosman--wav2vec2-xls-r-1b-portuguese/snapshots/8926743abe7e95bb81b64305cb3c5fa85173f6b0' transcription model..
2023-10-17 09:01:17	[WARN]	[task.transcript.RemoteWav2Vec2TranscriptTask]			Fail to transcribe on server: XXX  audio: XXX.opus error: Exception while transcribing: java.lang.RuntimeException: iped.exception.IPEDException: Error loading '/home/transcript/.cache/huggingface/hub/models--jonatasgrosman--wav2vec2-xls-r-1b-portuguese/snapshots/8926743abe7e95bb81b64305cb3c5fa85173f6b0' transcription model..
2023-10-17 09:01:18	[WARN]	[task.transcript.RemoteWav2Vec2TranscriptTask]			Fail to transcribe on server: XXX  audio: XXX.opus error: Exception while transcribing: java.lang.RuntimeException: iped.exception.IPEDException: Error loading '/home/transcript/.cache/huggingface/hub/models--jonatasgrosman--wav2vec2-xls-r-1b-portuguese/snapshots/8926743abe7e95bb81b64305cb3c5fa85173f6b0' transcription model..
2023-10-17 09:01:18	[WARN]	[task.transcript.RemoteWav2Vec2TranscriptTask]			Fail to transcribe on server: XXX  audio: XXX.opus error: Exception while transcribing: java.lang.RuntimeException: iped.exception.IPEDException: Error loading '/home/transcript/.cache/huggingface/hub/models--jonatasgrosman--wav2vec2-xls-r-1b-portuguese/snapshots/8926743abe7e95bb81b64305cb3c5fa85173f6b0' transcription model..
2023-10-17 09:01:18	[WARN]	[task.transcript.RemoteWav2Vec2TranscriptTask]			Fail to transcribe on server: XXX  audio: XXX.opus error: Exception while transcribing: java.lang.RuntimeException: iped.exception.IPEDException: Error loading '/home/transcript/.cache/huggingface/hub/models--jonatasgrosman--wav2vec2-xls-r-1b-portuguese/snapshots/8926743abe7e95bb81b64305cb3c5fa85173f6b0' transcription model..
2023-10-17 09:01:18	[WARN]	[task.transcript.RemoteWav2Vec2TranscriptTask]			Fail to transcribe on server: XXX  audio: XXX.opus error: Exception while transcribing: java.lang.RuntimeException: iped.exception.IPEDException: Error loading '/home/transcript/.cache/huggingface/hub/models--jonatasgrosman--wav2vec2-xls-r-1b-portuguese/snapshots/8926743abe7e95bb81b64305cb3c5fa85173f6b0' transcription model..
2023-10-17 09:01:19	[WARN]	[task.transcript.RemoteWav2Vec2TranscriptTask]			Fail to transcribe on server: XXX  audio: XXX.opus error: Exception while transcribing: java.lang.RuntimeException: iped.exception.IPEDException: Error loading '/home/transcript/.cache/huggingface/hub/models--jonatasgrosman--wav2vec2-xls-r-1b-portuguese/snapshots/8926743abe7e95bb81b64305cb3c5fa85173f6b0' transcription model..
```
Errors above in the transcription service should never happen because the node is added to the cluster just after the model is loaded correctly on GPU. But @hauck-jvsh reported sometimes the nodes Linux kernel (or GPU driver?) is being updated automatically, nodes are not restarted and the service continues running, returning errors above. @hauck-jvsh please try to disable automatic updates.

Anyway, if errors above are returned, we could add some protection in client code to remove the node from the cluster set and warn in the console so clients could warn the service maintainers about problematic nodes.

### PR DESCRIPTION
**Pull request by lfcnassif**
Fix #1942.

@hauck-jvsh, I'm still going to do tests, but I would appreciate your review, thanks.

### CODE REVIEW

**Comment by hauck-jvsh** [comment]
Sure, I will take a look at this today.

**Comment by lfcnassif** [comment]
I finished my changes and tests, this looks fine.

**Comment by lfcnassif** [comment]
Just an observation for others: audios that might theoretically cause crashes in python transcription processes were skipped intentionally, to avoid infinite loops on client side trying to transcribe the audio on different nodes. But as I think this is very unlikely to happen (corrupted audios often fail or trigger a timeout in the wav conversion step), and since we have this current situation of python processes crashing because of kernel or driver updates, I pushed commit 653dca1 to retry audios if python crashes, so clients won't skip audios silently. If some client hits some infinite loop with some corrupted audio, it won't be a silent issue, the client will complain and we can take a closer look at his audio to try to handle it properly.

**Comment by lfcnassif** [comment]
@hauck-jvsh tested this on a Kubernetes test environment and it worked, so I'm merging. Thank you @hauck-jvsh!

**Pull request merged**
