### PR TITLE
Timeline flushed index creation

### LINKED ISSUE #1666: Timeline chart draw synchronization problems
I found 2 points of problems when navigating too quickly in timeline chart. 
One is in internal unsynchronized operations on rowTimestamps arraylist of acumultor object.
The other is with unsync ref access to datasets when printing the chart.

### PR DESCRIPTION
**Pull request by patrickdalla**
Timeline index creation was optimized and adapted to flush intermediary results when memory consumption is beyond max memory estimated, to avoid OOM.
This pull request replaces #1653, as its content is included. (I will delete it)
With this PR, I think we can close #1666, #1652 and #1598.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Errors thrown after closing and re-opening a medium case of 11M items:
```
java.io.IOException: File not committed:072DEC1DDC310758DF3311470AF3CA61
	at iped.app.timelinegraph.cache.TimeIndexedMap.setIndexFile(TimeIndexedMap.java:47)
	at iped.app.timelinegraph.cache.persistance.CachePersistance.loadNewCache(CachePersistance.java:169)
	at iped.app.timelinegraph.cache.IndexTimeStampCache.run(IndexTimeStampCache.java:74)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.io.IOException: File not committed:072DEC1DDC310758DF3311470AF3CA61
	at iped.app.timelinegraph.cache.TimeIndexedMap.setIndexFile(TimeIndexedMap.java:47)
	at iped.app.timelinegraph.cache.persistance.CachePersistance.loadNewCache(CachePersistance.java:169)
	at iped.app.timelinegraph.cache.IndexTimeStampCache.run(IndexTimeStampCache.java:74)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.io.IOException: File not committed:072DEC1DDC310758DF3311470AF3CA61
2023-05-27 00:42:19	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Starting to build time cache of [[class org.jfree.data.time.Hour]]...
	at iped.app.timelinegraph.cache.TimeIndexedMap.setIndexFile(TimeIndexedMap.java:47)
	at iped.app.timelinegraph.cache.persistance.CachePersistance.loadNewCache(CachePersistance.java:169)
	at iped.app.timelinegraph.cache.IndexTimeStampCache.run(IndexTimeStampCache.java:74)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.io.IOException: File not committed:072DEC1DDC310758DF3311470AF3CA612023-05-27 00:42:19	[INFO]	[timelinegraph.cache.IndexTimeStampCache]			Starting to build time cache of [[class iped.jfextensions.model.Minute]]...

	at iped.app.timelinegraph.cache.TimeIndexedMap.setIndexFile(TimeIndexedMap.java:47)
	at iped.app.timelinegraph.cache.persistance.CachePersistance.loadNewCache(CachePersistance.java:169)
	at iped.app.timelinegraph.cache.IndexTimeStampCache.run(IndexTimeStampCache.java:74)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
The chart is not plotted. I think in this case the dirty cache should be deleted and rebuilt.

**Comment by patrickdalla** [comment]
"The chart was not plotted. I think in this case the dirty cache should be deleted and rebuilt. Not sure if cache building/storing was interrupted when closing the case or if it was saved wrongly. It happened 2x times in sequence."

That was the original behaviour. A modification to safelly close inputstream made a regression not raising the genereted "not committed exception". This was solved with commit 28d173f.

**Comment by lfcnassif** [comment]
> That was the original behaviour. A modification to safelly close inputstream made a regression not raising the genereted "not committed exception". This was solved with commit [28d173f](https://github.com/sepinf-inc/IPED/commit/28d173f3e08ed200c64f2e8e30738a67709399c7).

Thank you and sorry if I caused the regression, I was very tired when I did those commits and didn't test them properly.

**Comment by lfcnassif** [comment]
But, I didn't understand how commit 28d173f fixed the issue, since no exception is being caught. I think it can just theoretically throw an IOException when closing the streams before the "file not committed" IOException can be thrown...

**Comment by patrickdalla** [comment]
Nassif, I think you are right.
I thought that the missing of any catch block was simply ignoring any exception thrown inside the block. So the change does not altered the behaviour at all. Sorry.
But I could not reproduce the error. I am try to reproduce it.

**Comment by lfcnassif** [comment]
Hi @patrickdalla, I'm testing this again to finally merge it.

I detected that the first run on a case with 2.2M items takes 5s to build the Day cache and to render the time chart initially. After closing the case and opening it again, now with all time caches built, the time chart takes 18s to be rendered. I think it is not expected, or is it?

**Comment by patrickdalla** [comment]
With some of the late optimizations done, the time to build the cache and
to plot the chart became fast enough that I thought it would be
unnecessary to maintain the cache.
Though, the application of filters, the navigation on specific time
intervals and time period change is still significantly better using the
cache.

Il giorno mer 18 ott 2023 alle ore 12:47 Luis Filipe Nassif <
***@***.***> ha scritto:

**Comment by lfcnassif** [comment]
I did some profiling and found the slowness most time is here:
```
"pool-62-thread-1" #484 prio=5 os_prio=0 cpu=1859.38ms elapsed=2.52s tid=0x0000022c8b2b1800 nid=0x830c runnable  [0x0000009de046e000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.FileDispatcherImpl.read0(java.base@11.0.13/Native Method)
        at sun.nio.ch.FileDispatcherImpl.read(java.base@11.0.13/Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(java.base@11.0.13/Unknown Source)
        at sun.nio.ch.IOUtil.read(java.base@11.0.13/Unknown Source)
        at sun.nio.ch.FileChannelImpl.read(java.base@11.0.13/Unknown Source)
        - locked <0x000002247b0fcae0> (a java.lang.Object)
        at iped.utils.SeekableFileInputStream.read(SeekableFileInputStream.java:34)
        at iped.utils.SeekableFileInputStream.read(SeekableFileInputStream.java:42)
        at java.io.DataInputStream.readChar(java.base@11.0.13/Unknown Source)
        at org.roaringbitmap.RoaringArray.deserialize(RoaringArray.java:306)
        at org.roaringbitmap.RoaringBitmap.deserialize(RoaringBitmap.java:1711)
        at iped.app.timelinegraph.cache.persistance.CachePersistance.loadNextEntry(CachePersistance.java:387)
        at iped.app.timelinegraph.cache.TimeIndexedMap$ResultIterator.hasNext(TimeIndexedMap.java:234)
        - locked <0x000002247b0fb820> (a iped.utils.SeekableFileInputStream)
        at iped.app.timelinegraph.datasets.IpedTimelineDataset.caseSearchFilterLoad(IpedTimelineDataset.java:389)
        at iped.app.timelinegraph.datasets.IpedTimelineDataset$1.run(IpedTimelineDataset.java:178)
        at java.lang.Thread.run(java.base@11.0.13/Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.13/Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.13/Unknown Source)
        at java.lang.Thread.run(java.base@11.0.13/Unknown Source)
```
Seems to me it is slow because it calls SeekableInputStream.read(...) multiple times without buffering. I tried to put a BufferedInputStream between DataInputStream and its underlying SeekableInputStream, but it caused errors since there is a non trivial code that mixes reading from the DataInputStream and its underlying SeekableInputStream. Additionally, my case is on a SSD disk, I think if it is on a spinning disk (which is a common use case when we send extracted data to investigators), the slowness can increase a lot. Could you take a look and try to put buffering when loading the built caches?

**Comment by lfcnassif** [comment]
> Could you take a look and try to put buffering when loading the built caches?

A possible approach would be to use the Apache PDFBox `BufferedRandomAccessFile` instead of our SeekableInputStream, I'll try that later...

**Comment by lfcnassif** [comment]
> A possible approach would be to use the Apache PDFBox `RandomAccessBufferedFileInputStream` instead of our SeekableInputStream, I'll try that later...

It did the trick, loading the cache in a second UI opening now takes 3s-4s with the same 2,2M case.

**Comment by lfcnassif** [comment]
One question: is the `CacheDataInputStream.readInt2()` custom method really needed or can we remove it and use the default `DataInputStream.readInt()` ?

**Comment by lfcnassif** [comment]
Another issue: when first opening the case and building caches, when the last cache (seconds scale) is finished, the UI is refreshed and the zoom reset, even if the user started to interate/zoom into the chart using the first Day scale, aborting his analysis. @patrickdalla I would appreciate if you could take a look at this tomorrow morning.

I still plan to test multicases and read only cases. If no more issues are found, I think this can be merged.

**Comment by lfcnassif** [comment]
Thanks @patrickdalla! I had to force push to fix the issue reference number in your last commit, so please synchronize before implementing additional changes here.

**Comment by lfcnassif** [comment]
> I removed the command to refreshChart after all cache creation. I don't remember why exactly it was being done. I didn't reflect on any tests I have done. As you will continue testing, check if you see any colateral effect.

I think I discovered a collateral effect: after applying a Graph filter selecting some link, the time chart remains with the "loading" animation, being refreshed just if its panel is resized.

**Comment by lfcnassif** [comment]
> I think I discovered a collateral effect: after applying a Graph filter selecting some link, the time chart remains with the "loading" animation, being refreshed just if its panel is resized.

Actually not just the Graph filter, but any filter if the time chart is not visible.

**Comment by patrickdalla** [comment]
Thanks, I'll check it out.

Il giorno gio 19 ott 2023 alle ore 11:55 Luis Filipe Nassif <
***@***.***> ha scritto:

**Comment by lfcnassif** [comment]
> Thanks, I'll check it out.

I'm already fixing it.

**Review by lfcnassif — APPROVED** [review]
Hi @patrickdalla, I finished my changes. I think this is good and I'll merge, let me know if you find issues. Thank you for this important optimization!

**Pull request merged**
