### PR TITLE
Discord parser

### PR DESCRIPTION
**Pull request by felipecampanini**

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @felipecampanini! Have you noticed merge conflicts above? Are you comfortable to fix them?

**Comment by felipecampanini** [comment]
Hello @lfcnassif, sorry for the delay. I will review the conflicts

**Comment by lfcnassif** [comment]
@felipecampanini, @patrickdalla was trying to review this but he found merge conflicts in thousands of files. I took a look and seems you did a bad reverse merge of master here. I needed to force-push to fix that incorrect merge. Please take a look and check if I reverted some of your logic changes unintentionally, so @patrickdalla can proceed, thanks!

**Comment by lfcnassif** [comment]
At a first look, seems the date format in localization files were fixed just into the pt-BR localization and an AM/PM marker was introduced just in the English one, missing the other 3 localization files. I suggest always using 24h in all languages.

**Comment by patrickdalla** [comment]
Hi @felipecampanini . It seems the implementation mixes generic chrome cache index parsing with discord specific parsing. Wouldn't it be better to create a generic chrome index cache parser, and a specific discord parser? 
It seems the generic chrome parser could be very useful to parse some other content than discord content.
Maybe the discord parser could create the chats items querying the items from lucene already extracted by the generic chrome index cache parser.

**Comment by lfcnassif** [comment]
@felipecampanini does this contains the proposed changes on https://github.com/sepinf-inc/IPED/issues/1568?

**Comment by felipecampanini** [comment]
> @felipecampanini does this contain all proposed changes on #1568, right?

Exactly

**Comment by felipecampanini** [comment]
> Hi @felipecampanini . It seems the implementation mixes generic chrome cache index parsing with discord specific parsing. Wouldn't it be better to create a generic chrome index cache parser, and a specific discord parser? It seems the generic chrome parser could be very useful to parse some other content than discord content. Maybe the discord parser could create the chats items querying the items from lucene already extracted by the generic chrome index cache parser.

@patrickdalla, I even discussed this with lfcnassif in #1568.

The discord app uses the exact cache structure of Google Chrome. Therefore, I believe it would be ideal to use the same parser for both applications (Chrome and Discord).

However, the name should be ChromeCacheParser or something similar, but as explained by @lfcnassif, renaming the parser could cause some problems.

The same chat file that can be found in Chrome's cache can also be found in Discord's cache, so I believe they should be the same parser.

**Comment by felipecampanini** [comment]
> @felipecampanini, @patrickdalla was trying to review this but he found merge conflicts in thousands of files. I took a look and seems you did a bad reverse merge of master here. I needed to force-push to fix that incorrect merge. Please take a look and check if I reverted some of your logic changes unintentionally, so @patrickdalla can proceed, thanks!

I will review it calmly on Monday, sorry for the delay, this week I needed to focus on some urgent demands from the sector.

**Comment by lfcnassif** [comment]
> However, the name should be ChromeCacheParser or something similar, but as explained by @lfcnassif, renaming the parser could cause some problems.

One option is having 2 parsers: renaming the current one to ChromeCacheParser and creating a new one with the old name, extending the renamed parser. So things would continue working with old profiles.

> The same chat file that can be found in Chrome's cache can also be found in Discord's cache, so I believe they should be the same parser.

Out of curiosity, is this situation detected and deduplicated by current code?

> I will review it calmly on Monday, sorry for the delay, this week I needed to focus on some urgent demands from the sector.

I totally understand, don't worry.

**Comment by felipecampanini** [comment]
> Out of curiosity, is this situation detected and deduplicated by current code?

There is no deduplication, if the same chat is in the Google Chrome cache and in the Discord application cache for Windows, IPED will show two chat files. I'm not sure, but maybe IPED's duplicate filtering could work, I'll try to reproduce this behavior.

**Comment by felipecampanini** [comment]
Hi @lfcnassif, as I suspected, in a situation where there is the same chat in the Discord application cache and in the Google Chrome cache, they will have the same hash, which can be filtered by the IPED duplicate filter.

**Comment by lfcnassif** [comment]
> Hi @lfcnassif, as I suspected, in a situation where there is the same chat in the Discord application cache and in the Google Chrome cache, they will have the same hash, which can be filtered by the IPED duplicate filter.

Great news! So, I think just the single extracted messages would populate the communication graph and the timeline twice...

> @lfcnassif, I reviewed it here and apparently some changes were deleted. I have the backup here in my repository, @patrickdalla said he has some changes to send. I'll wait for it to commit and send the changes again.

Thank you for checking! And sorry about it, reverting the bad merge was not so easy... Yes, please wait until @patrickdalla push all his changes to avoid more merge conflicts.

**Comment by patrickdalla** [comment]
It seems there is new cache structure not supported by the Index parser.

https://www.chromium.org/developers/design-documents/network-stack/disk-cache/disk-cache-v3/

**Comment by lfcnassif** [comment]
@patrickdalla I think your commits referenced above are not going into this PR. Wasn't you able to push them to @felipecampanini repo? This usually works for me without origin repo permission changes... @felipecampanini can you give write permission to @patrickdalla to your repo?

**Comment by patrickdalla** [comment]
Hi @, I have reported to filipe about my difficulties in config his repo and he agreed to merge my changes in his repo latter.
I could fetch and work on it, but could not push.

**Comment by felipecampanini** [comment]
Hi @lfcnassif, I had already included the permission for @patrickdalla, but for some reason it still doesn't work.

@patrickdalla, can I submit the changes now? As soon as you finish, let me know so we can avoid conflicts in the merge.

@lfcnassif, can I send commits directly to the IPED repository? This way we can avoid these problems in the future.
Is the release of version 4.2 already close? I ask because it would be interesting to include these changes in the next version.

**Comment by lfcnassif** [comment]
> @lfcnassif, can I send commits directly to the IPED repository?

Sure! I just invited you to our organization.

> Is the release of version 4.2 already close? I ask because it would be interesting to include these changes in the next version.

I was planning to release it in the end of November or early December, but I'm not sure if there is enough time to include all desired PRs. This will be included, for sure.

**Comment by patrickdalla** [comment]
Hi @felipecampanini, my review is done.
Resuming, the main changes were:
1- Separate the parser in 2 parsers, one for Chrome Cache Index, an other for specific Discord entries. The first parser will extract each cache entry in the second processing queue, and the second will register itself to parse discord specific ones, in a third queue so it can find attachments and avatars from cache entries previously extracted.
2- Cache index parsing code was missing a loop to find entries in the linked list in the hash table bucket.
3- Logged account information is being extracted.

Please, compare and test if I made any mistake adapting your code.

**Comment by patrickdalla** [comment]
@lfcnassif, I had some difficulty in using felipe's repo directly, and he agreed that I could make my changes in new IPED branch and he would merge in his repo later.

**Comment by lfcnassif** [comment]
Thank you very much @patrickdalla for all your work reviewing this PR! @felipecampanini, after you accept the invitation I sent to you, please test branch pr-1859 where @patrickdalla pushed all changes, to check if it works with your test samples.

@patrickdalla for the future/next external contribution, what I usually do in eclipse is:
1. Checkout the PR as a new local branch:
image
2. Commit the changes locally.
2. Before pushing the changes, add the new remote repo:
image

**Comment by patrickdalla** [comment]
@lfcnassif , @felipecampanini made some observations that I solved. As soon as he makes his final tests with his test cases to look for any regression, if nothing more is noted, this can be merged.

PS.: I've noted some more artifacts that can be extracted, but can be object of other PR's with improvements.

**Comment by patrickdalla** [comment]
Hi @felipecampanini, with the help of @lfcnassif, I think I finally pushed to your repo. Please, confirm the push and the tests.

**Review by patrickdalla — APPROVED** [review]

**Comment by lfcnassif** [comment]
> Do you and @lfcnassif agree to push in this same PR, or should we create another?

Hi @patrickdalla, sorry for my delay, I saw you already pushed stickers support. Since it's ready and it changes the same related files, it's fine to put in this PR. But I saw you copied a whole library to the project. Please list it in the ThirdParty.txt file and put its licences into the licenses folder. That's a cool feature, thank you very much!

**Comment by felipecampanini** [comment]
@lfcnassif, @patrickdalla, firstly I had said that there were some changes missing that were not in the code after that problem with the merge, however, when reviewing the code sent by @patrickdalla, all the changes are there, I apologize for the confusion. Therefore, it will not be necessary to perform the merge again.

Thanks @patrickdalla, this function was excellent. I'm finishing the tests with the evidence I have here, as soon as I'm done I'll let you know.

**Comment by felipecampanini** [comment]
image

Hi @lfcnassif, @patrickdalla, I've finished my testing. The only thing I found is that now the chat ID only appears in the metadata tab, and does not appear in the table name field.

@lfcnassif, could you confirm if the code below actually changes the "name" field? Thanks!

`String chatName = "DiscordChat id(" + discordRoot.get(0).getId() + ")";

DiscordAuthor me = extractAccount(searcher, commonQuery, mapper, avatarCache, handler, extractor);

Metadata chatmetadata = new Metadata();

chatmetadata.set("URL", item.getName());
chatmetadata.set(TikaCoreProperties.TITLE, chatName);
chatmetadata.set(StandardParser.INDEXER_CONTENT_TYPE, CHAT_MIME_TYPE_HTML);`

**Comment by lfcnassif** [comment]
> @lfcnassif, could you confirm if the code below actually changes the "name" field? Thanks!
> 
> `String chatName = "DiscordChat id(" + discordRoot.get(0).getId() + ")";
> 
> DiscordAuthor me = extractAccount(searcher, commonQuery, mapper, avatarCache, handler, extractor);
> 
> Metadata chatmetadata = new Metadata();
> 
> chatmetadata.set("URL", item.getName()); chatmetadata.set(TikaCoreProperties.TITLE, chatName); chatmetadata.set(StandardParser.INDEXER_CONTENT_TYPE, CHAT_MIME_TYPE_HTML);`

It should if both `TikaCoreProperties.RESOURCE_NAME_KEY` and `ExtraProperties.MESSAGE_SUBJECT` are empty.

**Comment by felipecampanini** [comment]
Apparently it was a build problem, I ran a Maven clean and the chat IDs appeared correctly. So I don't have any changes to submit.

**Comment by lfcnassif** [comment]
After commit c5eb90d (propagate exception instead of silently catching it), I surprisingly got 25% more decoded chats and almost 2x more instant messages, although more parsing exceptions happen now. @felipecampanini or @patrickdalla, could some of you double check the commit to confirm it is fine?

**Comment by patrickdalla** [comment]
> After commit [c5eb90d](https://github.com/sepinf-inc/IPED/commit/c5eb90dc4f58134b924ce21976799c3def673944) (propagate exception instead of silently catching it), I surprisingly got 25% more decoded chats and almost 50% more instant messages, although more parsing exceptions happen now. @felipecampanini or @patrickdalla, could some of you double check the commit to confirm it is fine?

Are you using as sample your browser navigation? I came across some similar strange situation also, when using my own browser and discord session cache to test. My chats did not appear at first, although I have seen them on the browser. On a latter test, many chats appeared in IPED, from channels I have subscribed, although I have not seen them on browser. It seemed some Discord background processing that works with the cache, in second case, and delayed cache flush, in first, as the real sqlites used were consistent with IPED results. So I ignored.

If yes, could you revert your simple change on commit and test again to see if something the chat appears.

At first sight, this change isn't enough to recognize or recover any new chat.

**Comment by lfcnassif** [comment]
> Are you using as sample your browser navigation?

No, I'm using a fixed and immutable data set extracted from real cases...

**Comment by lfcnassif** [comment]
> If not, could you share your test base?

Sure.

**Comment by lfcnassif** [comment]
Before my commits:
image

After them, looks much better:
image

If there are no objections, I will merge with last commits. I just want to configure a few metadata types of new metadata keys, to avoid unneeded `:number` suffixes duplicating keys:
image

**Comment by patrickdalla** [comment]
@lfcnassif I could not repeat the first image of last msg with the test sample you sent me. 
Running with code till commit https://github.com/sepinf-inc/IPED/commit/de7b6a04548573c5f07b5055049eb97e0599590e gave me a similar result of the second image (except that discord JSON index entries was being counted as Chat category).

One thing I can observe in it is: It does not have any "browser artifacts" category items. So it seems you have run a yet older code commit, where the "Chrome Cache" subcategory wasn't defined.

**Comment by patrickdalla** [comment]
@lfcnassif: About the removal of Whatsapp related CSS, if I well remember, I have put it to make Audio and Video attachments reproducible directly from HTML, be it in viewer or in exported html report.
I could not find any audio or video attached to any of the chats in your sample, so I suppose you have not tested this possibility.
Could you review it?

**Comment by lfcnassif** [comment]
Thanks @patrickdalla for your tests!

I'll try to reproduce the first image I sent. About whatsapp css removal, I made it because the whatsapp chat background image was being displayed in some chats, giving a very weird look up. Please send me a sample with one audio and video as attachment, so I can test the change with them.

**Comment by lfcnassif** [comment]
Hi @patrickdalla, you're right, I did a mvn clean install and the same number of artifacts were recovered before and after my logic changes. About the WhatsApp CSS removal, this was what motivated me, this background shows up in many Discord chats:
image

**Comment by wladimirleite** [comment]
> About the WhatsApp CSS removal, this was what motivated me, this background shows up in many Discord chats: 

I think it would be better to have another CSS, even if it means some duplication. Otherwise changes in WhatsApp CSS (which is already complex) may cause undesired side effects in other parsers.

**Comment by lfcnassif** [comment]
I finished my review and pushed a minor fix and some adjustments. Thank you very much @felipecampanini and @patrickdalla for this great work!

**Pull request merged**
