### PR TITLE
#1685 do not extract items with the same trackId

### PR DESCRIPTION
**Pull request by hauck-jvsh**
Recreate the commit as you asked.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Hi @hauck-jvsh, thanks for this PR and sorry for my delay. As I thought initially, just ignoring the item may not be the best solution, as we are missing the picture of the shared contact in the chat. I pushed a possible improvement and if ongoing tests look good, I'll merge this, thanks!

**Review by lfcnassif — APPROVED** [review]

**Comment by tc-wleite** [comment]
@lfcnassif, processing a UFDR with the master branch, I got a NPE at `UfedXmlReader.java:788`, which may be related to commit [f23f7bc](https://github.com/sepinf-inc/IPED/pull/1703/commits/f23f7bc25072fb0309e7587e4fd73f679d074c73).
Adding a condition to check if `parentItem.getMediaType()` is not null was enough to prevent the exception: 
```java
if (parentItem.getMediaType() != null && UFED_CONTACTPHOTO_MIME.equals(parentItem.getMediaType().getSubtype())) {
    (...)
}
```

**Comment by lfcnassif** [comment]
Thanks for warning @tc-wleite! I'll fix it later today.

**Comment by lfcnassif** [comment]
> @lfcnassif, processing a UFDR with the master branch, I got a NPE at `UfedXmlReader.java:788`, which may be related to commit [f23f7bc](https://github.com/sepinf-inc/IPED/pull/1703/commits/f23f7bc25072fb0309e7587e4fd73f679d074c73).

Just pushed the fix, thanks!

**Pull request merged**
