### PR TITLE
#633 optimize telegram html

### LINKED ISSUE #640: TelegramParser building invalid unicode strings in subitem names
See #638 . Current classes triggering MalformedInputException were fixed, but it would be good to fix the issue in the source to avoid problems in future classes.

### PR DESCRIPTION
**Pull request by hauck-jvsh**
This pull request fixes #640  and implements the same algorithm used in the WhatsApp parser to optimize the audio and video tags.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @hauck-jvsh!

**Comment by lfcnassif** [comment]
@hauck-jvsh the commits related to #640 are not needed and actually now they are removing valid surrogate pairs, sorry again.

Do you want to create a separate PR with just #633 or should I do that?

**Comment by hauck-jvsh** [comment]
I can do that, its very strange that java's substring creates an invalid string.

**Comment by hauck-jvsh** [comment]
I think that now all changes related to #640 were reverted;

**Comment by lfcnassif** [comment]
Thank you, @hauck-jvsh!

**Comment by lfcnassif** [comment]
Just did a fix in 8481763 and other minor changes before merging.

**Comment by hauck-jvsh** [comment]
I didn't test it very deeply, sorry for mistakes.

**Pull request merged**
