### PR TITLE
#1833 fix

### LINKED ISSUE #1833: Transcribing audios with more than 2GB on remote service never ends
@arisjr Sent to me two audio files with more than 2GB and they aren't being processed correctly, the server log shows the following error 

> 21:52:55.767 [pool-1-thread-1714] INFO  iped.engine.task.transcript.RemoteWav2Vec2Service - Client 10.244.3.0:50890 - Accepted connection.
21:52:55.767 [pool-1-thread-1714] INFO  iped.engine.task.transcript.RemoteWav2Vec2Service - Protocol Version VERSION_1_1
21:52:55.767 [pool-1-thread-1714] INFO  iped.engine.task.transcript.RemoteWav2Vec2Service - Client 10.244.3.0:50890 - Receiving -2,028,500,146 bytes...
21:52:55.768 [pool-1-thread-1714] WARN  iped.engine.task.transcript.RemoteWav2Vec2Service - Exception while transcribing
java.io.IOException: Received less audio bytes than expected
        at iped.engine.task.transcript.RemoteWav2Vec2Service$2.run(RemoteWav2Vec2Service.java:353) [iped-engine-4.2-snapshot.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

I think that this is due to an integer overflow as the receiving bytes  shown is a negative number.

### PR DESCRIPTION
**Pull request by hauck-jvsh**
Closes #1833

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @hauck-jvsh! Could you please fix the code formatting?

**Comment by hauck-jvsh** [comment]
For sure, but I'm still testing a way to skip these files in old client version.

**Comment by lfcnassif** [comment]
Fine! So, since this is not ready, I'm changing to draft, please revert when finished, thank you!

**Comment by hauck-jvsh** [comment]
I think that now it is stopping the old clients, however I didn't like very the need of read the entire file before sending the error.

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh! What do you think about returning for old clients a transcription like "Audios longer than 2GB are not supported by old clients, please update your client version!" instead of just skipping long audios and logging a message for them most users wouldn't read? Or at least putting that message in the Exception String.

**Comment by hauck-jvsh** [comment]
I think that this is a great idea. It should be noticed faster than just sending the exception.

**Comment by hauck-jvsh** [comment]
I think that now it is ready. For old clients the following transcription is returned.
image

**Comment by lfcnassif** [comment]
Thank you @hauck-jvsh! Since you are working on this, just 2 minor final suggestions: on line 310 I think it is better to compare if Messages.AUDIO_SIZE.toString() does not start with the decoded String to avoid issues in the future with new protocol versions. And I would put version 1_0 into the Messages Enum.

**Comment by hauck-jvsh** [comment]
After you said I also think that this is better.

**Review by lfcnassif — APPROVED** [review]
Thank you very much @hauck-jvsh!

**Pull request merged**
