### PR TITLE
Recover deleted sqlite records WIP - closes #667

### LINKED ISSUE #667: Recover deleted records from SQLite databases
This is an old desired feature. I will push an old "study" branch (not even a draft or prototype) about sqlite structures.

### PR DESCRIPTION
**Pull request by fmpfeifer**
## FQLite side

In order to implement this feature, we chose to make use of FQLite (https://github.com/pawlaszczyk/fqlite).
Although FQLite is an excellent tool, it is not implemented to be used as a library.
So, first we had to fork the project and make many adjustments to make it suitable to be used as a library. The fork can be found here: https://github.com/fmpfeifer/libfqlite
The project is dual licensed under GPL v3 and MPL v2, so it can be used in IPED.
Among the changes made to the FQLite code, we can highlight:
- Get rid of the GUI components (were heavily mixed in code);
- Get rid of many System.out.println throughout the code;
- Create some classes to make the API easier to consume;
- Do not load the whole sqlite file in memory anymore;
- many more...

We also uploaded the release into the main maven repository (https://search.maven.org/artifact/io.github.fmpfeifer/libfqlite/1.56.02-beta/jar) to make it easier to use in IPED.

## IPED side

In IPED, we created a few classes to extract deleted records from SQLite databases, using the libfqlite above.
Then we used those classes to recover deleted messages in the android version of WhatsApp.

Here is one example of some recovery messages in a real case:
image

## ToDo

Those are still some implementations planned for this PR (implementations for other SQLite databases can be done later):

- Extend the implementation to also recover deleted chats (not only deleted messages);
- Extend the implementation to IOS version of WhatsApp;
- Implement recovery of deleted data in the generic SQLite3DBParser

Comments are very welcome.
Thanks

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you very much @fmpfeifer! I will try to review next week, tomorrow I'm out of office.

**Comment by lfcnassif** [comment]
Starting to do a first look now.

**Review by lfcnassif — COMMENTED** [review]
What pom.xml changes were done? There are some indentation changes mixed together...

**Comment by fmpfeifer** [comment]
> 
> 
> What pom.xml changes were done? There are some indentation changes mixed together...

oh, sorry about that. I think vscode messed up with it.
the changes were the addition of the following dependencies in iped-parsers-impl/pom.xml:
```xml
<dependency>
  <groupId>org.antlr</groupId>
  <artifactId>antlr4-runtime</artifactId>
  <version>4.9.2</version>
</dependency>
<dependency>
  <groupId>commons-codec</groupId>
  <artifactId>commons-codec</artifactId>
  <version>1.15</version>
</dependency>
<dependency>
  <groupId>io.github.fmpfeifer</groupId>
  <artifactId>libfqlite</artifactId>
  <version>1.56.02-beta</version>
</dependency>
```

actually the antlr and commons-codec are dependencies of libfqlite, I think we can get rid of it, as will be pulled by the dependecies in libfqlite.

**Comment by fmpfeifer** [comment]
I added those dependencies (commons-codec and antlr) before I was able to upload libfqlite to maven, and I forgot to remove afterwards

**Comment by lfcnassif** [comment]
> I added those dependencies (commons-codec and antlr) before I was able to upload libfqlite to maven, and I forgot to remove afterwards

So they could be removed?

@fmpfeifer this was a great work, thank you! I don't know if it is possible to make things more transparent to developers, if not, the needed changes, at least in the android whatsapp parsing code, looked small to me, great!

**Comment by fmpfeifer** [comment]
> > I added those dependencies (commons-codec and antlr) before I was able to upload libfqlite to maven, and I forgot to remove afterwards
> 
> So they could be removed?
I think so. I will test here and make a commit if it works 
> 
> @fmpfeifer this was a great work, thank you! I don't know if it is possible to make things more transparent to developers, if not, the needed changes, at least in the android whatsapp parsing code, looked small to me, great!

Thanks. The idea was to make it as close as possible of a normal sqlite data pull. Needs some polishing yet

**Comment by lfcnassif** [comment]
Please let me know how much time you estimate to finish this, so I will try to negotiate your efforts here.

**Comment by lfcnassif** [comment]
Adding some TODOs to track:
- Implement recovery in all other app supported sqlite databases: ChromeSqliteParser, FirefoxSqliteParser, SafariSqliteParser, TelegramParser, SkypeParser, both GDrive parsers, WinXTimelineParser

**Comment by fmpfeifer** [comment]
Hi @lfcnassif, i also implemented the recovery for WhatsApp IOS messages. Seems to be working here.
This change was a little bit more intrusive, because the parser uses fancy SQL SELECTS (functions, joins, etc) that cannot be used with deleted records (it only recover table and index rows).

I'm going on vacation, and I came back only in December. Do you think that it is better to leave this open until then, or we merge what we have (after review and testing), and implement the recovery for the remaining items after I came back?

**Comment by lfcnassif** [comment]
Thank you @fmpfeifer! If the API are not going to change, I think this could be possibly merged after better review and testing (I just took a look at the API and overall design). Maybe the generic SQLiteParser could be adapted before.

**Comment by fmpfeifer** [comment]
I think it would be better to wait a little bit more. I had to make a few changes in the api to extend to WhatsApp IOS. I think it is no stable enough yet

**Comment by lfcnassif** [comment]
@fmpfeifer I expect to release 4.0.0 in one month or two (depending on the features to be included) and it would be really great if we could include this. Do you plan to continue the work on this in the near future? Do you need some support from our side to help you having time to work on this?

**Comment by fmpfeifer** [comment]
Hi @lfcnassif, I'm closing this PR and I'm creating a new one.
thanks

**Pull request closed without merging**
