### PR TITLE
Avoid conflicts with bookmark shortcuts. 

### LINKED ISSUE #722: Avoid conflict between bookmark shortcuts and navigation/assigned keys
A minor usability enhancement: 
when the focus is in bookmark list (in the bookmark manager window), it is possible to assign keys that will conflict with the navigation in the list itself, items list or items gallery.
These keys include: 
- HOME, END, PAGE UP, PAGE DOWN, ARROWS (4 directions).
- Already used combinations: CTRL+A (select all), CTRL+B (open bookmarks manager window) and CTRL+C (copy selected cell content).

Although the user can just avoid using these keys as bookmarks shortcuts, it is better to prevent its usage, as it can lead to strange behaviors.
CTRL+A can be useful in the bookmark list (to select all bookmarks for exclusion or removal of items), but currently it is not possible to use it for selection, as it would try to also assign this combination. 

I propose to ignore these keys when assigning bookmarks shortcuts, so they will be handled in the standard way.

### PR DESCRIPTION
**Pull request by tc-wleite**
A minor usability enhancement. Closes #722.
I known that CTRL +/- are currently used, but I think those should be removed (replaced by menu items inside a "theme/font" menu) when implementing #679.

### CODE REVIEW

**Comment by tc-wleite** [comment]
Added the code (and a message) to handle SPACE and R keys.

**Comment by lfcnassif** [comment]
thanks @tc-wleite!

**Comment by tc-wleite** [comment]
@lfcnassif, I think CTRL+A could be left with no message, otherwise it would display the message when used to select all bookmarks. It could be handled as a navigation key.

**Comment by lfcnassif** [comment]
Sorry, will fix shortly.

**Comment by lfcnassif** [comment]
Just fixed on master as this was already merged.

**Comment by tc-wleite** [comment]
Thanks! It was just a very minor detail.

**Pull request merged**
