### PR TITLE
#1663 beacons

### PR DESCRIPTION
**Pull request by hauck-jvsh**
Sends a beacon each 60 seconds to keep the TCP connection alive.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @hauck-jvsh! Seems good to me. I would just change the LinkedList for a HashSet, maybe it can speed up removals a little bit.

If you tested old clients and new clients with the new service version, including the huge audio that caused the timeouts, and everything is fine, I think this can be merged. I won't be able to test it soon...

**Comment by hauck-jvsh** [comment]
I have tested it with old clients and new ones and it worked. Of course when an old client try to process the gigantic audio it ends up with the timeout as before. But with the new client all works well. I can change to HashSet, to be honest I have think about it yesterday when Implement I didn't change because the list should have a maximum of 128 clients. Because of the small size of the list I think the linkedlist should be okay.

**Comment by hauck-jvsh** [comment]
Just a note, I have changed yesterday the image used in the cluster here, it looks goods until now.

**Comment by lfcnassif** [comment]
> I can change to HashSet, to be honest I have think about it yesterday when Implement I didn't change because the list should have a maximum of 128 clients. Because of the small size of the list I think the linkedlist should be okay.

I also thought about it, no problem, HashSet also uses internal lists in each bucket, maybe we can increase that 128 constant in the future, but let's keep it as is, the diff should be minimal today, if it exists.

> Just a note, I have changed yesterday the image used in the cluster here, it looks goods until now.

Excellent, so I'm going to merge. Thank you very much!

**Review by lfcnassif — APPROVED** [review]

**Pull request merged**
