### PR TITLE
Delay map update when visible

### PR DESCRIPTION
**Pull request by patrickdalla**
This branch is for master. A correspondent branch for 4.1.x was created: DelayMapLoad_4_1_x

### CODE REVIEW

**Comment by felipecostadesousa** [comment]
Hello @patrickdalla, I tested this pull request last week and just found some erros in the map display. Basically when you select more than 1 gps locations in the map display and then you click in a previous selected location, the checked event disappears and the mark is not sync anymore. Here is the video I recorded showing some exemples of that mistake.
https://github.com/sepinf-inc/IPED/assets/81444931/224f2cf0-e875-4eb0-8977-21ce2536c18b
I don't know if I was clear with the explanation, but @lfcnassif confirmed that this behavior was weird.
Thank you =).

**Comment by patrickdalla** [comment]
The video was clarifying. I will look at this soon.

Em qua., 2 de ago. de 2023 09:29, Felipe Costa de Sousa <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
Thanks @felipecostadesousa for helping to test this. When you finish, please I would like your help to test #1669.

**Comment by lfcnassif** [comment]
While testing this, I got 2 kind of exceptions in UI log:
```
java.lang.NullPointerException
	at iped.geo.impl.AppMapPanel.accept(AppMapPanel.java:340)
	at iped.geo.impl.AppMapPanel.accept(AppMapPanel.java:50)
	at iped.geo.js.GetResultsJSWorker.done(GetResultsJSWorker.java:79)
	at java.desktop/javax.swing.SwingWorker$5.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.doneEDT(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$2.done(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.finishCompletion(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.cancel(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.cancel(Unknown Source)
	at iped.geo.impl.AppMapPanel.updateMap(AppMapPanel.java:245)
	at iped.geo.impl.MapViewer.tableChanged(MapViewer.java:144)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableDataChanged(Unknown Source)
	at iped.app.ui.UICaseSearcherFilter.done(UICaseSearcherFilter.java:336)
	at java.desktop/javax.swing.SwingWorker$5.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at java.desktop/sun.swing.AccumulativeRunnable.run(Unknown Source)
```
And:
```
java.lang.IndexOutOfBoundsException: Invalid index
	at iped.app.ui.parallelsorter.ParallelRowSorter.convertRowIndexToModel(ParallelRowSorter.java:526)
	at java.desktop/javax.swing.JTable.convertRowIndexToModel(Unknown Source)
	at iped.geo.impl.MapViewer$2.run(MapViewer.java:210)
	at iped.geo.impl.AppMapPanel.runAfterLoad(AppMapPanel.java:389)
	at iped.geo.impl.MapViewer.valueChanged(MapViewer.java:242)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
	at java.desktop/javax.swing.JTable.clearSelectionAndLeadAnchor(Unknown Source)
	at java.desktop/javax.swing.JTable.sortedTableChanged(Unknown Source)
	at java.desktop/javax.swing.JTable.tableChanged(Unknown Source)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableDataChanged(Unknown Source)
	at iped.app.ui.UICaseSearcherFilter.done(UICaseSearcherFilter.java:336)
```
@patrickdalla, when you have time, could you take a look?

**Comment by lfcnassif** [comment]
Another error:
```
java.lang.IndexOutOfBoundsException: Invalid index
	at iped.app.ui.parallelsorter.ParallelRowSorter.convertRowIndexToView(ParallelRowSorter.java:505)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(Unknown Source)
	at iped.geo.impl.AppMapPanel.getItemPositioninResultsTable(AppMapPanel.java:455)
	at iped.geo.impl.AppMapMarkerEventListener.onClicked(AppMapMarkerEventListener.java:26)
	at iped.geo.openstreet.MapCanvasOpenStreet$9.run(MapCanvasOpenStreet.java:453)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by patrickdalla** [comment]
Right. i wil review it. thanks for testing.

Em sex., 13 de out. de 2023 17:35, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by patrickdalla** [comment]
The first NullPointerException reported was being cause by an intermediary updateFileListing, called by Iped timeline clearFilter method, although it is called again at the end of all filters from IPED UI filterers being cleared. As part of the map update is done in background thread, the first updateFileListing was triggering a map update that was cancelled by the next updateFileListing. This was leading to a null object as result. And this null object wasn't being correctly handled. This was solved by previous commits.

**Comment by lfcnassif** [comment]
Great, thanks @patrickdalla for investigating and fixing it!

**Comment by patrickdalla** [comment]
Some of the IndexOutOfBoundsException occurs because of the lead selection cleaning on the results table and the old bad treatment of this condition by the methods getTrackSiblings and getSelectedJSONFeature. They were corrected by last 2 commits.

**Comment by patrickdalla** [comment]
The last IndexOutOfBoundsException occurred when the old lead selection id does not exists in the new result set. The method getItemPositioninResultsTable now returns -1 when this condiction occurs and the calling codes were changed to treat better this condition.

**Review by lfcnassif — APPROVED** [review]
Thank you @patrickdalla!

**Pull request merged**
