### PR TITLE
Handle more UFDR categories (#1370)

### LINKED ISSUE #1370: Create categories for other types extracted from UFDRs
When processing UFDRs, there are a few categories that stay with their "raw name".
This is an expected behavior, as there are too many possible categories and new ones may be created in new releases of Cellebrite tools.
Nevertheless, we can handle the most common categories already known, giving a proper name and translation, adding an icon, and in some cases grouping them:

- activitysensordata
- activitysensordatameasurement
- activitysensordatasample
- appsusagelog
- chatactivity
- creditcard
- deviceconnectivity
- deviceevent
- filedownload
- journey
- keyvaluemodel
- messagelabel
- networkusage
- profilepicture
- recognizeddevice
- socialmediaactivity
- webaddress

### PR DESCRIPTION
**Pull request by tc-wleite**
Closes #1370

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @tc-wleite!

I think this deserves some additional investigation. Maybe some of the new category items (message labels, key value model, profile pictures) are actually properties of pre existing items (like messages) and should be merged as properties/metadata instead of generating separate items... In UfedXmlReader class there is already a `mergeInParentNode` Set that hopefully may be enough if updated.

**Comment by lfcnassif** [comment]
> Makes sense!
> I already have a case with all these UFDR types, from several different UFDRs.
> I will take a look and see if we can merge some of them.

Great, thank you! Possibly you will need to check the report.xml files in UFDR root for those attribute values.

**Comment by tc-wleite** [comment]
> Maybe some of the new category items (message labels, key value model, profile pictures) are actually properties of pre existing items (like messages) and should be merged as properties/metadata instead of generating separate items...

I marked this as draft while I work on this.

UFDR types to be check for possible merge or removal:

- [ ] activitysensordata
- [ ] activitysensordatameasurement
- [ ] activitysensordatasample
- [ ] appsusagelog
- [ ] chatactivity
- [ ] creditcard
- [ ] deviceconnectivity
- [ ] deviceevent
- [ ] filedownload
- [ ] journey
- [ ] keyvaluemodel
- [ ] messagelabel
- [ ] networkusage
- [ ] profilepicture
- [ ] recognizeddevice
- [ ] socialmediaactivity
- [ ] webaddress

**Comment by tc-wleite** [comment]
In short:

### Merged

- ContactEntry
- KeyValueModel
- MessageLabel
- ProfilePicture
- WebAddress

### Parent entities:

- ActivitySensorData
- AppsUsageLog
- Creditcard
- DeviceConnectivity
- DeviceEvent
- FileDownload
- Journey
- NetworkUsage
- RecognizedDevice
- SocialMediaActivity

### Child but kept as items:

- ActivitySensorDataMeasurement
- ActivitySensorDataSample
- ChatActivity

**Comment by lfcnassif** [comment]
Great, thank you @tc-wleite!

**Review by lfcnassif — APPROVED** [review]

**Pull request merged**
