### PR TITLE
Evtx parser

### PR DESCRIPTION
**Pull request by patrickdalla**
Parser improved to extract individual event records types and timestamps. Some others event records grouping improvements, detailed in issue #1322, were included.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Hi @patrickdalla, could you fix the merge conflicts here?

**Comment by patrickdalla** [comment]
@lfcnassif , I could not understand why the above last commit is still not resolvable and not mergeable.

**Comment by lfcnassif** [comment]
Hi @patrickdalla, some issues/doubts on this:
- New parsers are not thread safe, I think I can fix them;
- RegRipperParser was disabled and RegistryParser was enabled. Is this needed? If yes, maybe a MultipleParser with both could be configured...
- There are some changes in iped-app/resources/config/conf/parsers/iped.parsers.registry.RegistryParser/ files. They are needed, right?

**Comment by lfcnassif** [comment]
So we have 2 new parsers here that support the same mimeType (application-x-elf-file), but just EvtxGroupedParser was installed. What is the purpose of EvtxRecordParser, just be an alternative parser?

**Comment by lfcnassif** [comment]
OK, thank you for the explanation. So could you please remove unneeded code or changes pushed by mistake?

**Comment by lfcnassif** [comment]
Just pushed a fix to thread safety. I'll wait for your PR fixes before continuing the review, thanks.

**Comment by patrickdalla** [comment]
EvtxRecordParser can be removed. But there is one advantage in keeping it for use: Although EvtxGroupedParser can be configured in a way it extracts each evtx record as a separate item, it computes unecessary info trying to group individual evtxrecords. So, if the user needs/prefers this kind of result, he should do it better using EvtxRecordParser.

That's why I keep it to decide with you if we can keep or not.

**Comment by patrickdalla** [comment]
I replaced regripparser as default registry parser. So, when you finally decide to keep or remove EvtxRecordParser, tell me, if you prefer that I do this.

**Comment by lfcnassif** [comment]
Should we delete the old evtx cmd line parser tool when merging this?

**Comment by patrickdalla** [comment]
Yes, I see no need to execute the old parser.

**Comment by lfcnassif** [comment]
> So, when you finally decide to keep or remove EvtxRecordParser, tell me, if you prefer that I do this.

I decided to remove the EvtxRecordParser to easy maintenance.

**Comment by lfcnassif** [comment]
So, as this parser can potentially generate hundreds of thousands (or even millions) of events, should we enable it by default on some profile? I think it should stay disabled in the default one.

**Comment by patrickdalla** [comment]
I agree. Maybe it may be enabled in forensics profile.

Em sex., 3 de fev. de 2023 15:08, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
Hi @patrickdalla, have you compared this parser output with the old cmd line one to see if we are still extracting the previous decoded info?

**Comment by patrickdalla** [comment]
> 
Yes. There is one kind of datatype that the evtxexport interprets in more detail, BINARY_TYPE, but for the occurrences I found of this datatype usage, the data was peculiar to that kind of event, and the interpretation done still wasn't too explanatory needing  more background knowledge of the analyst. (events of source Software Protection Platform Service, for example).

I have done also comparisons with results presented by event viewer app, also. One of the evtxfile could not be parsed by evtxexport, while it was opened by Event Viewer and parsed by the EvtxParser. It seems that evtxexport makes many validations for the data, and don't work if some inconsistency is found, even if this inconsistency affects only 1 log record. For all files others, the content was similar.

**Comment by lfcnassif** [comment]
> Yes. There is one kind of datatype that the evtxexport interprets in more detail, BINARY_TYPE, but for the occurrences I found of this datatype usage, the data was peculiar to that kind of event, and the interpretation done still wasn't too explanatory needing more background knowledge of the analyst. (events of source Software Protection Platform Service, for example).
> 
> I have done also comparisons with results presented by event viewer app, also. One of the evtxfile could not be parsed by evtxexport, while it was opened by Event Viewer and parsed by the EvtxParser. It seems that evtxexport makes many validations for the data, and don't work if some inconsistency is found, even if this inconsistency affects only 1 log record. For all other files, the content was similar.

Great, thank you!

**Comment by lfcnassif** [comment]
> I agree. Maybe it may be enabled in forensics profile.

Current approach is duplicating the whole ParserConfig.xml file in forensic profile, like it is in blind profile. I'll try to implement the proposal I talked here: https://github.com/sepinf-inc/IPED/pull/1341#issuecomment-1423030583

@patrickdalla just to confirm you haven't started nothing about that, right?

**Review by lfcnassif — APPROVED** [review]
Thank you @patrickdalla!

**Pull request merged**
