### PR TITLE
Extract frames from animated images

### PR DESCRIPTION
**Pull request by tc-wleite**
This implements what was discussed in #763. 
Animated GIFs and APNGs support seems to be working fine and should be useful.

Testing with a couple of disk images from real cases I am working with, I found several images that I thought to be static images, including APNGs. 
Also find quite a few of these animated images in LED database.

@lfcnassif, I created a subcategory of images ("Animated Images"), but the current classification is somewhat based on the file location (Temporary Internet Images, Images in System Folders), and I found the result a bit confusing, as there could be animated images in these folders. 
I ended up rolling back, and didn't create any new category.
However, these animated images can be easily find using a filter by "image:AnimationFrames" property.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @tc-wleite!

**Comment by lfcnassif** [comment]
@tc-wleite, what do you think about updating DIETask to take into account all frames extracted from animated images? If you agree, I will update it.

**Comment by lfcnassif** [comment]
@tc-wleite, let me know if you disagree or find some issue with last changes, thank you!

**Comment by tc-wleite** [comment]
Thanks @lfcnassif!
I was in an external activity, just returned to my desk... 
I think the changes you made make perfect sense.
Anyway, I will run a set of tests and take a look in the changed code and let you know if there is anything to be improved.

**Comment by tc-wleite** [comment]
I ran a few tests and inspected the changed code. 
Everything looks fine.
I think #763 can be closed.

**Comment by tc-wleite** [comment]
@lfcnassif, running unrelated tests, I detected a small regression caused by the last commit in this branch (1706bb6).
Document (PDF/LibreOffice) thumbs are not being displayed anymore.
I will submit a PR with fixing this.

**Comment by lfcnassif** [comment]
uh... sorry! And thank you for detecting this!

**Comment by tc-wleite** [comment]
No problem! I missed that when tested/reviewed the changes.

**Pull request merged**
