### PR TITLE
Handle new UFDR attachment's extracted path

### PR DESCRIPTION
**Pull request by marcosammoura**
Refers to issue #2028 

Analysis of `report.xml` files in UFDR reports generated by PA 8.7.100.106 and PA 10.0.100.93 has shown that `attachment_extracted_path` field for some instant message attachments point to non-existent files.

I have made the following main changes to `UfedXmlReader` class so that the correct attachment path is set, according to path information obtained using the `file_id` attachment attribute:
1- `ufedFileIdToLocalPath` HashMap was created to hold the `Local Path` information corresponding to each file tag within the report (file tag `id` attribute is the key and `Local Path` is the value)
2- `handleAttachment` method was changed so that if `extracted_path` is non-existent, `file_id` attachment attribute is used to get file path stored within the `ufedFileIdToLocalPath` HashMap, which then is set as the `extracted_path`

With such changes in place I have successfully processed IPED cases configured to use external phone parsers in which there were broken links to some chats' attachments.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @marcosammoura for this contribution! I'll try to review it in the next week. But I would need some UFDR samples from PA 8 or 10 for testing, I don't have any. For those who can help, please send a private link to me, thanks.

**Comment by patrickdalla** [comment]
Hi @marcosammoura , Nassif asked me to test and review this. Though I have processed one case with Inseyets, and for this case I could not find any occurence of the problem you solved. Could you provide me with some problematic sample case?

**Comment by patrickdalla** [comment]
Have you processed these problematic cases with PA 7.* or older? Maybe this is not a problem specific to IPED processing PA 8.*.

I suppose that it can occur when the file is moved from the original folder where the IM app downloaded it, so it does not exists there anymore, but its file id can be used to find its new path.

**Review by patrickdalla — APPROVED** [review]
Anyway, the code solves the problem.

**Comment by patrickdalla** [comment]
@lfcnassif I approved this correction.

**Comment by lfcnassif** [comment]
Thanks @patrickdalla! Last week I got a few UFDRs generated by PA 8 from a colleague. I'll share them with you. Ideally we should reproduce the issue to be sure this proposal fixes it. If @marcosammoura could share a triggering sample privately, That would help for sure.

**Comment by patrickdalla** [comment]
I found a triggering sample from the cases you sent me and the solution implemented by @marcosammoura worked, as I have reported to you via Teams.

**Comment by lfcnassif** [comment]
Thanks @patrickdalla for reproducing the issue and confirming the fix and thanks @marcosammoura for submitting this PR!

**Comment by lfcnassif** [comment]
@aberenguel just reported this fix caused a collateral effect: https://github.com/sepinf-inc/IPED/issues/2262

**Comment by marcosammoura** [comment]
I'll check the reported issue

**Pull request merged**
