### PR TITLE
First code for Issue #334 (https://github.com/sepinf-inc/IPED/iss…

### PR DESCRIPTION
**Pull request by thalespr**
…ues/334):

- Added new mime types: application/x-firefox-mozlz40 (for Mozilla LZ4 files) and application/x-firefox-savedsession (subclass of Mozilla Lz4 files that are related to saved sessions);
- Added new category (profile en/forensic): Mozilla Firefox Saved Session;
- Created FirefoxSavedSessionParser class to parse application/x-firefox-savedsession files. Package: dpf.pi.gpinf.firefox.parsers;
- FirefoxSavedSessionParser class takes the files, decompress them using net.jpountz.lz4 lib/pack and then uses org.json.simple.parser.JSONParser to extract web cookies from those files;
- This feature is only availabe, at this moment, for en/forensic profile.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @thalespr for this PR. Just a first question, is the configured signature specific of firefox session files or is a generic lz4 signature?

**Comment by thalespr** [comment]
> Thank you @thalespr for this PR. Just a first question, is the configured signature specific of firefox session files or is a generic lz4 signature?

None. It's the signature of generic Mozilla Firefox LZ4 file. The first 8 bytes contain the string **moz**lz40 (or something like that...). The Firefox saved session files are just part of the Mozilla LZ4 file group. There can be other Mozilla LZ4 files that aren't in the scope of saved sessions... That's why we look for a glob pattern besides the signature...

**Comment by lfcnassif** [comment]
@thalespr, last table column is not being populated with row data, please take a look.

**Comment by thalespr** [comment]
> @thalespr, last table column is not being populated with row data, please take a look.

Ok, I'm gonna check it out. Thank you for your review.

Best regards.

**Comment by thalespr** [comment]
> @thalespr, last table column is not being populated with row data, please take a look.

@lfcnassif Alright, got it. There was an useless blank column printed out (my bad). Patch fix was committed 8fc4017cbd39bc64aac3e4f34c866a7d12851663.

Also, I just want to point out that some of cookies' values are large enough to mess the HTML preview up. Need to think a better approach to handle that. I'm gonna work on it next days.

Thank you for your time.

**Comment by thalespr** [comment]
> Also, I just want to point out that some of cookies' values are large enough to mess the HTML preview up. Need to think a better approach to handle that. I'm gonna work on it next days.

Just a heads up:

Well, unfortunately there's nothing much to do for that point... Since Cookies' can take values with a variety of sizes and considering that it's worse to hide part of the cookies' value,  I think the best way is really to show the value as it is although it sometimes isn't nice to be presented in the preview tab GUI.

RFC 6265 told me that the browsers should provide the following capabilities:
   o **At least** 4096 bytes per cookie (as measured by the sum of the
      length of the cookie's name, value, and attributes).
   o  **At least** 50 cookies per domain.
   o  **At least** 3000 cookies total.

   Also, servers should use as few and as small cookies as possible to avoid reaching these implementation limits and to minimize network bandwidth due to the Cookie header being included in every request. So, let's assume devs won't write trash codes with useless large cookies ;-)

Moving forward, I'm gonna spend some effort on the JSON parser in order to be able to extract more useful info.

**Comment by lfcnassif** [comment]
You can extract large cookies as subitems, put some identification on html preview row and use that ID as the subitem name. Take a look at FirefoxSqliteParser, it optionally extract history entries as subitems to be used in timeline analysis.

**Comment by lfcnassif** [comment]
Another (more complex) example is the SQLiteParser, Blobs are extracted as subitems.

**Comment by thalespr** [comment]
@lfcnassif Did the following changes:
- Replaced the older simple JSON Parser to Jackson Parser;
- Implemented Tabs extraction;
- Now it shows URL and its title in a new table on the HTML preview GUI.

With those changes, I think this is ready for review to decide if it will be merged or not... I ran at least 100 tests with 300+ different Mozilla Saved Session files and it's fine so far (although some false positives have occurred)...

Thank you for your tips and time and let me know if anything goes wrong.

Best regards.

**Comment by lfcnassif** [comment]
Thank you very much, @thalespr! I will try to review next week.

**Comment by lfcnassif** [comment]
Sorry @thalespr, other higher priority issues took my time. Will do a final review next week.

**Comment by thalespr** [comment]
> Sorry @thalespr, other higher priority issues took my time. Will do a final review next week.

Not a problem, @lfcnassif . Take your time and let me know if I can do something to help you out on this.

**Pull request merged**
