### PR TITLE
Jabber Parser

### PR DESCRIPTION
**Pull request by rodac5**
FAZER:
            - carregar conteúdo do html original para exibição na janela text
            - carregar conteúdo do html em formato whatsapp para exibição na janela preview
            - documentação

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thanks @rodac5, I finished other works and reviews/merges of previous ready PRs. I was going to start reviewing this and just noticed you removed some recent changes in master branch in Customsignatures.xml and CategoriesByTypeConfig.txt files. So please I ask you to rebase your changes on master and send another PR without the reverting changes. Thank you.

**Comment by lfcnassif** [comment]
And please write in english next PR, thanks.

**Comment by lfcnassif** [comment]
Other recommendations about this:
- please create a new python script instead of changing the PythonParserExample.py
- translate your code comments to english
- seems you duplicated the full whatsapp template html into the script. It is better to get it using `dpf.mg.udi.gpinf.whatsappextractor.Util.readResourceAsString("wachat-html-template.txt")`
- and please revert the unintentional changes in Customsignatures.xml and CategoriesByTypeConfig.txt files

**Comment by rodac5** [comment]
OK, will do that in a new pull request!

**Comment by lfcnassif** [comment]
Thank you!

**Pull request closed without merging**
