### PR TITLE
Handle other WhatsApp for iOS message types (#2375)

### LINKED ISSUE #2375: Handle other WhatsApp for iOS Message Types
Handle other (newer) WhatsApp message types that I found in UFDR extracted from iOS devices.

### PR DESCRIPTION
**Pull request by wladimirleite**
Closes #2375.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Sorry @wladimirleite for delaying this. In ReportGenerator class, lines 601-611 were removed intentionally, right?

**Comment by wladimirleite** [comment]
> Sorry @wladimirleite for delaying this. In ReportGenerator class, lines 601-611 were removed intentionally, right?

Correct! The removed code handled extra information related to that kind of message (user joined from community), but such information is not read, so the generated message (in chat HTML preview) seemed incomplete.

**Comment by lfcnassif** [comment]
Hi @wladimirleite, thanks and sorry for delaying this. Is this PR finished?

**Comment by wladimirleite** [comment]
> Hi @wladimirleite, thanks and sorry for delaying this. Is this PR finished?

Yes, just sent two minor code changes, but just because it was not merged.

**Pull request merged**
