### PR TITLE
Face recognition functionality for IPED

### PR DESCRIPTION
**Pull request by ruisantana**
Script em python, baseado no projeto https://pypi.org/project/face-recognition/, desenvolvido para funcionar na ferramenta IPED, e que possui a funcionalidade de examinar cada evidência em busca de pessoas/rostos previamente escolhidos, criando filtros e um bookmark para os itens encontrados.

As orientações de como utilizar a funcionalidade estão descritas no cabeçalho do script. Inicialmente, os scripts foram colocados apenas nos "profiles" default, tanto em português como em inglês.

Caso a estação onde será rodado o IPED já esteja configurada para processar scripts em python, via IPED, e as bibliotecas requeridas já instaladas, será necessário apenas criar a pasta /knownfaces/, que deve estar localizada no mesmo nível do executável.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you very much @ruisantana! Will review and test this after finishing #357 (kind related) and #360, in the next week hopefully.

**Comment by lfcnassif** [comment]
Now that I fixed #380, will start reviewing this tomorrow.

**Comment by lfcnassif** [comment]
I did a first basic test and it worked fine! Will try to store face locations and encodings into index to implement a dynamic search from the analysis interface.

Is opencv just used to rotate images? I think we can call a java method to remove that dependency.

**Comment by ruisantana** [comment]
> I did a first basic test and it worked fine! Will try to store face locations and encodings into index to implement a dynamic search from the analysis interface.
> 
> Is opencv just used to rotate images? I think we can call a java method to remove that dependency.

Yes, I included this library just to provide the rotate feature. If it is possible through java method, is really better..

**Comment by lfcnassif** [comment]
image
Finished first version to search similar faces from a selected image in case. Next steps:
- allow configurable tolerance per search
- provide external face to be searched
- try to optimize code, currently is taking 3.26s per image per thread in my machine, not so bad, but with very small images with just 1 face each, this can be a problem to enable in real world cases...
- draw face boundaries in the viewer for the matches

**Comment by lfcnassif** [comment]
Hi @ruisantana, did you tested this on CPU? Not sure if running on CPU is code or hardware issue for me.

**Comment by ruisantana** [comment]
> Hi @ruisantana, did you tested this on CPU? Not sure if running on CPU is code or hardware issue for me.

Hi @lfcnassif, yes, all my tests were done using CPU. In fact, I didn't even try to use GPU.

**Comment by lfcnassif** [comment]
`show search progress in interface for large cases, still need to index one :)`
this won't be necessary, simulating a search with 1.3 million faces is taking ~3 seconds with 1 thread and almost instant with 48 threads :)
anyway, it's now possible to cancel the search

**Comment by lfcnassif** [comment]
@ruisantana I pushed dynamic search for external provided faces from GUI. I will remove the knownfaces folder and bookmark features, because they depend on providing faces before processing, ok?

**Comment by ruisantana** [comment]
> @ruisantana I pushed dynamic search for external provided faces from GUI. I will remove the knownfaces folder and bookmark features, because they depend on providing faces before processing, ok?

@lfcnassif, in less than two days you have implemented all proposals for future work and at least ten new improvements. Great! Yes, of course you can remove the folder...

**Comment by ruisantana** [comment]
bookmark too..

**Comment by lfcnassif** [comment]
image
(results of searching for GWB in images of other individuals)

I think the feature is fully functional. Lot of work to optimize code:
- load model only once
- profile time to detect faces and to extract features
- process images in batches
- reuse results of duplicate images
- test CNN algorithm from the library instead of HOG to detect faces (preliminar result was 40% faster on GPU, 0.048s per image from LFW).
- Test YOLO from other lib if face_recognition doesn't support it

**Comment by lfcnassif** [comment]
Did some research and tests. Seems face_recognition/dlib do not implement YOLO, but their cnn model is HOG + MMOD: https://github.com/davisking/dlib/blob/master/examples/dnn_mmod_ex.cpp

Also seems YOLO is much faster, but less accurate. Some useful references:
https://towardsdatascience.com/faced-cpu-real-time-face-detection-using-deep-learning-1488681c1602
https://github.com/iitzco/faced
https://www.pyimagesearch.com/2018/11/12/yolo-object-detection-with-opencv/
https://github.com/sthanhng/yoloface

I will measure the current model accuracy on LFW to compare with other model if we change in the future, but my feeling is that we have a very good precision/recall values on that dataset.

Now the real issue: measuring detection and feature extraction time, I got a total of 901s with hog model for both from java side. But measuring each inside python, got 41s for detection and ~23s for feature extraction. Each thread time is added and divided by numThreads. So python GIL is a big problem here, possibly not being released by dlib: https://github.com/ninia/jep/wiki/Jep-and-the-GIL

I tried to use multiprocessing module from python (executes functions in other processes instead of threads because of GIL), but JEP failed. Maybe creating the processes manually could work...

**Comment by hauck-jvsh** [comment]
Do you think that a mixed approach is possible (use CPU for detection and GPU for encoding)?

**Comment by lfcnassif** [comment]
> Do you think that a mixed approach is possible (use CPU for detection and GPU for encoding)?

@fsicoli suggested that, but I "think" not. face_recognition lib calls dlib as a python module, and modules uses global variables, not instances, I also checked dlib api and didn't find any function param, but I'm not a python specialist and could have missed something.

If you have GPU drivers configured, when installing dlib it is compiled with GPU support automatically, that happened with me. I tried env var CUDA_VISIBLE_DEVICES to disable it (works with tensorflow), but dlib didn't like it. To test on CPU, I had to uninstall everything, clean pip cache, remove my GPU drivers from PATH and install again.

But I have very good news, with c7d3388 simple optimization, HOG detection on CPU is much faster for high resolution images, drop from 36s to 0.65s in a different test (encoding took 1.7s, just 48 pics/faces), of course some small faces started to be lost, will make it configurable. I also tried CNN detection and it is slower on P620 GPU (5s on same downsized pics) and CNN on CPU is the slowest (37s after downsizing)

Finally I executed current code on a common HDD and face recognition task took 7% total processing time, similar to ParsingTask and IndexTask, so I'am happy with that!

I think trying to do batch face detection is not worthy, because just CNN model supports it and with just 4 threads sometimes our P620 GPU is already running out of memory. Possibly will leave as a future study :)

**Comment by lfcnassif** [comment]
I think this is ready to merge! @ruisantana, if you could do some test (even a basic one), or anyone interested in the feature, that would be great, I have made a lot of changes since the first version...

For anyone interested, just follow the steps in https://github.com/sepinf-inc/IPED/wiki/User-Manual#python-modules
and turn 'enableFaceRecogniton' on in IPEDConfig.txt

**Comment by lfcnassif** [comment]
Possible improvements for the future:
- check if it is possible to configure DLIB at runtime to use CPU/GPU per process to try a mixed approach as suggested by @fsicoli and @hauck-jvsh 
- try to reuse the same model in memory between processes to decrease memory usage on GPU to use more processes (maybe not possible)
- test batch face detection with CNN on GPU (maybe processing X images together in 1 process is faster than processing 1 image per X processes), not sure if it will be faster than HOG on CPU, the performance difference is big. I got 3x speed up on #357 with this approach but that is another model.

**Comment by ruisantana** [comment]
> I think this is ready to merge! @ruisantana, if you could do some test (even a basic one), or anyone interested in the feature, that would be great, I have made a lot of changes since the first version...
> 
> For anyone interested, just follow the steps in https://github.com/sepinf-inc/IPED/wiki/User-Manual#python-modules
> and turn 'enableFaceRecogniton' on in IPEDConfig.txt

Great! I will do some tests and answer you as soon as possible..

**Comment by lfcnassif** [comment]
> Great! I will do some tests and answer you as soon as possible..

Also feel free to review my code, I'm a python beginner

**Comment by ruisantana** [comment]
> > Great! I will do some tests and answer you as soon as possible..
> 
> Also feel free to review my code, I'm a python beginner

hi @lfcnassif, I tried to run the new version - in the same environment used in the initial version of the pull request - but I received the following message: "jep.JepException: JEP not found, all Python modules have been disabled."

I did the test on two different computers, with different versions of JEP (3.8.2 and 3.91), and both gave the same error.

Just to confirm that my environment has not changed, I ran the initial version of the functionality again (still with the knownfaces folder) and everything worked as expected. If I'm not doing anything wrong, do you have any idea what's going on? Can't this problem be related to the 2e2ec6e or 0b865fc commits?

The complete error message is as follows:

jep.JepException: JEP not found, all python modules were disabled. See https://github.com/sepinf-inc/IPED/wiki/User-Manual#python-modules
	at dpf.sp.gpinf.indexer.process.task.PythonTask.getNewJep(PythonTask.java:114)
	at dpf.sp.gpinf.indexer.process.task.PythonTask.init(PythonTask.java:218)
	at dpf.sp.gpinf.indexer.process.Worker.initTasks(Worker.java:113)
	at dpf.sp.gpinf.indexer.process.Worker.<init>(Worker.java:95)
	at dpf.sp.gpinf.indexer.process.Manager.iniciarIndexacao(Manager.java:384)
	at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:216)
	at dpf.sp.gpinf.indexer.IndexFiles.startManager(IndexFiles.java:197)
	at dpf.sp.gpinf.indexer.IndexFiles.execute(IndexFiles.java:251)
	at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:321)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at dpf.sp.gpinf.indexer.util.CustomLoader.run(CustomLoader.java:65)
	at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:317)
Caused by: java.lang.UnsatisfiedLinkError: jep.Jep.exec(JLjava/lang/String;)V
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at jep.Jep.setupJavaImportHook(Jep.java:323)
	at jep.Jep.configureInterpreter(Jep.java:310)
	at jep.SharedInterpreter.configureInterpreter(SharedInterpreter.java:64)
	at jep.Jep.<init>(Jep.java:282)
	at jep.SharedInterpreter.<init>(SharedInterpreter.java:56)
	at dpf.sp.gpinf.indexer.process.task.PythonTask.getNewJep(PythonTask.java:109)
	... 14 more

**Comment by lfcnassif** [comment]
Sorrry, forgot to say I upgraded to jep 3.9.1. Did you include the new dll to PATH? Don't remember if the parent folder is the same.

**Comment by ruisantana** [comment]
> Sorry, forgot to say I upgraded to jep 3.9.1. Did you include the new dll to PATH? I Don't remember if the parent folder is the same... Maybe you will need to remove the old dll?
> 
> The first commit you referenced just throws a more intuitive exception. The last was a small fix

Yes, just that. I removed the previous version of the dll and included the new one and now it worked.

**Comment by ruisantana** [comment]
When performing tests with some photos that would need to be rotated to be identified, the program presented the following error:
P.s.: I am using  numpy 1.20.1

C:\IPED\IPED\target\release\iped-3.19-snapshot>iped.exe -d c:\Shared\tmp1 -o c:\IPED\casos\tmp1
Traceback (most recent call last):
  File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 108, in <module>
    main()
  File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 82, in main
    img = rotateImg(img, int(tiff_orient))
  File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 28, in rotateImg
    img = np.flipup(img)
  File "C:\Users\rs-ju\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 303, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'flipup'
Traceback (most recent call last):
  File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 108, in <module>
    main()
  File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 82, in main
    img = rotateImg(img, int(tiff_orient))
  File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 28, in rotateImg
    img = np.flipup(img)
  File "C:\Users\rs-ju\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 303, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'flipup

**Comment by lfcnassif** [comment]
> When performing tests with some photos that would need to be rotated to be identified, the program presented the following error:
> P.s.: I am using numpy 1.20.1
> 
> C:\IPED\IPED\target\release\iped-3.19-snapshot>iped.exe -d c:\Shared\tmp1 -o c:\IPED\casos\tmp1
> Traceback (most recent call last):
> File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 108, in
> main()
> File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 82, in main
> img = rotateImg(img, int(tiff_orient))
> File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 28, in rotateImg
> img = np.flipup(img)
> File "C:\Users\rs-ju\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy__init__.py", line 303, in **getattr**
> raise AttributeError("module {!r} has no attribute "
> AttributeError: module 'numpy' has no attribute 'flipup'
> Traceback (most recent call last):
> File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 108, in
> main()
> File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 82, in main
> img = rotateImg(img, int(tiff_orient))
> File "C:\IPED\casos\tmp1\indexador\conf\scripts\FaceRecognitionProcess.py", line 28, in rotateImg
> img = np.flipup(img)
> File "C:\Users\rs-ju\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy__init__.py", line 303, in **getattr**
> raise AttributeError("module {!r} has no attribute "
> AttributeError: module 'numpy' has no attribute 'flipup

pushed a fix

**Comment by ruisantana** [comment]
Congratulations @lfcnassif! I did some tests and the result was impressive. The care you took in every detail of the implementation, and all the changes you made resulted in a very practical to use, dynamic, extremely fast and incredibly accurate functionality. IPED is getting more and more powerful… Congratulations again !! 

By the way, I didn't even review your code for a simple reason: I'm much more Python beginner than you ...

**Comment by lfcnassif** [comment]
Thank you @ruisantana for testing and for this PR, you are the original author, I just improved it.

Will do a simple impl for videos and fix a png transparency issue, after that will probably merge.

**Comment by ruisantana** [comment]
hi @lfcnassif, doing some more tests I came across the following messages:

C:\Users\RuiSantana\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py:962: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
...
C:\Users\RuiSantana\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py:2847: DecompressionBombWarning: Image size (133944300 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(


I believe that the first message (5 occurrences) is related to a problem already detected by you. The second I don't know, so, just in case, I decided to report them here.

**Comment by lfcnassif** [comment]
Thank you for testing! Yes, the first is the same. The second seems related to a corrupted image. Will try to redirect those warnings to log instead of sdtout.

**Comment by lfcnassif** [comment]
Merged, thank you @ruisantana!

**Pull request merged**
