### PR TITLE
HashDB

### PR DESCRIPTION
**Pull request by tc-wleite**
This implements #118, #288, #300, #307 and #364.
As it was a major refactor, it will probably require adjustments, or even a new approach.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @tc-wleite! Will review and test this carefully when some time is available.

**Comment by tc-wleite** [comment]
Thanks @lfcnassif! 
This should require some time indeed, as many things were changed. It is quite possible we will need to discuss about specific points and decisions taken, maybe revisiting parts of the proposed solution.

**Review by lfcnassif — COMMENTED** [review]
Added a simple support for quoted quotes "" in col data. Maybe it would be good to add some validation to CSV lines (e.g. check non quoted quotes in data)?

About PhotoDNA, I saw the support for ProjectVIC, but not sure if it is being read from CSV files... Is it possible to import and look up PhotoDNA of LED dataset for example?

**Comment by lfcnassif** [comment]
Forgot to say, I imported all NSRL datasets (except legacy) and ProjectVIC, intentionally non last versions, and it worked fine.

**Comment by tc-wleite** [comment]
> Added a simple support for quoted quotes "" in col data. Maybe it would be good to add some validation to CSV lines (e.g. check non quoted quotes in data)?

Sure! Current checks are just the minimal ones.
 
> About PhotoDNA, I saw the support for ProjectVIC, but not sure if it is being read from CSV files... Is it possible to import and look up PhotoDNA of LED dataset for example?

Yes, other datasets with PhotoDNA can be imported.
The only requirement is that the column uses base64 encoding (which was used by ProjectVIC and now in LED set).
I think I put the CSV file with LED PhotoDNA in our server (I don't have access now to check this), already in the expected format.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite!

**Pull request merged**
