### PR TITLE
Use thumbnails from "media_hash_thumbnail" table (#2031).

### LINKED ISSUE #2031: Extract more thumbnails from WhatsApp databases
Currently only thumbnails from "message_thumbnail" are used by WhatsApp parser for Android "new" databases.

### PR DESCRIPTION
**Pull request by wladimirleite**
Closes #2031.

### CODE REVIEW

**Comment by wladimirleite** [comment]
Added other minor fixes and improvements related to WhatsApp generated HTML.

**Comment by wladimirleite** [comment]
I created this PR just to address #2031.
However, while working on #2030, I realized that there may be some merging conflicts between them.
And the main problem is that I started to use two phones to check #2030 (initially I had only a WhatsApp database), comparing parser results with actual messages displayed on the devices. And there are differences that were solved by #2031, but I am not seeing them in #2030.
So I am closing this PR and will create a new one, which will handle both issues (and maybe #1923) together.

**Comment by lfcnassif** [comment]
Hi @wladimirleite! I can merge #1920 to avoid more merge conflicts with the improvements you are working on. I detected just very minor differences with master, so I think it's safe and I can take a closer look at them later. What do you think?

**Comment by lfcnassif** [comment]
PS: I saw you already pushed a few commits, so not sure if it will help.

**Comment by wladimirleite** [comment]
Please, do that if you can.
I can stop commiting and reverse merge with the master after you merge #1920.
This should avoid more conflicts.

**Pull request closed without merging**
