### PR TITLE
Discarded PR (Localized Number Formatting and Minor Improvements in MetadataPanel)

### PR DESCRIPTION
**Pull request by tc-wleite**
It contains #646, #649 and two possible minor fixes to regressions related to #18.

### CODE REVIEW

**Comment by tc-wleite** [comment]
@lfcnassif, I changed this back to draft as there is another option users requested here that I forgot to include in #649.

**Comment by lfcnassif** [comment]
I saw the change to draft, no problem at all!

**Comment by tc-wleite** [comment]
I am really sorry for mixing up two unrelated issues here...
Both issues have changes in the metadata panel, but other than that, no relationship.
I will discard this branch and create separated ones from the master, and then make the changes again, so it won't be a confusing.
When everything is ready I will close this pull request and make new ones.

**Comment by lfcnassif** [comment]
> I am really sorry for mixing up two unrelated issues here...

Don't worry, I have already done this some times... The worst thing about this to me is one incomplete or broken feature avoiding the merge of another finished feature, this happened in the past with large all-in-one contributions by others...

Maybe it is a good idea to put the issue number #XXX in each commit message, I think it could make commits easier to understand after merged in master.

**Comment by tc-wleite** [comment]
> Maybe it is a good idea to put the issue number #XXX in each commit message, I think it could make commits easier to find after being merged in master.

I will try to that next time!

**Comment by tc-wleite** [comment]
@lfcnassif, I see you improved and merged #646. 
Thanks!

Please leave this one open for now.
I will close it and delete this branch once I submitted another PR with changes for #649.

**Comment by lfcnassif** [comment]
Of course, don't worry!

**Comment by tc-wleite** [comment]
This PR was discarded.

**Pull request closed without merging**
