### PR TITLE
Parser for Google Drive files

### PR DESCRIPTION
**Pull request by mbichara**
Hi!

I wrote a parser for some GDrive artifacts that can be useful for (cloud) forensic analysis.
The sqlite queries were adapted from https://github.com/kacos2000/Queries (_GDrive_cloudgraph.sql_ and _GDrive_snapshot.sql_).

These artifact are created when a user installs Google Drive’s native app, named “Backup and Sync from Google”.
The following are from interest: 

Artifact | Information
-- | --
C:\Users\username\AppData\Local\ Google\Drive\user_default\snapshot.db | Files that have been synced with the user’s Google Drive account.
C:\Users\username\AppData\Local\Google\Drive\cloud_graph\cloud_graph.db | Files that have been synced with the user’s Google Drive account.
C:\Users\username\AppData\Local\ Google\Drive\user_default\sync_config.db | User’s Google Drive account info (email, name, local synced folder path)
C:\Users\username\AppData\Local\ Google\Drive\global.db | User’s Google Drive account info (email)

Just some quick considerations:

- The first two artifacts above were coded as standalone parsers (just like #31), _GDriveCloudGraphParser.java_ and _GDriveSnapshotParser.java_ . The appropriate parser is called, based on MIME type,  by _GDriveMainParser.java_ (which is registered in _ParserConfig.xml_). 
I thought keeping it independent like this may help future updates if needed, but let me know your thoughts.

- Each file entry from snapshot.db and cloud_graph.db was extracted and metadata added. I'm just not sure how to handle MD5, as I haven't used hash databases yet.

- The artifacts sync_config.db  and global.db contain some account info. These are currently just categorized, and parsed by default SQLite parser in _GDriveMainParser.java_. Would it be interesting to create a specific parser for these also?

Let me know what you think and feel free to change anything (naming, refactoring..). 
I can add info to other profiles after.

Thanks

image

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you, @mbichara! I am trying to finish a release, will take a look after that, unless someone does it before me :)

**Comment by fsicoli** [comment]
Great job! That's a very useful source of information.

**Comment by lfcnassif** [comment]
Hi @mbichara will try to crawl some sample files to test this, thanks!

**Comment by mbichara** [comment]
Alright! I'll be out for a couple of months but will gladly help after that. Cheers

**Comment by lfcnassif** [comment]
I fixed some exceptions with some samples with different table or column names, thanks to @tc-wleite sample crawling. Also added CSAM hashset look up and bookmarking of shared items found in case.

Thanks @mbichara !

**Pull request merged**
