### PR TITLE
Attachment count and flag

### LINKED ISSUE #744: Populate Message-Recipient-Address property by all email parsers
Currently this property is only populated by MSG parser. It should be also populated by EML, PST & OST parsers, so users would be able to search for a recipient address with a simple query like Message-Recipient-Address:"xxxxx@yyy.zzz", regardless of the recipient type (TO, CC or BCC).

### LINKED ISSUE #745: New properties to count the number of email attachments and to flag them
Currently we have numSubitems, but it does not apply to emails extracted from pst/ost files. And we also have pst_attachment, but it applies just to pst/ost files. It would be good to have general properties for any email type.

### PR DESCRIPTION
**Pull request by lfcnassif**
Closes #744, closes #745 

Add new properties Message:AttachmentCount and Message:IsEmailAttachment to EML, MSG, PST, OST and UFDR extracted emails. Removes old pst_attachment and pst_email_has_attachs properties.

### CODE REVIEW

**Comment by lfcnassif** [comment]
@streeg please review and test this.

**Comment by streeg** [comment]
> @streeg please review and test this.

Will do it tomorrow!

**Review by streeg — APPROVED** [review]
It seems to be working just fine! Already pulled this branch to Parser_tests and created/tested changes made.

**Comment by lfcnassif** [comment]
Thank you, @streeg. I decided to create a new MSG parser wrapper, so it can be easily tested too. I ask you to also write a test for it, thanks.

**Pull request merged**
