### PR TITLE
#802 download attachments

### LINKED ISSUE #802: Add support to download and decode WhatsApp attachments
WhatsApp attachments that were not present in the extraction may be recovered. On the msgstore database there is a link to the encrypted file and the key used to decode the file. As long as the file stills presented on the WhatsApp servers it is possible to download and decode them.

### PR DESCRIPTION
**Pull request by hauck-jvsh**
FALLBACK_DOWNLOAD_FILES must be set by a command line paramter;

closes #802

### CODE REVIEW

**Comment by hauck-jvsh** [comment]
How I can change this to a draft?
This may need to wait the downloaded file go through all the tasks.

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh, I've just changed to draft.

**Comment by hauck-jvsh** [comment]
I think that now it is ready for review.

**Comment by lfcnassif** [comment]
Thank you @hauck-jvsh !

**Comment by hauck-jvsh** [comment]
Now it is using the two phase scheme, I think its ready for review.

**Comment by lfcnassif** [comment]
Thank you @hauck-jvsh!

**Comment by hauck-jvsh** [comment]
After commit 0f2209063d9ef9d4619acc17a9b4c54f8781fc8d if more than one db is present on the case the download number may not be sequential, for example the dowloaded_item_1 could child of the first DB, and the dowloaded_item_2 could be from the second and dowloaded_item_3 of the first one again. Also the logger downloaded files will show an incorrect result, because it will show the sum of the downloaded files from all DBs.

**Comment by lfcnassif** [comment]
Good point! I don't think the numbering is critical, since one DB could use downloads from other DB, but now the logging is wrong. Could you revert? I'm already out of office... Please use lowercase chars for the counter, thank you!

**Comment by hauck-jvsh** [comment]
Sure I will revert only the counter, as the use of future seems a better option.

**Comment by lfcnassif** [comment]
@hauck-jvsh in last commit I changed the approach to just save item refs in messages in the last pass, that is done per chat, when creating the report. It was storing all items in memory, including theirs thumbs, found in case from all databases. Since the number of downloaded files is small, I think it's ok to search for them later when creating the report. The code also became simpler.

**Comment by lfcnassif** [comment]
@hauck-jvsh while testing here with different databases together, I got this:
```
java.io.StreamCorruptedException: invalid type code: 00
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.skipCustomData(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readArray(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readArray(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:?]
	at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:?]
	at dpf.mg.udi.gpinf.whatsappextractor.LinkExtractor.getCipherKey(LinkExtractor.java:111) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.LinkExtractor.extractLinks(LinkExtractor.java:204) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.searchMediaFilesForMessages(WhatsAppParser.java:1326) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.searchMediaFilesForMessagesInBatches(WhatsAppParser.java:1154) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parseAndCheckIfIsMainDb(WhatsAppParser.java:389) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.mg.udi.gpinf.whatsappextractor.WhatsAppParser.parse(WhatsAppParser.java:212) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) [tika-core-1.26.jar:1.26]
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:246) [iped-parsers-impl-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247) [iped-engine-4.0.0-snapshot.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
Could you take a look at this?

**Comment by hauck-jvsh** [comment]
Sure, could you share the databases?

**Comment by lfcnassif** [comment]
Everything looks good now, thank you @hauck-jvsh!

**Review by lfcnassif — APPROVED** [review]

**Pull request merged**
