### PR TITLE
Add support to DAV (from Dahua DVR) videos (#2054)

### LINKED ISSUE #2054: Support DAV videos
Working with a DVR, I manage to export its videos in the DAV format (created by Dahua Technology’s digital surveillance system).
They can be opened with VLC and MPlayer, but IPED didn't recognize them as videos because they have a specific signature.

### PR DESCRIPTION
**Pull request by wladimirleite**
Closes #2054.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thanks @wladimirleite! Could you send me some DAV video samples?

**Comment by wladimirleite** [comment]
> Thanks @wladimirleite! Could you send me some DAV video samples?

Sure! I will send you some samples after lunch. To be honest, they all came from the same source. I will to find other samples, although I suspect it won't be easy to find them.

**Comment by lfcnassif** [comment]
> Sure! I will send you some samples after lunch. To be honest, they all came from the same source. I will to find other samples, although I suspect it won't be easy to find them.

I just would like one or two to keep into the regression data set, thanks! About this PR, if you tested the signature rule without the extension rule (*.dav) that's enough for me.

**Comment by wladimirleite** [comment]
> Thanks @wladimirleite! Could you send me some DAV video samples?

Just sent you some samples through Teams.
Surprisingly (to me), there are DAVs in other cases.

**Review by lfcnassif — APPROVED** [review]

**Pull request merged**
