### PR TITLE
#668 Event Transcript Parser

### LINKED ISSUE #668: EventTranscriptDB parser.
In some cases MS activates the EventTranscriptDB. It should be easy to parse this SQLite database:
https://github.com/rathbuna/EventTranscript.db-Research

### PR DESCRIPTION
**Pull request by FelipeFcosta**
closes #668

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you @FelipeFcosta!

**Comment by lfcnassif** [comment]
Hi @FelipeFcosta, I think I finished reviewing this. Strings could still be localized, but since we didn't find this artifact in real world cases, not sure if it is worth.

Please take a look to see if I messed something and try to finish the incomplete no-op unit test, so we can merge this, thank you for this work!

**Comment by FelipeFcosta** [comment]
> Hi @FelipeFcosta, I think I finished reviewing this. Strings could still be localized, but since we didn't find this artifact in real world cases, not sure if it is worth.
> 
> Please take a look to see if I messed something and try to finish the incomplete no-op unit test, so we can merge this, thank you for this work!

Thanks @lfcnassif, will do

**Comment by FelipeFcosta** [comment]
Hi @lfcnassif, I finished the tests, thanks for the code improvements.

**Comment by lfcnassif** [comment]
Thank you @FelipeFcosta! I'll do the final review soon.

**Review by lfcnassif — APPROVED** [review]

**Pull request merged**
