### PR TITLE
Handle NSRL Product Code Inconsistencies

### PR DESCRIPTION
**Pull request by tc-wleite**
After the changes the importing tool (HashDBTool) accepts NSRL files with product codes that are not present in NSRLProd.txt (issue #611). 
As it is happening with too many lines in the RDS Version 2.73, I expect that it will be fixed in the provided files.
However it is better to handle this situation, as it may happen with fewer lines in future versions.

### CODE REVIEW

**Comment by lfcnassif** [comment]
@tc-wleite what do you think about printing a warning for each invalid product code while importing? Or just making the final invalid product codes message more explicit (and w/ number of invalid codes or references) so users will notice better their source hashset is broken?

**Comment by lfcnassif** [comment]
> what do you think about printing a warning for each invalid product code while importing?

forget this, I forgot the text progress bar...

**Comment by tc-wleite** [comment]
> > what do you think about printing a warning for each invalid product code while importing?
> 
> forget this, I forgot the text progress bar...
> 
> With more explicit I mean separate from other messages and with some !!! at the end.

Sure! 
To be honest, I don't expect this issue to happen with future NSRL releases, but I agree that it is important to warn the user.
What about moving the message I added to the last one, and add "WARNING:" before?

**Comment by tc-wleite** [comment]
> What about moving the message I added to the last one, and add "WARNING:" before?

I just made these simple changes, but feel free to improve it.

**Comment by lfcnassif** [comment]
Thanks @tc-wleite will merge shortly.

**Pull request merged**
