### PR TITLE
Discord cache files parser

### LINKED ISSUE #390: Discord cache files parser.
On windows the Discord application caches some conversations in the "C: \Users\{UserName}\AppData\Roaming\Cache" directory.

Create a parser to analyze data from the files.

### PR DESCRIPTION
**Pull request by felipecampanini**
Closes #390 

First version of the Discord parser

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thanks @felipecampanini! I'll try to review next week.

**Comment by lfcnassif** [comment]
I can anticipate a lot of InputStreams are not being closed.

**Comment by lfcnassif** [comment]
I pushed the wrong branch by mistake, sorry. I had to force push to clean the commit history.

**Comment by lfcnassif** [comment]
@felipecampanini is the "index" file processed by DiscordParser also located in "AppData/Roaming/discord/cache" folder? If not, is it located in a specific folder? This info would be very useful to us to try to locate samples to test this PR.

**Comment by lfcnassif** [comment]
> * I think signature pattern is matching all Chrome cache index files, but just discord data is being parsed and remaining data is being totally ignored, it used to be indexed generically using the string extractor. Maybe a custom detector could be implemented to differentiate them, I just started to think about this...

@felipecampanini I've just pushed another approach to handle above in 78f5cefef3218cfcdc2a4f25ee33906599d3e6a7. Now I'll address other features, until remaining TODOs are resolved.

**Comment by felipecampanini** [comment]
@lfcnasif I have time to work on the first two items.

Attachments are not searched in this case, I believe that not all files are stored in the cache directory, if internet access is blocked, some items will be missing (I'll check this with some tests yet).

**Comment by felipecampanini** [comment]
@lfcnassif 
As I had suspected, some attachments are not present in the cache folder.

I'm already changing the code to search for the available files directly from the "external files", which are the files in the cache folder starting with the characters "f_".

However, I couldn't come to a conclusion about how the procedure should be for files that are still available on the servers (files that can be obtained by download) but are not in the cache folder.

Could I get them while processing the case?

**Comment by lfcnassif** [comment]
Well, I'm not sure if we should start doing this. If yes, maybe ask for an user explicit permission, maybe a configuration option or/and warn to console. WhatsAppParser could also benefit of this. What other devs think? @tc-wleite @hauck-jvsh @fmpfeifer

**Comment by hauck-jvsh** [comment]
I have doubts about legal issues, if it asks for an explicit confirmation every time I think it could be done. If you think this could be done let me known , as I have made a java application that pulls out WhatsApp's attachments if they are still available on its server.

**Comment by lfcnassif** [comment]
Maybe a new --(get|download)(Internet|External|Cloud)(Data|Resources) command line option is enough, so users will need to explicitly enable it, and it won't break batch processing. I vote for --downloadInternetData

**Comment by tc-wleite** [comment]
> Well, I'm not sure if we should start doing this. If yes, maybe ask for an user explicit permission, maybe a configuration option or/and warn to console. WhatsAppParser could also benefit of this. What other devs think? @tc-wleite @hauck-jvsh @fmpfeifer

In general, I think it may have legal issues, as those files are not actually part of the evidence being analysed, but there are references to them. On the other hand, they may provide very useful information, as long the user knows what is happening.

> Maybe a new --(get|download)(Internet|External|Cloud)(Data|Resources) command line option is enough, so users will need to explicitly enable it, and it won't break batch processing. I vote for --downloadInternetData

On more vote to that option :-)

One suggestion, sorry if this was already discussed, that applies to Discord, WhatsApp or any parser that enriches its output with online data: somehow (visually) differentiate downloaded files from the ones already present in the processed evidences.

**Comment by lfcnassif** [comment]
> One suggestion, sorry if this was already discussed, that applies to Discord, WhatsApp or any parser that enriches its output with online data: somehow (visually) differentiate downloaded files from the ones already present in the processed evidences.

+1

**Comment by lfcnassif** [comment]
I think recent versions of Skype could also benefit from downloading data from Internet servers

**Comment by lfcnassif** [comment]
> --downloadInternetData

or --getInternetData

**Comment by felipecampanini** [comment]
> Maybe a new --(get|download)(Internet|External|Cloud)(Data|Resources) command line option is enough, so users will need to explicitly enable it, and it won't break batch processing. I vote for --downloadInternetData

I also vote for this option!

**Comment by lfcnassif** [comment]
> I also vote for this option!

Ok I'll expose such parameter soon, I'm out of office in the next 2 days. But this could be already implemented in parsers using an internal boolean attribute to enable/disable downloading Internet data and I can implement the logic to set that parameter later.

**Comment by hauck-jvsh** [comment]
I think that I will wait until #758 is finished, this will avoid unnecessary conflicts. After that I can start integrate my code to IPED.

**Comment by hauck-jvsh** [comment]
Just one more thing, I think that the files recovered from the internet should have a message saying that they were recovered from the internet in the chat. Maybe also a metadata to be possible to filter them from the files presented in the evidence. What do you think? @felipecampanini @lfcnassif @tc-wleite

**Comment by felipecampanini** [comment]
> Just one more thing, I think that the files recovered from the internet should have a message saying that they were recovered from the internet in the chat. Maybe also a metadata to be possible to filter them from the files presented in the evidence. What do you think? @felipecampanini @lfcnassif @tc-wleite

I also think it

**Comment by lfcnassif** [comment]
Sorry for the long delay here, I was working on other hundreds of tickets targeted for 4.0.0...

For who is going to finish this incomplete work (fix some exceptions while parsing, extract single messages to populate the graph and the timeline, download attachments available in servers), now we have the new --downloadInternetData cmd line option. For the download attachments part, the same approach used in #828 could be used as example.

**Comment by felipecampanini** [comment]
thanks for the tip @lfcnassif, I have some changes to commit, but it's not complete yet. I should complete it in the next few days, it ended up delaying a lot because of other demands from the sector. I will try to send the code in the same approach as WhatsApp attachments.

**Comment by lfcnassif** [comment]
Thanks @felipecampanini for last commits! I'll try to review in the next days. Just to confirm, you don't have more commits to push, right?

**Comment by felipecampanini** [comment]
> Thanks @felipecampanini for last commits! I'll try to review in the next days. Just to confirm, you don't have more commits to push, right?

Yes, I don't have any more commits to send. I'm working on the function to download the files from the internet, but I'm not finished yet. I remain at your disposal for any improvement or correction that may be necessary.

**Comment by lfcnassif** [comment]
Thank you!

**Comment by lfcnassif** [comment]
I also got a bunch of exceptions printed in log while processing, I collected some of them:
```
java.io.EOFException: Length to read: 160 actual: 0
	at org.apache.commons.io.IOUtils.readFully(IOUtils.java:1826)
	at org.apache.commons.io.IOUtils.readFully(IOUtils.java:1846)
	at dpf.sp.gpinf.discord.cache.CacheEntry.<init>(CacheEntry.java:144)
	at dpf.sp.gpinf.discord.cache.Index.<init>(Index.java:200)
	at dpf.sp.gpinf.discord.DiscordParser.parse(DiscordParser.java:89)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:246)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ((CTRL-CHAR, code 131)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (BufferedInputStream); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2737)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:902)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3674)
	at dpf.sp.gpinf.discord.DiscordParser.parse(DiscordParser.java:101)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:246)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
```
com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 3)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (BufferedInputStream); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:713)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:3057)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:756)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4761)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3674)
	at dpf.sp.gpinf.discord.DiscordParser.parse(DiscordParser.java:101)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:246)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
```
dpf.sp.gpinf.discord.cache.CacheAddr$InputStreamNotAvailable: Cannot open InputStream for this CacheAddr.
	at dpf.sp.gpinf.discord.cache.CacheAddr.getInputStream(CacheAddr.java:127)
	at dpf.sp.gpinf.discord.cache.CacheEntry.getResponseRawDataStream(CacheEntry.java:95)
	at dpf.sp.gpinf.discord.cache.CacheEntry.getResponseDataStream(CacheEntry.java:180)
	at dpf.sp.gpinf.discord.DiscordParser.parse(DiscordParser.java:97)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:246)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<dpf.sp.gpinf.discord.json.DiscordRoot>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (BufferedInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3674)
	at dpf.sp.gpinf.discord.DiscordParser.parse(DiscordParser.java:101)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:246)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<dpf.sp.gpinf.discord.json.DiscordRoot>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (BufferedInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3674)
	at dpf.sp.gpinf.discord.DiscordParser.parse(DiscordParser.java:101)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:246)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
```
java.lang.NullPointerException
	at dpf.sp.gpinf.discord.DiscordParser.extractMessages(DiscordParser.java:183)
	at dpf.sp.gpinf.discord.DiscordParser.parse(DiscordParser.java:151)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at dpf.sp.gpinf.indexer.parsers.IndexerDefaultParser.parse(IndexerDefaultParser.java:246)
	at dpf.sp.gpinf.indexer.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
If you have time to take a look at them, I can provide my samples for testing, thank you.

**Comment by lfcnassif** [comment]
Hi @felipecampanini, are you willing to take a look and try to fix the exceptions above? If yes, I can resolve the merge conflicts and, eventually, implement the other remaining features.

**Comment by felipecampanini** [comment]
> Hi @felipecampanini, are you willing to take a look and try to fix the exceptions above? If yes, I can resolve the merge conflicts and, eventually, implement the other remaining features.

Hi @lfcnassif, sorry for the time without replying. I will implement the remaining features and fix the exceptions. I also have other corrections to send. You had already given me some test samples, if you have new samples, could you please send them to me? Thanks.

**Comment by lfcnassif** [comment]
> Hi @lfcnassif, sorry for the time without replying. I will implement the remaining features and fix the exceptions. I also have other corrections to send. You had already given me some test samples, if you have new samples, could you please send them to me? Thanks.

Thanks @felipecampanini for replying. So I'll try to resolve the merge conflicts. I didn't collect more samples, so I think you already have mine.

**Comment by lfcnassif** [comment]
Sorry for delaying here, I just fixed the merge conflicts with master as promised.

**Comment by lfcnassif** [comment]
Thank you very much @felipecampanini for your enhancements!

> There is a limitation that I haven't been able to find alternatives yet. If a user does not send any message in the chat, it is not possible to identify him. For example: If a chat has two participants (participant 'A' and "B"), and only participant "A" sends messages, the field "Message-From" will have the value "A" and the field "Message-To " will be blank. This is because I didn't find a list with all the chat participants in the JSON file, the participant list is obtained by the nicknames of the users who sent messages in the chat. For the same reason, it is not possible to determine the device owner's user in the JSON file. I'm looking for alternatives.

Sad. If there are no alternatives, I think the missing fields could be left blank, unfortunately the Graph won't be populated, it needs both of them...

> These features were implemented, but I couldn't test it because the embedded viewer is apparently not interpreting the HTML for Discord chats. Has any configuration file been changed?

You should configure the new Chat HTML mimetype into iped.viewers.HtmlLinkViewer.isSupportedType(...) method, so javascript and case callback functions will be executed.


Did you have time to take a look at the exceptions I posted above?

**Comment by felipecampanini** [comment]
Thanks for the help with HtmlViewer, @lfcnasif!

Yes, I checked the exceptions, basically they occur for two reasons:

1 - Some chats are compressed with Brotli, this implied a correction in the getResponseDataStream method of the CacheEntry class, now the code is ready to receive files compressed with gzip or brotli (this correction is not in my last commit, I will send it soon)

2 - Some samples of the Discord folder have the GPUCache subfolder with an Index file with the same signature as the Index of the Cache subfolder. The correct behavior would be to run the parser only for the Index file in the Cache folder and not for the one in the GPUCache folder. The solution I found was to filter these files by their path, however the DiscordParser would trigger. I believe that the most correct would be not to trigger the parser for these files, is there any way to do this?

**Comment by lfcnassif** [comment]
> I believe that the most correct would be not to trigger the parser for these files, is there any way to do this?

Yes. In RefineCategoryTask.js we can change the mimetype of files based on any attribute. We can give the one in GPUCache a json generic mime, or alternatively give the parser supported mime to the correct Index file here instead.

**Comment by lfcnassif** [comment]
Another possibility is to create a JsonDetector like the SQLiteContainerDetector, it detects sqlite files based on table names, the json one could be based on the json schema.

**Comment by lfcnassif** [comment]
> 1 - Some chats are compressed with Brotli, this implied a correction in the getResponseDataStream method of the CacheEntry class, now the code is ready to receive files compressed with gzip or brotli (this correction is not in my last commit, I will send it soon)

Great!!!

**Comment by lfcnassif** [comment]
> Another possibility is to create a JsonDetector like the SQLiteContainerDetector, it detects sqlite files based on table names, the json one could be based on the json schema.

If we follow this approach, the jackson fasterxml lib should be used to don't load huge json file on memory.

**Comment by lfcnassif** [comment]
Hi @felipecampanini, I'm sorry for being far away from this... Do you have local commits to push? What is still needed to finish this in your opinion?

We are planning a 4.1 release and if this is near to be finished, maybe we could include it.

**Comment by felipecampanini** [comment]
Hi @lfcnassif, I think all that's left to do is fix the error caused by the cache in the GPUCache folder. The problem is simple to fix with RefineCategoryTask.js, but I haven't had time to solve it yet, I'll work on it now.

I made some changes to the parser to work with other caches (not just discord), however, it is still very early and I believe it would be better to leave it out of this first version.

**Comment by lfcnassif** [comment]
> Hi @lfcnassif, I think all that's left to do is fix the error caused by the cache in the GPUCache folder. The problem is simple to fix with RefineCategoryTask.js, but I haven't had time to solve it yet, I'll work on it now.

Great! Let me know if you will have time (or not) to fix it today. I'll try to review and test this again tomorrow, to try to include it in 4.1. This is an old but important PR that was delayed for a number of reasons... Anyway, even if not 100%, I think we would be better with it than without it, we can improve it later as any feature if needed...

> I made some changes to the parser to work with other caches (not just discord), however, it is still very early and I believe it would be better to leave it out of this first version.

I agree, I prefer to integrate a stable version. Thank you for your continuous work to improve it!

**Comment by felipecampanini** [comment]
> Great! Let me know if you will have time (or not) to fix it today. I'll try to review and test this again tomorrow, to try to include it in 4.1. This is an old but important PR that was delayed for a number of reasons... Anyway, even if not 100%, I think we would be better with it than without it, we can improve it later as any feature if needed...

Hi @lfcnassif, I didn't have time to finalize it yesterday, but I'm fixing it right now!

**Comment by lfcnassif** [comment]
> Hi @lfcnassif, I didn't have time to finalize it yesterday, but I'm fixing it right now!

Great, thank you very much!

**Comment by felipecampanini** [comment]
@lfcnassif, sorry for the delay, it turned out to be more difficult than I thought. Any problems let me know.

**Comment by lfcnassif** [comment]
Don't worry, I was reviewing other PR. I'll review this next week, thank you!

**Comment by lfcnassif** [comment]
I'll start reviewing this tomorrow.

**Comment by tc-wleite** [comment]
> @tc-wleite, if you have time, could you run a search for "AppData/Roaming/discord" folders in São Paulo cases? If yes, exporting some samples of the whole folder structure would help a lot to test this PR. I just have 6 samples here. And in our cases here, we don't have all needed data...

Sure! I will try to find more samples here. As far as I remember, part of these 6 samples I already collected from cases we have here. Maybe there are Discord files in cases processed recently.

**Comment by lfcnassif** [comment]
Sorry, actually I have 12 samples here.

**Comment by tc-wleite** [comment]
I found 4 new samples here, which I believe are not in the ones you already have.
I just sent them to you through Teams.

**Comment by lfcnassif** [comment]
@felipecampanini, there are many messages being extracted as subitems, but they are not being rendered because they have no content, I think this is inconsistent. Should we extract just messages being rendered, or render all messages, including empty ones?

**Comment by lfcnassif** [comment]
Messages are also being rendered in reports from youngest to oldest, this is default Discord behavior, right?

**Comment by lfcnassif** [comment]
> @felipecampanini, there are many messages being extracted as subitems, but they are not being rendered because they have no content, I think this is inconsistent. Should we extract just messages being rendered, or render all messages, including empty ones?
> 
> PS: If they should be rendered, how?

I changed to print all messages because some with attachments but with no body were being missed.

**Comment by lfcnassif** [comment]
Ok I think this is almost finished, there is just one exception left:
```
java.io.EOFException: Length to read: 160 actual: 0
	at org.apache.commons.io.IOUtils.readFully(IOUtils.java:1826)
	at org.apache.commons.io.IOUtils.readFully(IOUtils.java:1846)
	at iped.parsers.discord.cache.CacheEntry.<init>(CacheEntry.java:153)
	at iped.parsers.discord.cache.Index.<init>(Index.java:200)
	at iped.parsers.discord.DiscordParser.parse(DiscordParser.java:92)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at iped.parsers.standard.StandardParser.parse(StandardParser.java:245)
	at iped.engine.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
It is printed 43 times in the log. Seems not expected to me, @felipecampanini could you take a look?

**Comment by lfcnassif** [comment]
> It is printed 43 times in the log

All of them refer to CacheAddr fileType 2, 3 or 4.

**Comment by felipecampanini** [comment]
> I changed to print all messages because some with attachments but with no text body were being missed.

I believe this is the best solution

**Comment by felipecampanini** [comment]
> Ok I think this is almost finished, there is just one exception left:
> 
> ```
> java.io.EOFException: Length to read: 160 actual: 0
> 	at org.apache.commons.io.IOUtils.readFully(IOUtils.java:1826)
> 	at org.apache.commons.io.IOUtils.readFully(IOUtils.java:1846)
> 	at iped.parsers.discord.cache.CacheEntry.<init>(CacheEntry.java:153)
> 	at iped.parsers.discord.cache.Index.<init>(Index.java:200)
> 	at iped.parsers.discord.DiscordParser.parse(DiscordParser.java:92)
> 	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
> 	at iped.parsers.standard.StandardParser.parse(StandardParser.java:245)
> 	at iped.engine.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> ```
> 
> It is printed 43 times in the log. Seems not expected to me, @felipecampanini could you take a look?



> > It is printed 43 times in the log
> 
> All of them refer to CacheAddr fileType 2, 3 or 4.

Thanks, I'll check it out now

**Comment by lfcnassif** [comment]
> In truth no. With regard to the message rendering order, the Discord interface is similar to WhatsApp, Telegram, etc, the parser renders in the exact order they are found in the JSON files, that's why there was this behavior, I will change it today to be similar to the others parsers.

Thanks, let me implement this. As you know better the Discord cache parsing logic, I think your effort would be better used investigating the remaining exception above.

**Comment by lfcnassif** [comment]
@felipecampanini commit [f098e63](https://github.com/sepinf-inc/IPED/pull/687/commits/f098e6339450e1e634ea75cbc01c898ea6cf4c06) fixed the remaining exceptions, including the EOFException above, please take a look to double check if the logic is correct. If yes, I'll merge this.

**Review by lfcnassif — APPROVED** [review]
Tests done by @felipecampanini passed, mine too. Thank you very much for this PR and for your patience!

**Comment by lfcnassif** [comment]
Just saw I referenced a wrong issue number in many commits, sorry... Since @felipecampanini didn't push any commit after them, I'll fix the commit message and and force push.

**Pull request merged**
