### PR TITLE
Review WhatsApp Message compareTo() to avoid "Comparison method violates its general contract" exceptions.

### LINKED ISSUE #2337: Error parsing WhatsApp DB (Comparison method violates its general contract)
Another user reported the following error (it happens both with 4.1.x and master).
Analysing the database, the issue is caused by the way messages are sorted.
It may fail when a very specific combination of records (with zeroes or null values in the columns used) is present, which is the case of the triggering database.
I will submit a fix shortly.

```
2024-10-15 09:32:48	[ERROR]	[parsers.whatsapp.WhatsAppParser]			Error parsing WhatsApp: Item: XXX/msgstore.db type: sqlite size: 61648896
org.apache.tika.exception.TikaException: WAExtractorException Exception
	at iped.parsers.whatsapp.WhatsAppParser.parseWhatsappMessages(WhatsAppParser.java:399) ~[iped-parsers-impl-4.2-snapshot.jar:?]
	at iped.parsers.whatsapp.WhatsAppParser.parse(WhatsAppParser.java:259) [iped-parsers-impl-4.2-snapshot.jar:?]
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298) [tika-core-2.4.0-p1.jar:2.4.0]
	at iped.parsers.standard.StandardParser.parse(StandardParser.java:245) [iped-parsers-impl-4.2-snapshot.jar:?]
	at iped.engine.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247) [iped-engine-4.2-snapshot.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeHi(Unknown Source) ~[?:?]
	at java.util.ComparableTimSort.mergeAt(Unknown Source) ~[?:?]
	at java.util.ComparableTimSort.mergeForceCollapse(Unknown Source) ~[?:?]
	at java.util.ComparableTimSort.sort(Unknown Source) ~[?:?]
	at java.util.Arrays.sort(Unknown Source) ~[?:?]
	at java.util.Arrays.sort(Unknown Source) ~[?:?]
	at java.util.ArrayList.sort(Unknown Source) ~[?:?]
	at java.util.Collections.sort(Unknown Source) ~[?:?]
	at iped.parsers.whatsapp.ExtractorAndroidNew.extractChatList(ExtractorAndroidNew.java:150) ~[iped-parsers-impl-4.2-snapshot.jar:?]
	at iped.parsers.whatsapp.Extractor.getChatList(Extractor.java:34) ~[iped-parsers-impl-4.2-snapshot.jar:?]
	at iped.parsers.whatsapp.WhatsAppParser.parseWhatsappMessages(WhatsAppParser.java:391) ~[iped-parsers-impl-4.2-snapshot.jar:?]
	... 9 more

```

### PR DESCRIPTION
**Pull request by wladimirleite**
Fix #2337.

### CODE REVIEW

**Comment by wladimirleite** [comment]
Unit tests are working again.
I tested with 4 database samples (Android old, new, iOS and an Android that I have the device here), and the result seems fine.

**Comment by lfcnassif** [comment]
Thank you @wladimirleite! Just to confirm commit [39c1a37](https://github.com/sepinf-inc/IPED/pull/2338/commits/39c1a37c7746ff8e90cf586cedd65132d4e8407f) is good, right?

**Comment by wladimirleite** [comment]
> Thank you @wladimirleite! Just to confirm commit [39c1a37](https://github.com/sepinf-inc/IPED/pull/2338/commits/39c1a37c7746ff8e90cf586cedd65132d4e8407f) is good, right?

No! Sorry, I will fix it.

**Comment by wladimirleite** [comment]
> > Thank you @wladimirleite! Just to confirm commit [39c1a37](https://github.com/sepinf-inc/IPED/pull/2338/commits/39c1a37c7746ff8e90cf586cedd65132d4e8407f) is good, right?
> 
> No! Sorry, I will fix it.

I believe it is correct (and a bit clearer) now.
I am sorry for the last wrong commits, @lfcnassif... 
I was doing other things in parallel and messed up.

Priority order should be: `sortId` -> `timeStamp` -> `id`.
For new databases, `sortId` is usually present in all records. For older ones, no `sortId`, but `timeStamp` is always present.
In practice, the fallback is only used in very specific cases, only between `sortId` and `timeStamp`.

**Pull request merged**
