### PR TITLE
APK Parser (#1953)

### LINKED ISSUE #1953: APK Parser
Currently APK files (Android Packages) are parsed by `iped.parsers.compress.PackageParser`.
When processing UFDRs with many APK, it usually takes quite some time parsing these files, and the output is usually not very useful. 
Depending on the UFDR content and processing options, time spent parsing APKs is usually between 10% and 40% of the whole processing time.

I made some tests with a few libraries, and found https://github.com/hsiafan/apk-parser the best option.
Although the project is not active anymore, it is pretty straightforward to use, no native code (Java only), only one very small additional JAR (208 kB), popular project (has 1.2K stars), and handled all sample APKs that I tried.

### PR DESCRIPTION
**Pull request by tc-wleite**
Closes #1953.
I managed to overcome the main limitations of the library used to parse the APKs.
There are a couple of TODO's related to certificates dates metadata that can be solved during review.

Processing 1K APKs (~12 GB) now took about 1 minute, while it was taking ~25 minutes before (with the default PackageParser). Index had 2.5 GB before, and now 20 MB.

A sample output of the parser:
image

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you very much @tc-wleite!

**Comment by tc-wleite** [comment]
I ran a performance test with the 4 UDFRs which were extracted from Android phones used in #1912 tests, comparing total processing time between master branch and this PR (which includes an APK parser):

Since there was a lot of performance changes recently, I repeated the tests:

| # | Type | Size (GB) | Total Items | Master Processing Time (s) |  Processing Time (s) using the APK Parser | Processing Time Reduction |
| :---: | :---: | ---: | ---: | ---: | ---: | :---: |
| 1 | UFDR | 2.4 | 57,495 | **555** | **500** | **10%** |
| 2 | UFDR | 18 | 118,297 | **1,494** | **649** | **57%** |
| 5 | UFDR | 33 | 697,193 | **3,553** | **3,008** | **15%** |
| 6 | UFDR | 37 | 1,596,925 | **4,342** | **3,546** | **18%** |

So, using the APK parser would reduce a bit the processing time of Android UFDRs.

**Comment by patrickdalla** [comment]
Hi wladmir

I will review tomorrow your code

could you share your test cases with me?

Em seg., 13 de nov. de 2023 16:34, Wladimir Leite ***@***.***>
escreveu:

**Comment by tc-wleite** [comment]
> I will review tomorrow your code.
> Could you share your test cases with me? 

Sure!
I just used APKs exported from some Android UFDRs I am working with (and for some test the UFDRs themselves).
I will export some of these APKs and send them to you through Teams.

**Comment by tc-wleite** [comment]
> I will export some of these APKs and send them to ~~you through Teams~~ our internal WebDAV server.

I just copied a 7-Zip (~14 GB) with some samples to \Temp\Wladimir.

**Comment by lfcnassif** [comment]
> could you share your test cases with me?

I'll start a crawl in BSB cases database through the night.

**Comment by lfcnassif** [comment]
> could you share your test cases with me?

@patrickdalla I just shared 37K APKs from 87 cases with you.

**Comment by patrickdalla** [comment]
Hi @tc-wleite , IPED already have an certificate parser. I extracted the certificate data and enabled CertificateParser in ParsersConfig.xml (not enabled by default) and resulted in something like the image below. This could be a reasonable approach?

@lfcnassif I don't remember well CertificateParser is not enabled by default. What I remember is that the certificate carver carves a lot of certificates, many of them duplicated many times.


image

**Comment by tc-wleite** [comment]
> Hi @tc-wleite , IPED already have an certificate parser. I extracted the certificate data and enabled CertificateParser in ParsersConfig.xml (not enabled by default) and resulted in something like the image below. This could be a reasonable approach?

Hi @patrickdalla!
Do you mean extract certificate data as subitems of APK? It seems a good idea. In such case, metadata set in the APK could be removed, as it would be set for its children.

Just a couple of minor details:
- I think that setting the type of the properties "certificate:notafter" and "certificate:notbefore" as dates would avoid the extra properties with ":date" suffix.
- Most propertiy names use camel case, so perhaps "notAfter" and "notBefore" would be more readable.

**Comment by patrickdalla** [comment]
I have just reviewed Pkcs7Parser code from tika.
 
Pkcs7 is a container spec to hold content and its signature info in same file/stream. Pkcs7Parser of tika only strips/ignores the signature and delegate the content parsing to the corresponding parser. Pkcs7Parser doesn't parse any signature and respectives certification information.

Pkcs7 is most used to save certification revogation list and certification files itself (when included with entire certificates of certification path). The CertificateParser uses java.security.cert.CertificateFactory that can extract the certificates these files PKCS7 formatted content.

PKCS7 is not the format of the certificate used to sign the APK.

It seems from https://issues.apache.org/jira/browse/TIKA-3205, code done after the implementation of CertificateParser, that TIKA didn't classified PEM and DER files as "x-x509-ca-cert". But now it do.

I have created in CertificateParser "application/x-pem-file" and "application/pkix-cert" mime-types to identify this kind of content, but now it seems it can use the new "application/x-x509-ca-cert" identified by Tika.

I will create an issue with this same info.

**Comment by patrickdalla** [comment]
Anyway, I will finish reviewing this PR. If CategoriesToExpand.txt is configured to expand "Android Applications" category, it will create a new subitem with the certificate data. Tika is classifying this new subitem as application/x-x509-cert. When CertificateParser is reviewed later, it will parse this accordingly.

**Comment by lfcnassif** [comment]
> I have just reviewed Pkcs7Parser code from tika.
> 
> Pkcs7 is a container spec to hold content and its signature info in same file/stream. Pkcs7Parser of tika only strips/ignores the signature and delegate the content parsing to the corresponding parser. Pkcs7Parser doesn't parse any signature and respectives certification information.
> 
> Pkcs7 is most used to save certification revogation list and certification files itself (when included with entire certificates of certification path). The CertificateParser uses java.security.cert.CertificateFactory that can extract the certificates these files PKCS7 formatted content.
> 
> PKCS7 is not the format of the certificate used to sign the APK.
> 
> It seems from https://issues.apache.org/jira/browse/TIKA-3205, code done after the implementation of CertificateParser, that TIKA didn't classified PEM and DER files as "x-x509-ca-cert". But now it do.
> 
> I have created in CertificateParser "application/x-pem-file" and "application/pkix-cert" mime-types to identify this kind of content, but now it seems it can use the new "application/x-x509-ca-cert" identified by Tika.
> 
> I will create an issue with this same info.

Thank you @patrickdalla for your analysis!

**Review by patrickdalla — APPROVED** [review]
After internationalization code and the creation of specif category for APK, it is good.

**Comment by lfcnassif** [comment]
Thanks @patrickdalla for your review. @tc-wleite is @patrickdalla approach fine to you?

**Comment by tc-wleite** [comment]
> Thanks @patrickdalla for your review. @tc-wleite is @patrickdalla approach fine to you?

Sure, it seems fine! I can run a last test before merging, but I will be able to do that in the afternoon.

**Comment by tc-wleite** [comment]
Hi @lfcnassif!
I ran a large test and everything seems fine.
Just made a few minor (mostly visual) adjustments.

**Comment by lfcnassif** [comment]
Thank you @tc-wleite for your adjustments and for testing again! Before merging, I would like to do 2 comments:
- Maybe changes in CertificateParser would fit better in #1981, but they look fine;
- @patrickdalla is the addition of `application/x-pem-file` to `MakePreviewConfig.txt` intentional here?

**Comment by patrickdalla** [comment]
It was. but I reverted to put changes related to CertificateParser in the
other PR, and forgot to revert this inclusion on MakePreview. You can
revert if you want to merge this PR still today, or tomorrow I will do.

Em qua., 15 de nov. de 2023 20:35, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
Thanks @patrickdalla. I also removed the changes in CertificateParser, since most of them are included in #1981 to avoid possible merge conflicts.

**Pull request merged**
