### PR TITLE
Export case User Interface

### PR DESCRIPTION
**Pull request by gfd2020**
The PR export the entire case (along with the evidences) to a folder chosen by the user.

### CODE REVIEW

**Review by lfcnassif — COMMENTED** [review]
Hi @gfd2020, thanks for this PR. But my thoughts about this "export case" feature is to include it in the case creation UI implemented in #1341, together into that PR or after it is integrated. Users wouldn't need to open the case to just copy it to other location. I think it makes more sense to put this into the case management UI. What do you think?

**Comment by gfd2020** [comment]
> Hi @gfd2020, thanks for this PR. But my thoughts about this "export case" feature is to include it in the case creation UI implemented in #1341, together into that PR or after it is integrated. Users wouldn't need to open the case to just copy it to other location. I think it makes more sense to put this into the case management UI. What do you think?

I think it could have both. Will the creation UI be an integral part of a processed case?

**Comment by lfcnassif** [comment]
> I think it could have both. Will the creation UI be an integral part of a processed case?

Initially not. Part of it, the task/module selection panel will be added to the analysis UI when #24 is implemented in the future, so users will be able to run selected modules after the initial processing.

**Comment by gfd2020** [comment]
> > I think it could have both. Will the creation UI be an integral part of a processed case?
> 
> Initially not. Part of it, the task/module selection panel will be added to the analysis UI when #24 is implemented in the future, so users will be able to run selected modules after the initial processing.

In this case, if someone only has the case processed, how will they export it to another place if they don't have Creatin UI installed?

**Comment by lfcnassif** [comment]
> In this case, if someone only has the case processed, how will they export it to another place if they don't have Creatin UI installed?

Simply copying by Windows Explorer? Internal absolute paths should be updated by the Analysis UI when it is opened from the copied case. Isn't that working?

**Comment by gfd2020** [comment]
> 
> Simply copying by Windows Explorer? Internal absolute paths should be updated by the Analysis UI when it is opened from the copied case. Isn't that working?

I think it's working. But this PR does everything automatically and estimates the size needed for copying. I think that for a common user it is a bit complicated for them to fix the paths. Make a test and tell me if it's worth it.

**Pull request closed without merging**
