### PR TITLE
MFT Entries carving (#1344)

### PR DESCRIPTION
**Pull request by tc-wleite**
I still need to run more tests and make a post here with some details and points to be discussed and improved.

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thank you very much for this @tc-wleite!

**Comment by lfcnassif** [comment]
Hi @tc-wleite, did you close this by accident?

**Comment by tc-wleite** [comment]
Hi @lfcnassif! 
No, it was intentional. Sorry I forgot to leave a comment.

I still have a few important concerns about the feature itself. 
As this PR was opened for a long time, and I am not sure when (and if) #1344 will be finished, I thought it was better to close it, and maybe open a new one in the future.

**Comment by lfcnassif** [comment]
Hi @tc-wleite, no problem at all! When you have available time, if you could share your concerns on #1344, maybe someone may have some idea to help.

**Pull request closed without merging**
