### PR TITLE
Fix #698 Shareaza album folders and files missing

### LINKED ISSUE #698: Shareaza parser missing some files
Files, that are present in Shareaza albums but are not in the filesystem, aren't showed in the HTML output. This was found by  Hugo Kling a college from São Paulo.

### PR DESCRIPTION
**Pull request by fmpfeifer**

### CODE REVIEW

**Comment by lfcnassif** [comment]
Thanks, @fmpfeifer! I will give priority to merge this next week.

**Comment by lfcnassif** [comment]
@tc-wleite do you have some Library(1|2).dat files so I can test this? I have just 3 and I didn't found any more in ~600 local cases here...

**Comment by tc-wleite** [comment]
> @tc-wleite do you have some Library(1|2).dat files so I can test this? I have just 3 and I didn't found any more in ~600 local cases here...

I certainly have a few here. I will collect them and send to you after lunch.

**Comment by tc-wleite** [comment]
Uploaded ~15 files to my temp folder.

**Comment by lfcnassif** [comment]
Got it, thank you!

**Pull request merged**
